aa.h File Reference
Definition of an amino acid.
#include `formula.h`
Data Structures
struct amino_acid_CF
Structure representing an amino acid.
Typedefs
typedef struct amino_acid_CF aa_CF_t
Structure representing an amino acid.
Functions
void init_peptid_link (element_t *elem_table, int elem_table_size)
Procedure which initialises the formula of peptid liaison and the util formulae.
 aa_CF_t * get_amino_acid_table (const char *filename, element_t *elem_table, int elem_table_size)
Function which initialise and return the amino acid formula table stored in a file.
void free_amino_acid_table (aa_CF_t *aa_table)
Procedure which frees the memory allocated for an amino acid table.
 formula_t * get_util_formula (const char *name)
Function which allows to get a already calculated formula.
void free_peptide_link ()
Procedure which frees the formula of the peptide link and the util formulae.
void print_amino_acid_table (aa_CF_t *aa_table)
Procedure which prints on the screen the amino acid table.
void fprint_amino_acid_table (FILE *file, aa_CF_t *aa_table)
Procedure which prints in a file the amino acid table.
void set_X (char amino_acid)
Procedure which allows to set the amino acid that will be used when X is met in a FASTA file.
void set_Z (char amino_acid)
Procedure which allows to set the amino acid that will be used when Z is met in a FASTA file.
void set_B (char amino_acid)
Procedure which allows to set the amino acid that will be used when B is met in a FASTA file.
char get_X ()
Function which allows to access to the amino acid used for X.
char get_Z ()
Function which allows to access to the amino acid used for Z.
char get_B ()
Function which allows to access to the amino acid used for B.
Detailed Description
Definition of an amino acid.
Author
Nicolas GRUSZCZYNSKA and Nicolas DOLET (2005).
 Modified and updated by Jean-Charles BOISSON (2005-2008).
Warning
Copyright USTL
 This software is governed by the CeCILL-C license under French law and abiding by the rules of distribution of free software.
Typedef Documentation
aa_CF_t
typedef struct amino_acid_CF aa_CF_t
Structure representing an amino acid.
Function Documentation
fprint_amino_acid_table()
void fprint_amino_acid_table (FILE * file, aa_CF_t * aa_table)
Procedure which prints in a file the amino acid table.
Parameters
file The file where the amino acid table will be printed.
aa_table The amino acid table to print.
Definition at line 434 of file aa.cpp.
References formula_tochar(), and get_weight().
free_amino_acid_table()
void free_amino_acid_table (aa_CF_t * aa_table)
Procedure which frees the memory allocated for an amino acid table.
Parameters
aa_table The amino acid table.
Definition at line 208 of file aa.cpp.
References error(), free_formula(), and FREE_MEMORY_ERROR.
Referenced by free_tables().
free_peptide_link()
void free_peptide_link ()
Procedure which frees the formula of the peptide link and the util formulae.
Definition at line 317 of file aa.cpp.
References CH, CO, CO2H, error(), free_formula(), FREE_MEMORY_ERROR, H, H2O, NH, NH2, NH3, NHCHCO, and OH.
Referenced by free_tables().
get_amino_acid_table()
 aa_CF_t* get_amino_acid_table (const char * filename, element_t * elem_table, int elem_table_size)
Function which initialise and return the amino acid formula table stored in a file.
Parameters
filename The file which contains the table.
elem_table The element table.
elem_table_size The number of elements in the table.
Returns
The first aa_CF_t structure.
Definition at line 138 of file aa.cpp.
References amino_acid_CF::add_modif, B, copy_formula(), error(), amino_acid_CF::form, IO_ERROR, MEMORY_ALLOCATION_ERROR, read_formula(), amino_acid_CF::sub_modif, X, and Z.
get_B()
char get_B ()
Function which allows to access to the amino acid used for B.
Returns
The used amino acid used.
Definition at line 486 of file aa.cpp.
References B.
get_util_formula()
 formula_t* get_util_formula (const char * name)
Function which allows to get a already calculated formula.
Parameters
name The char* form of the wanted formula.
Returns
The wanted forumla.
Definition at line 235 of file aa.cpp.
References CH, CO, CO2H, error(), H, H2O, NH, NH2, NH3, NHCHCO, OH, and USAGE_ERROR.
Referenced by digest(), fusion_peptide(), get_formula_from_sequence(), get_formulae_of_peptides(), get_peptide_formula_from_another_protein(), and get_peptide_formula_from_index().
get_X()
char get_X ()
Function which allows to access to the amino acid used for X.
Returns
The used amino acid used.
Definition at line 474 of file aa.cpp.
References X.
get_Z()
char get_Z ()
Function which allows to access to the amino acid used for Z.
Returns
The used amino acid used.
Definition at line 480 of file aa.cpp.
References Z.
init_peptid_link()
void init_peptid_link (element_t * elem_table, int elem_table_size)
Procedure which initialises the formula of peptid liaison and the util formulae.
Parameters
elem_table The element table.
elem_table_size The number of elements in the table.
Definition at line 123 of file aa.cpp.
References CH, CO, CO2H, H, H2O, NH, NH2, NH3, NHCHCO, OH, and read_formula().
Referenced by tables_initialisation().
print_amino_acid_table()
void print_amino_acid_table (aa_CF_t * aa_table)
Procedure which prints on the screen the amino acid table.
Parameters
aa_table The amino acid table.
Definition at line 412 of file aa.cpp.
References formula_tochar().
set_B()
void set_B (char amino_acid)
Procedure which allows to set the amino acid that will be used when B is met in a FASTA file.
Parameters
amino_acid The amino acid corresponding to B.
Definition at line 468 of file aa.cpp.
References B.
Referenced by load_string_keyword().
set_X()
void set_X (char amino_acid)
Procedure which allows to set the amino acid that will be used when X is met in a FASTA file.
Parameters
amino_acid The amino acid corresponding to X.
Definition at line 456 of file aa.cpp.
References X.
Referenced by load_string_keyword().
set_Z()
void set_Z (char amino_acid)
Procedure which allows to set the amino acid that will be used when Z is met in a FASTA file.
Parameters
amino_acid The amino acid corresponding to Z.
Definition at line 462 of file aa.cpp.
References Z.
Referenced by load_string_keyword().