aa.cpp File Reference
Implementation of the methods defined in aa.h.
#include `aa.h`
Functions
void init_peptid_link (element_t *elem_table, int elem_table_size)
Procedure which initialises the formula of peptid liaison and the util formulae.
 aa_CF_t * get_amino_acid_table (const char *filename, element_t *elem_table, int elem_table_size)
Function which initialise and return the amino acid formula table stored in a file.
void free_amino_acid_table (aa_CF_t *aa_table)
Procedure which frees the memory allocated for an amino acid table.
 formula_t * get_util_formula (const char *name)
Function which allows to get a already calculated formula.
void free_peptide_link ()
Procedure which frees the formula of the peptide link and the util formulae.
void print_amino_acid_table (aa_CF_t *aa_table)
Procedure which prints on the screen the amino acid table.
void fprint_amino_acid_table (FILE *file, aa_CF_t *aa_table)
Procedure which prints in a file the amino acid table.
void set_X (char amino_acid)
Procedure which allows to set the amino acid that will be used when X is met in a FASTA file.
void set_Z (char amino_acid)
Procedure which allows to set the amino acid that will be used when Z is met in a FASTA file.
void set_B (char amino_acid)
Procedure which allows to set the amino acid that will be used when B is met in a FASTA file.
char get_X ()
Function which allows to access to the amino acid used for X.
char get_Z ()
Function which allows to access to the amino acid used for Z.
char get_B ()
Function which allows to access to the amino acid used for B.
Variables
 formula_t * H =NULL
Variable that corresponds to the H formula.
 formula_t * OH =NULL
Variable that corresponds to the OH formula.
 formula_t * NHCHCO =NULL
Variable that corresponds to the NHCHCO formula.
 formula_t * H2O =NULL
Variable that corresponds to the H2O formula.
 formula_t * CO =NULL
Variable that corresponds to the CO formula.
 formula_t * NH =NULL
Variable that corresponds to the NH formula.
 formula_t * NH3 =NULL
Variable that corresponds to the NH3 formula.
 formula_t * NH2 =NULL
Variable that corresponds to the NH2 formula.
 formula_t * CH =NULL
Variable that corresponds to the CH formula.
 formula_t * CO2H =NULL
Variable that corresponds to the CO2H formula.
char X ='G'
Variable that corresponds to the value of the amino acid X read in a fasta file.
char Z ='E'
Variable that corresponds to the value of the amino acid Z read in a fasta file.
char B ='D'
Variable that corresponds to the value of the amino acid B read in a fasta file.
Detailed Description
Implementation of the methods defined in aa.h.
Author
Nicolas GRUSZCZYNSKA and Nicolas DOLET (2005).
 Modified and updated by Jean-Charles BOISSON (2005-2008).
Warning
Copyright USTL
 This software is governed by the CeCILL-C license under French law and abiding by the rules of distribution of free software.
Function Documentation
fprint_amino_acid_table()
void fprint_amino_acid_table (FILE * file, aa_CF_t * aa_table)
Procedure which prints in a file the amino acid table.
Parameters
file The file where the amino acid table will be printed.
aa_table The amino acid table to print.
Definition at line 434 of file aa.cpp.
References formula_tochar(), and get_weight().
free_amino_acid_table()
void free_amino_acid_table (aa_CF_t * aa_table)
Procedure which frees the memory allocated for an amino acid table.
Parameters
aa_table The amino acid table.
Definition at line 208 of file aa.cpp.
References error(), free_formula(), and FREE_MEMORY_ERROR.
Referenced by free_tables().
free_peptide_link()
void free_peptide_link ()
Procedure which frees the formula of the peptide link and the util formulae.
Definition at line 317 of file aa.cpp.
References CH, CO, CO2H, error(), free_formula(), FREE_MEMORY_ERROR, H, H2O, NH, NH2, NH3, NHCHCO, and OH.
Referenced by free_tables().
get_amino_acid_table()
 aa_CF_t * get_amino_acid_table (const char * filename, element_t * elem_table, int elem_table_size)
Function which initialise and return the amino acid formula table stored in a file.
Parameters
filename The file which contains the table.
elem_table The element table.
elem_table_size The number of elements in the table.
Returns
The first aa_CF_t structure.
Definition at line 138 of file aa.cpp.
References amino_acid_CF::add_modif, B, copy_formula(), error(), amino_acid_CF::form, IO_ERROR, MEMORY_ALLOCATION_ERROR, read_formula(), amino_acid_CF::sub_modif, X, and Z.
get_B()
char get_B ()
Function which allows to access to the amino acid used for B.
Returns
The used amino acid used.
Definition at line 486 of file aa.cpp.
References B.
get_util_formula()
 formula_t * get_util_formula (const char * name)
Function which allows to get a already calculated formula.
Parameters
name The char* form of the wanted formula.
Returns
The wanted forumla.
Definition at line 235 of file aa.cpp.
References CH, CO, CO2H, error(), H, H2O, NH, NH2, NH3, NHCHCO, OH, and USAGE_ERROR.
Referenced by digest(), fusion_peptide(), get_formula_from_sequence(), get_formulae_of_peptides(), get_peptide_formula_from_another_protein(), and get_peptide_formula_from_index().
get_X()
char get_X ()
Function which allows to access to the amino acid used for X.
Returns
The used amino acid used.
Definition at line 474 of file aa.cpp.
References X.
get_Z()
char get_Z ()
Function which allows to access to the amino acid used for Z.
Returns
The used amino acid used.
Definition at line 480 of file aa.cpp.
References Z.
init_peptid_link()
void init_peptid_link (element_t * elem_table, int elem_table_size)
Procedure which initialises the formula of peptid liaison and the util formulae.
Parameters
elem_table The element table.
elem_table_size The number of elements in the table.
Definition at line 123 of file aa.cpp.
References CH, CO, CO2H, H, H2O, NH, NH2, NH3, NHCHCO, OH, and read_formula().
Referenced by tables_initialisation().
print_amino_acid_table()
void print_amino_acid_table (aa_CF_t * aa_table)
Procedure which prints on the screen the amino acid table.
Parameters
aa_table The amino acid table.
Definition at line 412 of file aa.cpp.
References formula_tochar().
set_B()
void set_B (char amino_acid)
Procedure which allows to set the amino acid that will be used when B is met in a FASTA file.
Parameters
amino_acid The amino acid corresponding to B.
Definition at line 468 of file aa.cpp.
References B.
Referenced by load_string_keyword().
set_X()
void set_X (char amino_acid)
Procedure which allows to set the amino acid that will be used when X is met in a FASTA file.
Parameters
amino_acid The amino acid corresponding to X.
Definition at line 456 of file aa.cpp.
References X.
Referenced by load_string_keyword().
set_Z()
void set_Z (char amino_acid)
Procedure which allows to set the amino acid that will be used when Z is met in a FASTA file.
Parameters
amino_acid The amino acid corresponding to Z.
Definition at line 462 of file aa.cpp.
References Z.
Referenced by load_string_keyword().
Variable Documentation
B
char B ='D'
Variable that corresponds to the value of the amino acid B read in a fasta file.
Definition at line 120 of file aa.cpp.
Referenced by get_amino_acid_table(), get_B(), and set_B().
CH
 formula_t * CH =NULL
Variable that corresponds to the CH formula.
Definition at line 98 of file aa.cpp.
Referenced by free_peptide_link(), get_util_formula(), and init_peptid_link().
CO
 formula_t * CO =NULL
Variable that corresponds to the CO formula.
Definition at line 78 of file aa.cpp.
Referenced by free_peptide_link(), get_util_formula(), and init_peptid_link().
CO2H
 formula_t * CO2H =NULL
Variable that corresponds to the CO2H formula.
Definition at line 103 of file aa.cpp.
Referenced by free_peptide_link(), get_util_formula(), and init_peptid_link().
H
 formula_t * H =NULL
Variable that corresponds to the H formula.
Definition at line 58 of file aa.cpp.
Referenced by free_peptide_link(), get_util_formula(), and init_peptid_link().
H2O
 formula_t * H2O =NULL
Variable that corresponds to the H2O formula.
Definition at line 73 of file aa.cpp.
Referenced by free_peptide_link(), get_util_formula(), and init_peptid_link().
NH
 formula_t * NH =NULL
Variable that corresponds to the NH formula.
Definition at line 83 of file aa.cpp.
Referenced by free_peptide_link(), get_util_formula(), and init_peptid_link().
NH2
 formula_t * NH2 =NULL
Variable that corresponds to the NH2 formula.
Definition at line 93 of file aa.cpp.
Referenced by free_peptide_link(), get_util_formula(), and init_peptid_link().
NH3
 formula_t * NH3 =NULL
Variable that corresponds to the NH3 formula.
Definition at line 88 of file aa.cpp.
Referenced by free_peptide_link(), get_util_formula(), and init_peptid_link().
NHCHCO
 formula_t * NHCHCO =NULL
Variable that corresponds to the NHCHCO formula.
Definition at line 68 of file aa.cpp.
Referenced by free_peptide_link(), get_util_formula(), and init_peptid_link().
OH
 formula_t * OH =NULL
Variable that corresponds to the OH formula.
Definition at line 63 of file aa.cpp.
Referenced by free_peptide_link(), get_util_formula(), and init_peptid_link().
X
char X ='G'
Variable that corresponds to the value of the amino acid X read in a fasta file.
Definition at line 110 of file aa.cpp.
Referenced by get_amino_acid_table(), get_X(), and set_X().
Z
char Z ='E'
Variable that corresponds to the value of the amino acid Z read in a fasta file.
Definition at line 115 of file aa.cpp.
Referenced by get_amino_acid_table(), get_Z(), and set_Z().