ascq_me_display.h File Reference
Definition of the methods to use and display ASCQ_ME results.
#include <sstream>
#include `ascq_me_configuration.h`
Functions
void init_ascq_me_display ()
Procedure which inits all the useful structure for ASCQ_ME display.
void add_protein (char *description, char * sequence, complex_t *spectrum, double score)
Procedure which adds and manages a new saved protein.
void printf_ascq_me_results ()
Procedure which prints on the stdout the ASCQ_ME results.
void fprintf_ascq_me_results (FILE *file)
Procedure which prints in a file the ASCQ_ME results.
void ascq_me_cleaning ()
Procedure which frees all the memory allocated for ascq_me (excepted the structures allocated in ascq_me.cpp).
void free_ascq_me_display ()
Procedure which frees all the structures useful for the ASCQ_ME display.
void fprintf_ascq_me_results_table_form (FILE *file)
Procedure which prints in a file the ASCQ_ME results in order to use them in spreadsheet programs.
void save_partial_peptide_scoring (double *peptide_scoring, int nb_peptides)
Procedure which allows to save the partial peptide scoring of the current protein.
int compare_peptide_scores (const void *first, const void *second)
Procedure which compares two partial_score ==> useful for qsort.
int compare_peptide_score_from_indices (const void *first, const void *second)
Procedure which compares two partial scores from the score indexes in the current peptide scoring array ==> useful for qsort.
void sort_and_init_with_peptide_scoring ()
Procedure which allows to sort the peptides_scoring in a decreasing order and initialises the array of peptides sequences.
void fprintf_ascq_me_peptide_scoring (FILE *file)
Procedure which prints in a file the ASCQ_ME scoring for the peptides of each result protein in order to use them in a spreadsheet program.
void fprintf_ascq_me_results_xml (FILE *file)
Procedure which prints in a file the ASCQ_ME results in a xml format.
Detailed Description
Definition of the methods to use and display ASCQ_ME results.
Author
Jean-Charles BOISSON (2006-2008).
Warning
Copyright USTL
 This software is governed by the CeCILL-C license under French law and abiding by the rules of distribution of free software.
Function Documentation
add_protein()
void add_protein (char * description, char * sequence, complex_t * spectrum, double score)
Procedure which adds and manages a new saved protein.
Parameters
description The protein description.
sequence The protein sequence.
spectrum The protein simulated spectrum.
score The protein score.
Definition at line 206 of file ascq_me_display.cpp.
References copy_formula(), copy_spectrum(), current_peptide_formulae, current_peptide_scores, current_peptides, error(), free_n_formula(), get_nb_displayed_proteins(), link_between_score_and_others, MEMORY_ALLOCATION_ERROR, nb_current_peptides, nb_saved_proteins, peptide_formulae, peptide_number, peptide_scores, peptides, protein_descriptions, protein_scores, protein_sequences, protein_spectra, sequence, sort_and_init_with_peptide_scoring(), and USAGE_ERROR.
Referenced by main().
ascq_me_cleaning()
void ascq_me_cleaning ()
Procedure which frees all the memory allocated for ascq_me (excepted the structures allocated in ascq_me.cpp).
Definition at line 481 of file ascq_me_display.cpp.
References current_peptide_scores, free_n_formula(), link_between_score_and_others, link_between_score_and_peptides, nb_current_peptides, nb_saved_proteins, peptide_formulae, peptide_number, peptide_scores, peptides, protein_descriptions, protein_scores, protein_sequences, and protein_spectra.
Referenced by main().
compare_peptide_score_from_indices()
int compare_peptide_score_from_indices (const void * first, const void * second)
Procedure which compares two partial scores from the score indexes in the current peptide scoring array ==> useful for qsort.
Parameters
first a void pointer that is in reality an index to a peptide score.
second a void pointer that is also an index to a peptide score.
Returns
1, 0 or -1 <=> the first is inferior,equal or superior to the second.
Warning
It's for a decreasing order.
Definition at line 649 of file ascq_me_display.cpp.
References current_peptide_scores, error(), and USAGE_ERROR.
Referenced by sort_and_init_with_peptide_scoring().
compare_peptide_scores()
int compare_peptide_scores (const void * first, const void * second)
Procedure which compares two partial_score ==> useful for qsort.
Parameters
first a void pointer that is in reality a peptide score.
second a void pointer which is also a peptide score.
Returns
1, 0 or -1 <=> the first is inferior,equal or superior to the second.
Warning
It is for a decreasing order.
Definition at line 622 of file ascq_me_display.cpp.
References current_peptide_scores, error(), and USAGE_ERROR.
Referenced by sort_and_init_with_peptide_scoring().
fprintf_ascq_me_peptide_scoring()
void fprintf_ascq_me_peptide_scoring (FILE * file)
Procedure which prints in a file the ASCQ_ME scoring for the peptides of each result protein in order to use them in a spreadsheet program.
Parameters
file The file where the data will be written.
Definition at line 719 of file ascq_me_display.cpp.
References get_weight(), link_between_score_and_others, nb_saved_proteins, peptide_formulae, peptide_number, peptide_scores, and peptides.
Referenced by main().
fprintf_ascq_me_results()
void fprintf_ascq_me_results (FILE * file)
Procedure which prints in a file the ASCQ_ME results.
Parameters
file The considered file.
Definition at line 440 of file ascq_me_display.cpp.
References free_formula(), get_decoy_score(), get_formula_from_sequence(), get_peptide_score_threshold(), get_weight(), is_decoy_mode_activated(), link_between_score_and_others, nb_saved_proteins, peptide_formulae, peptide_number, peptide_scores, peptides, protein_descriptions, protein_scores, protein_sequences, and TRUE.
Referenced by main().
fprintf_ascq_me_results_table_form()
void fprintf_ascq_me_results_table_form (FILE * file)
Procedure which prints in a file the ASCQ_ME results in order to use them in spreadsheet programs.
Parameters
file The file where the results will be written.
Definition at line 517 of file ascq_me_display.cpp.
References compute_correlation(), free_formula(), get_exp_spectrum(), get_formula_from_sequence(), get_maximum_mass(), get_minimum_mass(), get_step(), get_weight(), link_between_score_and_others, nb_saved_proteins, PROGRAM_LIMITATION, protein_descriptions, protein_scores, protein_sequences, and protein_spectra.
Referenced by main().
fprintf_ascq_me_results_xml()
void fprintf_ascq_me_results_xml (FILE * file)
Procedure which prints in a file the ASCQ_ME results in a xml format.
Parameters
file The file.
Definition at line 763 of file ascq_me_display.cpp.
References free_formula(), get_decoy_score(), get_formula_from_sequence(), get_weight(), link_between_score_and_others, nb_saved_proteins, peptide_number, peptide_scores, peptides, protein_descriptions, protein_scores, and protein_sequences.
Referenced by main().
free_ascq_me_display()
void free_ascq_me_display ()
Procedure which frees all the structures useful for the ASCQ_ME display.
init_ascq_me_display()
void init_ascq_me_display ()
Procedure which inits all the useful structure for ASCQ_ME display.
Definition at line 132 of file ascq_me_display.cpp.
References error(), get_nb_displayed_proteins(), link_between_score_and_others, MEMORY_ALLOCATION_ERROR, peptide_formulae, peptide_number, peptide_scores, peptides, protein_descriptions, protein_scores, protein_sequences, and protein_spectra.
Referenced by main().
printf_ascq_me_results()
void printf_ascq_me_results ()
Procedure which prints on the stdout the ASCQ_ME results.
Definition at line 417 of file ascq_me_display.cpp.
References free_formula(), get_decoy_score(), get_formula_from_sequence(), get_weight(), is_decoy_mode_activated(), link_between_score_and_others, nb_saved_proteins, protein_descriptions, protein_scores, protein_sequences, and TRUE.
save_partial_peptide_scoring()
void save_partial_peptide_scoring (double * peptide_scoring, int nb_peptides)
Procedure which allows to save the partial peptide scoring of the current protein.
Parameters
peptide_scoring The current peptide scoring.
nb_peptides The peptide number.
Definition at line 592 of file ascq_me_display.cpp.
References current_peptide_scores, error(), link_between_score_and_peptides, MEMORY_ALLOCATION_ERROR, and nb_current_peptides.
Referenced by main().
sort_and_init_with_peptide_scoring()
void sort_and_init_with_peptide_scoring ()
Procedure which allows to sort the peptides_scoring in a decreasing order and initialises the array of peptides sequences.
qsort is used thanks to the methods compare_peptides_score and compare_peptides_score_from_indices.
Definition at line 676 of file ascq_me_display.cpp.
References compare_peptide_score_from_indices(), compare_peptide_scores(), current_peptide_formulae, current_peptide_scores, current_peptides, error(), get_peptide_formula_from_index(), get_peptide_sequence(), link_between_score_and_peptides, MEMORY_ALLOCATION_ERROR, and nb_current_peptides.
Referenced by add_protein().