ascq_me_configuration.cpp File Reference
Implementation of the methods defined in ascq_me_configuration.h.
#include `ascq_me_configuration.h`
Functions
void load_int_keyword (FILE *file, char *buffer)
Procedure which reads the value of a parameter that requires an int value.
void load_unsigned_int_keyword (FILE *file, char *buffer)
Procedure which reads the value of a parameter that requires an unsigned int value.
void load_boolean_keyword (FILE *file, char *buffer)
Procedure which reads the value of a parameter that requires a boolean value (in reality it is a char*, not really a boolean).
void load_string_keyword (FILE *file, const char *buffer)
Procedure which reads the value of a parameter that requires a string value (it is a char* value).
void load_float_keyword (FILE *file, char *buffer)
Procedure which reads the value of a parameter that requires a float value (or a double value).
char * get_configuration_file_name ()
Function which returns the name of the configuration file used.
void load_configuration (char *configuration_file)
Procedure which allows to load the wanted configuration <=> set all the parameters of the application.
void ascq_me_configuration_cleaning ()
Procedure which frees all the memory allocated for ascq_me configuration.
int is_fasta_chosen ()
Function which indicates if the chosen file type is fasta or spectra.
void print_configuration ()
Procedure which allows to print the current configuration on the stdout.
void fprint_configuration (FILE *file)
Procedure which allows to print the current configuration in a file.
void fprint_configuration_xml (FILE *file)
Procedure which allows to print in a xml format the current configuration in a file.
void activate_decoy_mode ()
Procedure which allows to activate the decoy mode.
int is_decoy_mode_activated ()
Function which allows to know if the decoy mode has been activated or not.
void set_decoy_score (double score)
Procedure which allows to set the decoy_score.
double get_decoy_score ()
Function which allows to get the decoy score.
int get_nb_displayed_proteins ()
Function which returns the number of displayed proteins.
const char * get_base_name ()
Function which allows to get the base name of the result file of ASCQ_ME.
Variables
char * base_name =NULL
Base name for the ASCQ_ME result files.
char * configuration_file_name =NULL
Name of the configuration file used.
int fasta_format = TRUE
Variable that indicates if the chosen format is FASTA (TRUE) or spectrum (FALSE).
int decoy_mode_activation = FALSE
Variable that indicates if the decoy mode is activated or not.
double decoy_score =0.0
Variable that contains the mean of the decoy score of the analyzed proteins.
int nb_displayed_proteins =10
Number of displayed proteins.
Detailed Description
Implementation of the methods defined in ascq_me_configuration.h.
Author
Jean-Charles BOISSON (2005-2008).
Warning
Copyright USTL
 This software is governed by the CeCILL-C license under French law and abiding by the rules of distribution of free software.
Function Documentation
activate_decoy_mode()
void activate_decoy_mode ()
Procedure which allows to activate the decoy mode.
Definition at line 1008 of file ascq_me_configuration.cpp.
References decoy_mode_activation, and TRUE.
Referenced by load_boolean_keyword().
ascq_me_configuration_cleaning()
void ascq_me_configuration_cleaning ()
Procedure which frees all the memory allocated for ascq_me configuration.
Definition at line 771 of file ascq_me_configuration.cpp.
References base_name, configuration_file_name, fasta_format, fastafclose(), free_activated_modification(), free_all_modifications(), free_isodistrib(), free_tables(), free_util_digestion(), and TRUE.
Referenced by main().
fprint_configuration()
void fprint_configuration (FILE * file)
Procedure which allows to print the current configuration in a file.
Parameters
file The file where the current will be put.
Definition at line 871 of file ascq_me_configuration.cpp.
References configuration_file_name, formula_tochar(), fprint_modification_configuration(), get_activation_full_digest(), get_atom_quantity(), get_exp_protein_mass(), get_experimental_filename(), get_fasta_filename(), get_gaussian_value(), get_maximum_mass(), get_maximum_peptide_length(), get_minimum_mass(), get_minimum_matched_peptide_number(), get_minimum_peptide_number(), get_nb_displayed_proteins(), get_nb_missed_cleavages(), get_number_of_activated_modifications(), get_peptide_charge_formula(), get_peptide_maximum_mass(), get_peptide_precision(), get_scoring_sensitivity(), get_simulated_spectra_filename(), get_specie(), get_spectrum_maximum_mass(), get_spectrum_precision(), get_threshold(), get_used_enzyme(), is_decoy_mode_activated(), is_exp_protein_mass_activated(), is_fasta_chosen(), PROGRAM_NAME, PROGRAM_VERSION, and TRUE.
Referenced by main().
fprint_configuration_xml()
void fprint_configuration_xml (FILE * file)
Procedure which allows to print in a xml format the current configuration in a file.
Parameters
file The file where the current configuration in a xml format will be put.
Definition at line 946 of file ascq_me_configuration.cpp.
References configuration_file_name, formula_tochar(), fprint_xml_modification_configuration(), get_activation_full_digest(), get_atom_quantity(), get_experimental_filename(), get_fasta_filename(), get_gaussian_value(), get_maximum_mass(), get_maximum_peptide_length(), get_minimum_mass(), get_minimum_matched_peptide_number(), get_minimum_peptide_number(), get_nb_displayed_proteins(), get_nb_missed_cleavages(), get_number_of_activated_modifications(), get_peptide_charge_formula(), get_peptide_maximum_mass(), get_peptide_precision(), get_scoring_sensitivity(), get_simulated_spectra_filename(), get_specie(), get_spectrum_maximum_mass(), get_spectrum_precision(), get_threshold(), get_used_enzyme(), is_decoy_mode_activated(), is_fasta_chosen(), PROGRAM_VERSION, and TRUE.
Referenced by main().
get_base_name()
char * get_base_name ()
Function which allows to get the base name of the result file of ASCQ_ME.
Returns
The base name.
Warning
This function directly returns a pointer (not a copy), do not modified it
Definition at line 1038 of file ascq_me_configuration.cpp.
References base_name.
Referenced by main().
get_configuration_file_name()
char * get_configuration_file_name ()
Function which returns the name of the configuration file used.
Returns
The configuration file name.
Definition at line 118 of file ascq_me_configuration.cpp.
References configuration_file_name, error(), and USAGE_ERROR.
get_decoy_score()
double get_decoy_score ()
Function which allows to get the decoy score.
Returns
The decoy score.
Definition at line 1026 of file ascq_me_configuration.cpp.
References decoy_score.
Referenced by fprintf_ascq_me_results(), fprintf_ascq_me_results_xml(), and printf_ascq_me_results().
get_nb_displayed_proteins()
int get_nb_displayed_proteins ()
Function which returns the number of displayed proteins.
Returns
The number.
Definition at line 1032 of file ascq_me_configuration.cpp.
References nb_displayed_proteins.
Referenced by add_protein(), fprint_configuration(), fprint_configuration_xml(), init_ascq_me_display(), and print_configuration().
is_decoy_mode_activated()
int is_decoy_mode_activated ()
Function which allows to know if the decoy mode has been activated or not.
Returns
TRUE or FALSE (according to util.h).
Definition at line 1014 of file ascq_me_configuration.cpp.
References decoy_mode_activation.
Referenced by fprint_configuration(), fprint_configuration_xml(), fprintf_ascq_me_results(), main(), print_configuration(), and printf_ascq_me_results().
is_fasta_chosen()
int is_fasta_chosen ()
Function which indicates if the chosen file type is fasta or spectra.
Returns
TRUE or FALSE (see util.h).
Definition at line 798 of file ascq_me_configuration.cpp.
References fasta_format.
Referenced by fprint_configuration(), fprint_configuration_xml(), main(), and print_configuration().
load_boolean_keyword()
void load_boolean_keyword (FILE * file, char * buffer)
Procedure which reads the value of a parameter that requires a boolean value (in reality it is a char*, not really a boolean).
Parameters
file The file to read.
buffer The name of the keyword
Definition at line 438 of file ascq_me_configuration.cpp.
References activate_decoy_mode(), activate_full_digestion(), error(), EXECUTION_ERROR, FALSE, fasta_format, read_line(), TRUE, and USAGE_ERROR.
Referenced by load_configuration().
load_configuration()
void load_configuration (char * configuration_file)
Procedure which allows to load the wanted configuration <=> set all the parameters of the application.
Parameters
configuration_file The configuration file.
Definition at line 130 of file ascq_me_configuration.cpp.
References configuration_file_name, error(), FALSE, get_distribution_activation(), init_util_digestion(), IO_ERROR, jump_commentaries(), load_boolean_keyword(), load_float_keyword(), load_int_keyword(), load_modifications(), load_string_keyword(), load_unsigned_int_keyword(), MEMORY_ALLOCATION_ERROR, MODIFICATION_FILENAME, tables_initialisation(), and USAGE_ERROR.
Referenced by main().
load_float_keyword()
void load_float_keyword (FILE * file, char * buffer)
Procedure which reads the value of a parameter that requires a float value (or a double value).
Parameters
file The file to read.
buffer The name of the keyword
Definition at line 655 of file ascq_me_configuration.cpp.
References error(), EXECUTION_ERROR, get_distribution_activation(), read_line(), set_exp_protein_mass(), set_gaussian_value(), set_maximum_mass(), set_minimum_mass(), set_scoring_sensitivity(), set_threshold(), TRUE, USAGE_ERROR, and WARNING.
Referenced by load_configuration().
load_int_keyword()
void load_int_keyword (FILE * file, char * buffer)
Procedure which reads the value of a parameter that requires an int value.
Parameters
file The file to read.
buffer The name of the keyword
Definition at line 245 of file ascq_me_configuration.cpp.
References error(), EXECUTION_ERROR, get_distribution_activation(), nb_displayed_proteins, read_line(), set_C_atom_quantity(), set_maximum_peptide_length(), set_nb_missed_cleavages(), set_peptide_maximum_mass(), set_peptide_precision(), set_precision(), set_spectrum_maximum_mass(), set_used_enzyme(), TRUE, USAGE_ERROR, and WARNING.
Referenced by load_configuration().
load_string_keyword()
void load_string_keyword (FILE * file, const char * buffer)
Procedure which reads the value of a parameter that requires a string value (it is a char* value).
Parameters
file The file to read.
buffer The name of the keyword
Definition at line 516 of file ascq_me_configuration.cpp.
References base_name, error(), EXECUTION_ERROR, FALSE, fasta_format, fastafopen(), init_distrib(), load_modification_configuration(), MEMORY_ALLOCATION_ERROR, read_line(), read_simulated_spectrum(), read_spectrum(), set_B(), set_peptide_charge(), set_specie(), set_X(), set_Z(), and USAGE_ERROR.
Referenced by load_configuration().
load_unsigned_int_keyword()
void load_unsigned_int_keyword (FILE * file, char * buffer)
Procedure which reads the value of a parameter that requires an unsigned int value.
Parameters
file The file to read.
buffer The name of the keyword
Definition at line 382 of file ascq_me_configuration.cpp.
References error(), EXECUTION_ERROR, read_line(), set_minimum_matched_peptide_number(), set_minimum_peptide_number(), USAGE_ERROR, and WARNING.
Referenced by load_configuration().
print_configuration()
void print_configuration ()
Procedure which allows to print the current configuration on the stdout.
Definition at line 804 of file ascq_me_configuration.cpp.
References configuration_file_name, formula_tochar(), get_activation_full_digest(), get_atom_quantity(), get_exp_protein_mass(), get_experimental_filename(), get_fasta_filename(), get_gaussian_value(), get_maximum_mass(), get_maximum_peptide_length(), get_minimum_mass(), get_minimum_matched_peptide_number(), get_minimum_peptide_number(), get_nb_displayed_proteins(), get_nb_missed_cleavages(), get_number_of_activated_modifications(), get_peptide_charge_formula(), get_peptide_maximum_mass(), get_peptide_precision(), get_scoring_sensitivity(), get_simulated_spectra_filename(), get_specie(), get_spectrum_maximum_mass(), get_spectrum_precision(), get_threshold(), get_used_enzyme(), is_decoy_mode_activated(), is_exp_protein_mass_activated(), is_fasta_chosen(), print_modification_configuration(), PROGRAM_NAME, PROGRAM_VERSION, and TRUE.
set_decoy_score()
void set_decoy_score (double score)
Procedure which allows to set the decoy_score.
Parameters
score The decoy score.
Definition at line 1020 of file ascq_me_configuration.cpp.
References decoy_score.
Referenced by main().
Variable Documentation
base_name
char * base_name =NULL
Base name for the ASCQ_ME result files.
Definition at line 55 of file ascq_me_configuration.cpp.
Referenced by ascq_me_configuration_cleaning(), get_base_name(), and load_string_keyword().
configuration_file_name
char * configuration_file_name =NULL
Name of the configuration file used.
Definition at line 60 of file ascq_me_configuration.cpp.
Referenced by ascq_me_configuration_cleaning(), fprint_configuration(), fprint_configuration_xml(), get_configuration_file_name(), load_configuration(), and print_configuration().
decoy_mode_activation
int decoy_mode_activation = FALSE
Variable that indicates if the decoy mode is activated or not.
Definition at line 70 of file ascq_me_configuration.cpp.
Referenced by activate_decoy_mode(), and is_decoy_mode_activated().
decoy_score
double decoy_score =0.0
Variable that contains the mean of the decoy score of the analyzed proteins.
Definition at line 75 of file ascq_me_configuration.cpp.
Referenced by get_decoy_score(), main(), and set_decoy_score().
fasta_format
int fasta_format = TRUE
Variable that indicates if the chosen format is FASTA (TRUE) or spectrum (FALSE).
Definition at line 65 of file ascq_me_configuration.cpp.
Referenced by ascq_me_configuration_cleaning(), is_fasta_chosen(), load_boolean_keyword(), and load_string_keyword().
nb_displayed_proteins
int nb_displayed_proteins =10
Number of displayed proteins.
Definition at line 80 of file ascq_me_configuration.cpp.
Referenced by get_nb_displayed_proteins(), and load_int_keyword().