ascq_me.cpp File Reference
ASCQ_ME main program.
#include `ascq_me_display.h`
Macros
#define ASCQ_ME_TABLE_RESULT `_ascq_me_table_results.txt`
Default format of the table results of ASCQ_ME.
#define ASCQ_ME_RESULT `_ascq_me_results.txt`
Default format of the text results of ASCQ_ME.
#define ASCQ_ME_PEPTIDES_SCORING `_ascq_me_peptides_scoring.txt`
Default format of the peptide scoring of ASCQ_ME.
Functions
void print_ascq_me_usage ()
int main (int argc, char *argv[])
ASCQ_ME main function.
Detailed Description
ASCQ_ME main program.
Author
Jean-Charles BOISSON (2005-2008).
Warning
Copyright USTL
 This software is governed by the CeCILL-C license under French law and abiding by the rules of distribution of free software.
Macro Definition Documentation
ASCQ_ME_PEPTIDES_SCORING
#define ASCQ_ME_PEPTIDES_SCORING `_ascq_me_peptides_scoring.txt`
Default format of the peptide scoring of ASCQ_ME.
Definition at line 65 of file ascq_me.cpp.
ASCQ_ME_RESULT
#define ASCQ_ME_RESULT `_ascq_me_results.txt`
Default format of the text results of ASCQ_ME.
Definition at line 60 of file ascq_me.cpp.
ASCQ_ME_TABLE_RESULT
#define ASCQ_ME_TABLE_RESULT `_ascq_me_table_results.txt`
Default format of the table results of ASCQ_ME.
Definition at line 55 of file ascq_me.cpp.
Function Documentation
main()
int main (int argc, char * argv[])
ASCQ_ME main function.
Parameters
argc The number of parameters of the ASCQ_ME command including the ASCQ_ME command.
argv The parameters.
Returns
The return code of the ASCQ_ME command.
Definition at line 76 of file ascq_me.cpp.
References activate_verbose_mode(), add_chains(), add_protein(), ascq_me_cleaning(), ascq_me_configuration_cleaning(), ASCQ_ME_PEPTIDES_SCORING, ASCQ_ME_RESULT, ASCQ_ME_TABLE_RESULT, decoy_score, error(), FALSE, fprint_configuration(), fprint_configuration_xml(), fprintf_ascq_me_peptide_scoring(), fprintf_ascq_me_results(), fprintf_ascq_me_results_table_form(), fprintf_ascq_me_results_xml(), free_n_formula(), get_base_name(), get_current_peptide_score_save(), get_current_peptide_score_size(), get_formulae_of_peptides(), get_reversed_sequence(), get_spectrum_original_description(), get_spectrum_original_sequence(), get_theo_spectrum(), getDesc(), getSeq(), init_ascq_me_display(), IO_ERROR, is_a_wanted_protein(), is_decoy_mode_activated(), is_fasta_chosen(), is_simulated_wanted_protein(), is_verbose_mode_activated(), load_configuration(), next_simulated_spectrum(), nextEntry(), optimized_isotopic_distribution(), peptides, print_ascq_me_usage(), PROGRAM_NAME, PROGRAM_VERSION, real_digest(), save_partial_peptide_scoring(), sequence, set_decoy_score(), TRUE, and USAGE_ERROR.
print_ascq_me_usage()
void print_ascq_me_usage ()
Definition at line 308 of file ascq_me.cpp.
Referenced by main().