ascq_me_display.cpp File Reference
Implementation of the methods defined in ascq_me_display.h.
#include `ascq_me_display.h`
Macros
#define PROGRAM_LIMITATION 32000
Maximum number of points that the spreadsheet program used to read the ASCQ_ME table result files can be read in one shot.
Functions
void init_ascq_me_display ()
Procedure which inits all the useful structure for ASCQ_ME display.
void add_protein (char *description, char * sequence, complex_t *spectrum, double score)
Procedure which adds and manages a new saved protein.
void printf_ascq_me_results ()
Procedure which prints on the stdout the ASCQ_ME results.
void fprintf_ascq_me_results (FILE *file)
Procedure which prints in a file the ASCQ_ME results.
void ascq_me_cleaning ()
Procedure which frees all the memory allocated for ascq_me (excepted the structures allocated in ascq_me.cpp).
void fprintf_ascq_me_results_table_form (FILE *file)
Procedure which prints in a file the ASCQ_ME results in order to use them in spreadsheet programs.
void save_partial_peptide_scoring (double *peptide_scoring, int nb_peptides)
Procedure which allows to save the partial peptide scoring of the current protein.
int compare_peptide_scores (const void *first, const void *second)
Procedure which compares two partial_score ==> useful for qsort.
int compare_peptide_score_from_indices (const void *first, const void *second)
Procedure which compares two partial scores from the score indexes in the current peptide scoring array ==> useful for qsort.
void sort_and_init_with_peptide_scoring ()
Procedure which allows to sort the peptides_scoring in a decreasing order and initialises the array of peptides sequences.
void fprintf_ascq_me_peptide_scoring (FILE *file)
Procedure which prints in a file the ASCQ_ME scoring for the peptides of each result protein in order to use them in a spreadsheet program.
void fprintf_ascq_me_results_xml (FILE *file)
Procedure which prints in a file the ASCQ_ME results in a xml format.
Variables
int nb_saved_proteins =0
Number of proteins currently saved.
char ** protein_descriptions =NULL
Descriptions of all the saved proteins.
char ** protein_sequences =NULL
Sequences of all the saved proteins.
 complex_t ** protein_spectra =NULL
Spectra of all the saved proteins.
double * protein_scores =NULL
Scores of all the saved proteins.
double ** peptide_scores =NULL
For each saved proteins, scores of all of its peptides.
char *** peptides =NULL
Sequence of each peptide of each saved protein.
 formula_t ** peptide_formulae =NULL
Formula of each peptide of each saved protein.
int * peptide_number =NULL
Peptide number of each protein.
int * link_between_score_and_others =NULL
Array that allows to work on the indexes for making sorts.
char ** current_peptides =NULL
Sequence of each peptide of the current analysed protein.
 formula_t * current_peptide_formulae =NULL
Formula of each peptide of the current analysed protein.
double * current_peptide_scores =NULL
Score of each peptide of the current analysed protein.
int * link_between_score_and_peptides =NULL
Array that allows to work on the indexes to make sorts for the current analysed protein.
int nb_current_peptides =0
Peptide number of current analysed protein.
Detailed Description
Implementation of the methods defined in ascq_me_display.h.
Author
Jean-Charles BOISSON (2006-2008).
Warning
Copyright USTL
 This software is governed by the CeCILL-C license under French law and abiding by the rules of distribution of free software.
Macro Definition Documentation
PROGRAM_LIMITATION
#define PROGRAM_LIMITATION 32000
Maximum number of points that the spreadsheet program used to read the ASCQ_ME table result files can be read in one shot.
Definition at line 54 of file ascq_me_display.cpp.
Function Documentation
add_protein()
void add_protein (char * description, char * sequence, complex_t * spectrum, double score)
Procedure which adds and manages a new saved protein.
Parameters
description The protein description.
sequence The protein sequence.
spectrum The protein simulated spectrum.
score The protein score.
Definition at line 206 of file ascq_me_display.cpp.
References copy_formula(), copy_spectrum(), current_peptide_formulae, current_peptide_scores, current_peptides, error(), free_n_formula(), get_nb_displayed_proteins(), link_between_score_and_others, MEMORY_ALLOCATION_ERROR, nb_current_peptides, nb_saved_proteins, peptide_formulae, peptide_number, peptide_scores, peptides, protein_descriptions, protein_scores, protein_sequences, protein_spectra, sequence, sort_and_init_with_peptide_scoring(), and USAGE_ERROR.
Referenced by main().
ascq_me_cleaning()
void ascq_me_cleaning ()
Procedure which frees all the memory allocated for ascq_me (excepted the structures allocated in ascq_me.cpp).
Definition at line 481 of file ascq_me_display.cpp.
References current_peptide_scores, free_n_formula(), link_between_score_and_others, link_between_score_and_peptides, nb_current_peptides, nb_saved_proteins, peptide_formulae, peptide_number, peptide_scores, peptides, protein_descriptions, protein_scores, protein_sequences, and protein_spectra.
Referenced by main().
compare_peptide_score_from_indices()
int compare_peptide_score_from_indices (const void * first, const void * second)
Procedure which compares two partial scores from the score indexes in the current peptide scoring array ==> useful for qsort.
Parameters
first a void pointer that is in reality an index to a peptide score.
second a void pointer that is also an index to a peptide score.
Returns
1, 0 or -1 <=> the first is inferior,equal or superior to the second.
Warning
It's for a decreasing order.
Definition at line 649 of file ascq_me_display.cpp.
References current_peptide_scores, error(), and USAGE_ERROR.
Referenced by sort_and_init_with_peptide_scoring().
compare_peptide_scores()
int compare_peptide_scores (const void * first, const void * second)
Procedure which compares two partial_score ==> useful for qsort.
Parameters
first a void pointer that is in reality a peptide score.
second a void pointer which is also a peptide score.
Returns
1, 0 or -1 <=> the first is inferior,equal or superior to the second.
Warning
It is for a decreasing order.
Definition at line 622 of file ascq_me_display.cpp.
References current_peptide_scores, error(), and USAGE_ERROR.
Referenced by sort_and_init_with_peptide_scoring().
fprintf_ascq_me_peptide_scoring()
void fprintf_ascq_me_peptide_scoring (FILE * file)
Procedure which prints in a file the ASCQ_ME scoring for the peptides of each result protein in order to use them in a spreadsheet program.
Parameters
file The file where the data will be written.
Definition at line 719 of file ascq_me_display.cpp.
References get_weight(), link_between_score_and_others, nb_saved_proteins, peptide_formulae, peptide_number, peptide_scores, and peptides.
Referenced by main().
fprintf_ascq_me_results()
void fprintf_ascq_me_results (FILE * file)
Procedure which prints in a file the ASCQ_ME results.
Parameters
file The considered file.
Definition at line 440 of file ascq_me_display.cpp.
References free_formula(), get_decoy_score(), get_formula_from_sequence(), get_peptide_score_threshold(), get_weight(), is_decoy_mode_activated(), link_between_score_and_others, nb_saved_proteins, peptide_formulae, peptide_number, peptide_scores, peptides, protein_descriptions, protein_scores, protein_sequences, and TRUE.
Referenced by main().
fprintf_ascq_me_results_table_form()
void fprintf_ascq_me_results_table_form (FILE * file)
Procedure which prints in a file the ASCQ_ME results in order to use them in spreadsheet programs.
Parameters
file The file where the results will be written.
Definition at line 517 of file ascq_me_display.cpp.
References compute_correlation(), free_formula(), get_exp_spectrum(), get_formula_from_sequence(), get_maximum_mass(), get_minimum_mass(), get_step(), get_weight(), link_between_score_and_others, nb_saved_proteins, PROGRAM_LIMITATION, protein_descriptions, protein_scores, protein_sequences, and protein_spectra.
Referenced by main().
fprintf_ascq_me_results_xml()
void fprintf_ascq_me_results_xml (FILE * file)
Procedure which prints in a file the ASCQ_ME results in a xml format.
Parameters
file The file.
Definition at line 763 of file ascq_me_display.cpp.
References free_formula(), get_decoy_score(), get_formula_from_sequence(), get_weight(), link_between_score_and_others, nb_saved_proteins, peptide_number, peptide_scores, peptides, protein_descriptions, protein_scores, and protein_sequences.
Referenced by main().
init_ascq_me_display()
void init_ascq_me_display ()
Procedure which inits all the useful structure for ASCQ_ME display.
Definition at line 132 of file ascq_me_display.cpp.
References error(), get_nb_displayed_proteins(), link_between_score_and_others, MEMORY_ALLOCATION_ERROR, peptide_formulae, peptide_number, peptide_scores, peptides, protein_descriptions, protein_scores, protein_sequences, and protein_spectra.
Referenced by main().
printf_ascq_me_results()
void printf_ascq_me_results ()
Procedure which prints on the stdout the ASCQ_ME results.
Definition at line 417 of file ascq_me_display.cpp.
References free_formula(), get_decoy_score(), get_formula_from_sequence(), get_weight(), is_decoy_mode_activated(), link_between_score_and_others, nb_saved_proteins, protein_descriptions, protein_scores, protein_sequences, and TRUE.
save_partial_peptide_scoring()
void save_partial_peptide_scoring (double * peptide_scoring, int nb_peptides)
Procedure which allows to save the partial peptide scoring of the current protein.
Parameters
peptide_scoring The current peptide scoring.
nb_peptides The peptide number.
Definition at line 592 of file ascq_me_display.cpp.
References current_peptide_scores, error(), link_between_score_and_peptides, MEMORY_ALLOCATION_ERROR, and nb_current_peptides.
Referenced by main().
sort_and_init_with_peptide_scoring()
void sort_and_init_with_peptide_scoring ()
Procedure which allows to sort the peptides_scoring in a decreasing order and initialises the array of peptides sequences.
qsort is used thanks to the methods compare_peptides_score and compare_peptides_score_from_indices.
Definition at line 676 of file ascq_me_display.cpp.
References compare_peptide_score_from_indices(), compare_peptide_scores(), current_peptide_formulae, current_peptide_scores, current_peptides, error(), get_peptide_formula_from_index(), get_peptide_sequence(), link_between_score_and_peptides, MEMORY_ALLOCATION_ERROR, and nb_current_peptides.
Referenced by add_protein().
Variable Documentation
current_peptide_formulae
 formula_t * current_peptide_formulae =NULL
Formula of each peptide of the current analysed protein.
Definition at line 114 of file ascq_me_display.cpp.
Referenced by add_protein(), and sort_and_init_with_peptide_scoring().
current_peptide_scores
double * current_peptide_scores =NULL
Score of each peptide of the current analysed protein.
Definition at line 119 of file ascq_me_display.cpp.
Referenced by add_protein(), ascq_me_cleaning(), compare_peptide_score_from_indices(), compare_peptide_scores(), save_partial_peptide_scoring(), and sort_and_init_with_peptide_scoring().
current_peptides
char ** current_peptides =NULL
Sequence of each peptide of the current analysed protein.
Definition at line 109 of file ascq_me_display.cpp.
Referenced by add_protein(), and sort_and_init_with_peptide_scoring().
link_between_score_and_others
int * link_between_score_and_others =NULL
Array that allows to work on the indexes for making sorts.
Definition at line 104 of file ascq_me_display.cpp.
Referenced by add_protein(), ascq_me_cleaning(), fprintf_ascq_me_peptide_scoring(), fprintf_ascq_me_results(), fprintf_ascq_me_results_table_form(), fprintf_ascq_me_results_xml(), init_ascq_me_display(), and printf_ascq_me_results().
link_between_score_and_peptides
int * link_between_score_and_peptides =NULL
Array that allows to work on the indexes to make sorts for the current analysed protein.
Definition at line 124 of file ascq_me_display.cpp.
Referenced by ascq_me_cleaning(), save_partial_peptide_scoring(), and sort_and_init_with_peptide_scoring().
nb_current_peptides
int nb_current_peptides =0
Peptide number of current analysed protein.
Definition at line 129 of file ascq_me_display.cpp.
Referenced by add_protein(), ascq_me_cleaning(), save_partial_peptide_scoring(), and sort_and_init_with_peptide_scoring().
nb_saved_proteins
int nb_saved_proteins =0
Number of proteins currently saved.
Definition at line 59 of file ascq_me_display.cpp.
Referenced by add_protein(), ascq_me_cleaning(), fprintf_ascq_me_peptide_scoring(), fprintf_ascq_me_results(), fprintf_ascq_me_results_table_form(), fprintf_ascq_me_results_xml(), and printf_ascq_me_results().
peptide_formulae
 formula_t ** peptide_formulae =NULL
Formula of each peptide of each saved protein.
Definition at line 94 of file ascq_me_display.cpp.
Referenced by add_protein(), ascq_me_cleaning(), fprintf_ascq_me_peptide_scoring(), fprintf_ascq_me_results(), and init_ascq_me_display().
peptide_number
int * peptide_number =NULL
Peptide number of each protein.
Definition at line 99 of file ascq_me_display.cpp.
Referenced by add_protein(), ascq_me_cleaning(), fprintf_ascq_me_peptide_scoring(), fprintf_ascq_me_results(), fprintf_ascq_me_results_xml(), and init_ascq_me_display().
peptide_scores
double ** peptide_scores =NULL
For each saved proteins, scores of all of its peptides.
Definition at line 84 of file ascq_me_display.cpp.
Referenced by add_protein(), ascq_me_cleaning(), fprintf_ascq_me_peptide_scoring(), fprintf_ascq_me_results(), fprintf_ascq_me_results_xml(), and init_ascq_me_display().
peptides
char *** peptides =NULL
Sequence of each peptide of each saved protein.
Definition at line 89 of file ascq_me_display.cpp.
Referenced by add_protein(), ascq_me_cleaning(), fprint_result_of_digestion(), fprint_result_of_digestion_table_format(), fprintf_ascq_me_peptide_scoring(), fprintf_ascq_me_results(), fprintf_ascq_me_results_xml(), get_formulae_of_peptides(), init_ascq_me_display(), main(), optimized_isotopic_distribution(), and print_result_of_digestion().
protein_descriptions
char ** protein_descriptions =NULL
Descriptions of all the saved proteins.
Definition at line 64 of file ascq_me_display.cpp.
Referenced by add_protein(), ascq_me_cleaning(), fprintf_ascq_me_results(), fprintf_ascq_me_results_table_form(), fprintf_ascq_me_results_xml(), init_ascq_me_display(), and printf_ascq_me_results().
protein_scores
double * protein_scores =NULL
Scores of all the saved proteins.
Definition at line 79 of file ascq_me_display.cpp.
Referenced by add_protein(), ascq_me_cleaning(), fprintf_ascq_me_results(), fprintf_ascq_me_results_table_form(), fprintf_ascq_me_results_xml(), init_ascq_me_display(), and printf_ascq_me_results().
protein_sequences
char ** protein_sequences =NULL
Sequences of all the saved proteins.
Definition at line 69 of file ascq_me_display.cpp.
Referenced by add_protein(), ascq_me_cleaning(), fprintf_ascq_me_results(), fprintf_ascq_me_results_table_form(), fprintf_ascq_me_results_xml(), init_ascq_me_display(), and printf_ascq_me_results().
protein_spectra
 complex_t ** protein_spectra =NULL
Spectra of all the saved proteins.
Definition at line 74 of file ascq_me_display.cpp.
Referenced by add_protein(), ascq_me_cleaning(), fprintf_ascq_me_results_table_form(), and init_ascq_me_display().