cleavage.h File Reference
Description of methods allowing to know where enzymes can cut proteins.
#include `util.h`
Data Structures
struct cleavePoint
Structure representing a cleavage point.
struct cleavePointList
Structure representing a list of cleavage point <=> cleavage rules.
struct enzyme
Structure that represents an enzyme.
struct enzyme_list
Structure that represents an enzyme list.
Macros
#define N_SIDE 0
Correspond to the N-terminal side.
#define C_SIDE 1
Correspond to the C-terminal side.
Typedefs
typedef struct cleavePoint cp_t
typedef struct cleavePointList cpl_t
typedef struct enzyme enz_t
typedef struct enzyme_list enztable_t
Functions
 cpl_t * stringToCpl (char *s)
Function which translates according to a grammar a character a sequence into a complete cleavage rule.
int cpl_isCleavage (cpl_t *cpl, char c)
Function which indicates if letter can be a cleveage point according to the cleavage rules.
int cpl_isCleavage2 (cpl_t *cpl, char cprev, char c, char cnext)
Function which indicates if we are in a good cleavage situation according to the cleavage rules.
void cpl_fprint (FILE *f, cpl_t *cpl)
Procedure which prints the rules in a file in an understanding style.
 enztable_t * enzym_load (const char *fileToLoad)
Procedure which initialized the enztable_t structure from a file.
int get_enzyme_number (char *enztofind, enztable_t *enzt)
Function which returns the place of an enzym in the enzyme list.
void print_enzyme_table (enztable_t *enzt)
Procedure which prints the enzyme table on the screen.
void free_cpt (cp_t *cpt)
Procedure which frees the content of a cpt structure.
void free_cplt (cpl_t *cplt)
Procedure which frees the content of a cplt structure.
void free_enzt (enz_t *enzt)
Procedure which frees the content of a enzt structure.
void free_enzym_table (enztable_t *enzyme_table)
Procedure which frees an enzyme table.
Detailed Description
Description of methods allowing to know where enzymes can cut proteins.
Author
Pierre LAURENCE and David BOENS (2003).
 Modified and updated by Jean-Charles BOISSON (2005-2008).
Warning
Copyright USTL
 This software is governed by the CeCILL-C license under French law and abiding by the rules of distribution of free software.
Macro Definition Documentation
C_SIDE
#define C_SIDE 1
Correspond to the C-terminal side.
Definition at line 65 of file cleavage.h.
N_SIDE
#define N_SIDE 0
Correspond to the N-terminal side.
Definition at line 60 of file cleavage.h.
Typedef Documentation
cp_t
typedef struct cleavePoint cp_t
cpl_t
typedef struct cleavePointList cpl_t
enz_t
typedef struct enzyme enz_t
enztable_t
typedef struct enzyme_list enztable_t
Function Documentation
cpl_fprint()
void cpl_fprint (FILE * f, cpl_t * cpl)
Procedure which prints the rules in a file in an understanding style.
Parameters
f The file in which we want to print the rules.
cpl The rules.
Definition at line 267 of file cleavage.cpp.
References cleavePointList::cp, cp_fprint(), and cleavePointList::size.
cpl_isCleavage()
int cpl_isCleavage (cpl_t * cpl, char c)
Function which indicates if letter can be a cleveage point according to the cleavage rules.
Parameters
cpl The rules.
c The considered letter.
Returns
TRUE or FALSE (see util.h).
Definition at line 207 of file cleavage.cpp.
References cleavePointList::cp, FALSE, cleavePoint::letter, cleavePointList::size, and TRUE.
cpl_isCleavage2()
int cpl_isCleavage2 (cpl_t * cpl, char cprev, char c, char cnext)
Function which indicates if we are in a good cleavage situation according to the cleavage rules.
Parameters
cpl The rules.
cprev The letter(s) before the current one.
c The current letter.
cnext The letter(s) after the current one.
Returns
TRUE or FALSE (see util.h).
Definition at line 217 of file cleavage.cpp.
References cleavePointList::cp, cleavePoint::exceptafter, cleavePoint::exceptbefore, FALSE, cleavePoint::letter, cleavePoint::nbexceptafter, cleavePoint::nbexceptbefore, cleavePointList::size, and TRUE.
Referenced by digest().
enzym_load()
 enztable_t* enzym_load (const char * fileToLoad)
Procedure which initialized the enztable_t structure from a file.
Parameters
fileToLoad The file used to make the initialisation.
Returns
The enzyme table.
Definition at line 276 of file cleavage.cpp.
References C_SIDE, enzyme::cpl, enzyme_list::enz, EOL, error(), IO_ERROR, N_SIDE, enzyme::name, SEPARATOR, enzyme::side, enzyme_list::size, stringToCpl(), and USAGE_ERROR.
Referenced by init_util_digestion().
free_cplt()
void free_cplt (cpl_t * cplt)
Procedure which frees the content of a cplt structure.
Parameters
cplt The cplt structure we want to free.
Definition at line 436 of file cleavage.cpp.
References cleavePointList::cp, error(), free_cpt(), FREE_MEMORY_ERROR, and cleavePointList::size.
Referenced by free_enzt().
free_cpt()
void free_cpt (cp_t * cpt)
Procedure which frees the content of a cpt structure.
Parameters
cpt The cpt structure we want to free.
Definition at line 409 of file cleavage.cpp.
References error(), cleavePoint::exceptafter, cleavePoint::exceptbefore, FREE_MEMORY_ERROR, cleavePoint::nbexceptafter, and cleavePoint::nbexceptbefore.
Referenced by free_cplt().
free_enzt()
void free_enzt (enz_t * enzt)
Procedure which frees the content of a enzt structure.
Parameters
enzt The enzyme table we want to free.
Definition at line 457 of file cleavage.cpp.
References enzyme::cpl, error(), free_cplt(), FREE_MEMORY_ERROR, and enzyme::name.
Referenced by free_enzym_table().
free_enzym_table()
void free_enzym_table (enztable_t * enzyme_table)
Procedure which frees an enzyme table.
Parameters
enzyme_table The enzym table to free.
Definition at line 480 of file cleavage.cpp.
References enzyme_list::enz, error(), free_enzt(), FREE_MEMORY_ERROR, and enzyme_list::size.
Referenced by free_util_digestion().
get_enzyme_number()
int get_enzyme_number (char * enztofind, enztable_t * enzt)
Function which returns the place of an enzym in the enzyme list.
Parameters
enztofind The enzym we want to find.
enzt The enzyme table.
Returns
The place of the enzyme in the enzyme list.
Definition at line 377 of file cleavage.cpp.
References enzyme_list::enz, enzyme::name, and enzyme_list::size.
print_enzyme_table()
void print_enzyme_table (enztable_t * enzt)
Procedure which prints the enzyme table on the screen.
Parameters
enzt The enzyme table.
Definition at line 399 of file cleavage.cpp.
References enzyme_list::enz, enzyme::name, and enzyme_list::size.
stringToCpl()
 cpl_t* stringToCpl (char * s)
Function which translates according to a grammar a character a sequence into a complete cleavage rule.
Parameters
s a correct character chain according to the grammar.
Returns
The complete cleavage rule.
Definition at line 61 of file cleavage.cpp.
References cleavePointList::cp, error(), cleavePoint::exceptafter, cleavePoint::exceptbefore, FALSE, cleavePoint::letter, MEMORY_ALLOCATION_ERROR, cleavePoint::nbexceptafter, cleavePoint::nbexceptbefore, cleavePointList::size, and TRUE.
Referenced by enzym_load().