complex.h File Reference
Definition of the complex structure and basic methods to use complex numbers.
#include <math.h>
Data Structures
struct complex
Basic complex structure with a real part and an imaginary part.
Typedefs
typedef struct complex complex_t
Functions
 complex_t complex_multiplication (complex_t z1, complex_t z2)
Function which makes the multiplication of 2 complex numbers.
 complex_t complex_addition (complex_t z1, complex_t z2)
Function which makes the addition of 2 complex numbers.
 complex_t complex_subtraction (complex_t z1, complex_t z2)
Function which makes the subtraction of 2 complex numbers.
 complex_t complex_power (complex_t z, int n)
Function which calculates the power of a complex number.
 complex_t complex_conjugate (complex_t z)
Function which produces the conjugate complex number of one complex number.
Detailed Description
Definition of the complex structure and basic methods to use complex numbers.
Author
Jean-Charles BOISSON (2006-2008).
Warning
Copyright USTL
 This software is governed by the CeCILL-C license under French law and abiding by the rules of distribution of free software.
Typedef Documentation
complex_t
typedef struct complex complex_t
Function Documentation
complex_addition()
 complex_t complex_addition (complex_t z1, complex_t z2)
Function which makes the addition of 2 complex numbers.
Parameters
z1 The first complex number.
z2 The second complex number.
Returns
The addition of the 2 complex numbers.
Definition at line 63 of file complex.cpp.
References complex::Im, and complex::Re.
complex_conjugate()
 complex_t complex_conjugate (complex_t z)
Function which produces the conjugate complex number of one complex number.
Parameters
z The complex number.
Returns
The conjugate complex number.
Definition at line 104 of file complex.cpp.
References complex::Im, and complex::Re.
complex_multiplication()
 complex_t complex_multiplication (complex_t z1, complex_t z2)
Function which makes the multiplication of 2 complex numbers.
Parameters
z1 The first complex number.
z2 The second complex number.
Returns
The multiplication of the 2 complex numbers.
Definition at line 52 of file complex.cpp.
References complex::Im, and complex::Re.
Referenced by complex_power(), init_distrib(), and optimized_isotopic_distribution().
complex_power()
 complex_t complex_power (complex_t z, int n)
Function which calculates the power of a complex number.
Parameters
z The complex number.
n The power level.
Returns
The complex number at the good power level.
Definition at line 85 of file complex.cpp.
References complex_multiplication(), complex::Im, and complex::Re.
complex_subtraction()
 complex_t complex_subtraction (complex_t z1, complex_t z2)
Function which makes the subtraction of 2 complex numbers.
Parameters
z1 The first complex number.
z2 The second complex number.
Returns
The subtraction of the 2 complex numbers.
Definition at line 74 of file complex.cpp.
References complex::Im, and complex::Re.