digest.cpp File Reference
Implementation of the methods defined in digest.h.
#include `digest.h`
Functions
void digest ()
Procedure which realises the digestion with 0 miss-cleavage.
 peptide_t * get_result_of_digestion (int *nb_peptides)
Function which returns the peptides resulting of the digestion.
 peptide_t * get_copie_of_digestion_result (int *nb_peptides)
Function which allows to gain a copie of the result of the digestion.
void print_result_of_digestion (peptide_t * peptides, int nb_peptides)
Procedure which prints on stdout the result of the digestion.
void fprint_result_of_digestion (FILE *file, peptide_t * peptides, int nb_peptides)
Procedure which prints in a file the result of the digestion.
void fprint_result_of_digestion_table_format (FILE *file, peptide_t * peptides, int nb_peptides)
Procedure which prints in a file a result of the digestion in a format useful for speadsheet programs.
 peptide_t * copy_peptide (peptide_t *original)
Function which makes a copy of a peptide.
 peptide_t * fusion_peptide (peptide_t *first, peptide_t *second)
Function which makes the fusion of two CONTIGUOUS (!!!) peptides.
void new_peptides_with_missed_cleavages (int missed_cleavage, int *nb_new_peptides_total)
Procedure which allows to compute the new peptides gained due to missed cleavages.
void real_digest (char *seq)
Procedure which realises the real digestion according the number of missed cleavages.
void activate_full_digestion (int activation)
Procedure which allows to activate or desactivate the full-digest process i.e. when it is activated, the digestion do not use the missed cleavage parameter and makes the digestion with all the possible missed cleavages (from 1 to n-1 missed cleavages with n the number of peptides gained without missed cleavages).
int compare_peptides (const void *first, const void *second)
Procedure which compares two peptides ==> useful for qsort.
void sort_peptides ()
Procedure which sorts the current experimental peptides.
void set_peptide_charge (const char * formula)
Procedure which allows to set the value of the atom charge.
double peptide_charge_weight ()
Function which allows to get the weight of the atom charge.
void default_peptide_charge ()
Procedure which sets the atom charge with the default value <=> H formula.
 formula_t * get_peptide_charge_formula ()
Function which returns the formula of the atom charge.
void init_util_digestion ()
Procedure which initialises all the data useful for digestion (enzyme table for the moment).
void set_used_enzyme (int chosen_enzyme)
Procedure which sets the chosen enzyme (default is 0 for trypsine see others in enztable.aprot).
void free_util_digestion ()
Procedure which frees all the data useful for the digestion (enzym table for the moment).
void set_nb_missed_cleavages (int missed_cleavage)
Procedure which allows to set the number of authorized missed cleavage.
 formula_t * get_formulae_of_peptides (int *nb_peptides)
Function which allows to obtain the result of the digestion in a formulae format.
int get_nb_missed_cleavages ()
Function which allows to get the number of authorized missed cleavages.
int get_activation_full_digest ()
Function which allows to get the state of the activation of full digestion.
char * get_used_enzyme ()
Function which allows to get the name of the used enzyme.
 formula_t * get_peptide_formula_from_index (int index)
Function which returns a formula corresponding to a peptide according to its place in the current digestion.
 formula_t * get_peptide_formula (peptide_t * peptide)
Function which returns a formula corresponding to a wanted peptide of the current digested protein.
 formula_t * get_peptide_formula_from_another_protein (peptide_t * peptide, char *protein_sequence)
Function which returns a formula corresponding to a wanted peptide that not belongs to the current digested protein.
void free_peptide (peptide_t * peptide)
Procedure which free the memory allocated for the post-translational modifications of a peptide.
void add_peptide_modification (peptide_t * peptide, int amino_acid, int modif)
Procedure which adds a modification on an amino acid of a peptide.
void compute_post_traductional_modifications_global ()
Procedure which computes peptides gained with post-translational modifications.
 peptide_t * compute_post_traductional_modifications_one_peptide (peptide_t * peptide, int *nb_new)
Function which computes the peptides gained with post-translational modifications from one peptide.
char * get_peptide_sequence (int index)
Function which returns the sequence of the wanted peptide, this sequence is only for making saves for printing because it can contains modifications name.
void print_peptide (peptide_t * peptide)
Procedure which allows to print directly a peptide on the stdout.
void print_peptide_index (int index)
Procedure which prints directly on the screen a peptide of the current digestion (thanks to an index).
void fprint_peptide (FILE *file, peptide_t * peptide)
Procedure which allows to print a peptide in a file.
void fprint_peptide_index (FILE *file, int index)
Procedure which prints in a file a peptide of the current digestion (thanks to an index).
int get_peptide_length_at_index (int index)
Function which returns the sequence length of a wanted peptide.
int is_equivalent_to_another (int index)
Function which indicates if a peptide is equivalent to another one due to variable post-translational modifications.
void set_maximum_peptide_length (int new_value)
Procedure which sets the maximum allowed length in amino acids for a peptide.
int get_maximum_peptide_length ()
Function which returns the maximum allowed length in amino acids for a peptide.
void compute_equivalent_peptides ()
Procedure which computes for the current digestion, the peptides which has to be marked has equivalent to another one.
Variables
 peptide_t * Peptides = NULL
Result of the current digestion.
int NbPeptides =0
Current digestion peptide number.
int FULL_DIGESTION = FALSE
Activation state of the full digest process, TRUE or FALSE (see util.h).
 formula_t * peptide_charge_formula =NULL
Formula to add for the peptide to be charged.
 enztable_t * enztable =NULL
Enzyme table.
int enzyme =0
Index of the current chosen enzyme in the enzyme table.
int nb_missed_cleavages =0
Maximum number of missed cleavage.
char * sequence =NULL
Sequence of the protein that i currently digested.
int maximum_peptide_length =30
Maximum length in amino acids allowed for a peptide.
Detailed Description
Implementation of the methods defined in digest.h.
Author
Pierre LAURENCE and David BOENS (2003).
 Modified and updated by Jean-Charles BOISSON (2005-2008).
Warning
Copyright USTL
 This software is governed by the CeCILL-C license under French law and abiding by the rules of distribution of free software.
Function Documentation
activate_full_digestion()
void activate_full_digestion (int activation)
Procedure which allows to activate or desactivate the full-digest process i.e. when it is activated, the digestion do not use the missed cleavage parameter and makes the digestion with all the possible missed cleavages (from 1 to n-1 missed cleavages with n the number of peptides gained without missed cleavages).
Parameters
activation The parameter which activates (TRUE) or not (FALSE) the full digestion.
Definition at line 693 of file digest.cpp.
References error(), FALSE, FULL_DIGESTION, TRUE, and USAGE_ERROR.
Referenced by load_boolean_keyword().
add_peptide_modification()
void add_peptide_modification (peptide_t * peptide, int amino_acid, int modif)
Procedure which adds a modification on an amino acid of a peptide.
Parameters
peptide The peptide.
amino_acid The amino acid (its index).
modif The wanted modification (its index).
Definition at line 999 of file digest.cpp.
References peptide::endOff, error(), get_formula_to_add(), get_formula_to_sub(), get_number_of_activated_modifications(), get_weight(), MEMORY_ALLOCATION_ERROR, peptide::modifications, peptide::nb_modif, peptide::startOff, USAGE_ERROR, and peptide::weight.
Referenced by compute_post_traductional_modifications_one_peptide().
compare_peptides()
int compare_peptides (const void * first, const void * second)
Procedure which compares two peptides ==> useful for qsort.
Parameters
first a void pointer that is in reality a peptide.
second a void pointer that is also a peptide.
Returns
-1, 0 or 1 <=> the first is inferior,equal or superior to the second.
Definition at line 707 of file digest.cpp.
References peptide::weight.
Referenced by compute_post_traductional_modifications_one_peptide(), and sort_peptides().
compute_equivalent_peptides()
void compute_equivalent_peptides ()
Procedure which computes for the current digestion, the peptides which has to be marked has equivalent to another one.
Definition at line 1447 of file digest.cpp.
References peptide::endOff, equals(), peptide::equivalent_to_another, error(), EXECUTION_ERROR, FALSE, get_peptide_sequence(), NbPeptides, Peptides, peptide::startOff, TRUE, and USAGE_ERROR.
Referenced by real_digest().
compute_post_traductional_modifications_global()
void compute_post_traductional_modifications_global ()
Procedure which computes peptides gained with post-translational modifications.
Definition at line 1084 of file digest.cpp.
References compute_post_traductional_modifications_one_peptide(), copy_peptide(), error(), free_peptide(), MEMORY_ALLOCATION_ERROR, NbPeptides, and Peptides.
Referenced by real_digest().
compute_post_traductional_modifications_one_peptide()
 peptide_t * compute_post_traductional_modifications_one_peptide (peptide_t * peptide, int * nb_new)
Function which computes the peptides gained with post-translational modifications from one peptide.
Parameters
peptide The peptide.
nb_new The number of new peptides generated (initialised by the function).
Returns
The new peptides.
Definition at line 1145 of file digest.cpp.
References add_peptide_modification(), can_be_used_on_for_digestion(), compare_peptides(), copy_peptide(), peptide::endOff, peptide::equivalent_to_another, error(), EXECUTION_ERROR, FALSE, FIXED, get_modification_type(), get_number_of_activated_modifications(), maximum_peptide_length, MEMORY_ALLOCATION_ERROR, nb_modifications, sequence, peptide::startOff, TRUE, USAGE_ERROR, and peptide::weight.
Referenced by compute_post_traductional_modifications_global().
copy_peptide()
 peptide_t * copy_peptide (peptide_t * original)
Function which makes a copy of a peptide.
Parameters
original The peptide we want to copy.
Returns
The copy.
Definition at line 341 of file digest.cpp.
References peptide::endOff, peptide::equivalent_to_another, error(), MEMORY_ALLOCATION_ERROR, peptide::modifications, peptide::nb_missed_cleavages, peptide::nb_modif, peptide::startOff, USAGE_ERROR, and peptide::weight.
Referenced by compute_post_traductional_modifications_global(), compute_post_traductional_modifications_one_peptide(), fusion_peptide(), get_copie_of_digestion_result(), and new_peptides_with_missed_cleavages().
default_peptide_charge()
void default_peptide_charge ()
Procedure which sets the atom charge with the default value <=> H formula.
Definition at line 755 of file digest.cpp.
References set_peptide_charge().
Referenced by init_util_digestion().
digest()
void digest ()
Procedure which realises the digestion with 0 miss-cleavage.
Definition at line 101 of file digest.cpp.
References C_SIDE, enzyme::cpl, cpl_isCleavage2(), peptide::endOff, enzyme_list::enz, enztable, peptide::equivalent_to_another, error(), FALSE, amino_acid_CF::form, free_peptide(), get_amino_acid(), get_util_formula(), get_weight(), MEMORY_ALLOCATION_ERROR, peptide::modifications, N_SIDE, peptide::nb_missed_cleavages, peptide::nb_modif, NbPeptides, peptide_charge_weight(), Peptides, sequence, enzyme::side, peptide::startOff, and peptide::weight.
Referenced by real_digest().
fprint_peptide()
void fprint_peptide (FILE * file, peptide_t * peptide)
Procedure which allows to print a peptide in a file.
Parameters
file The file.
peptide The peptide we want to print.
Definition at line 1368 of file digest.cpp.
References peptide::endOff, error(), get_activated_modification_symbol(), peptide::modifications, peptide::nb_modif, sequence, peptide::startOff, and USAGE_ERROR.
Referenced by fprint_peptide_index().
fprint_peptide_index()
void fprint_peptide_index (FILE * file, int index)
Procedure which prints in a file a peptide of the current digestion (thanks to an index).
Parameters
file The file.
index The index.
Definition at line 1394 of file digest.cpp.
References error(), fprint_peptide(), NbPeptides, Peptides, and USAGE_ERROR.
Referenced by fprint_result_of_digestion(), and fprint_result_of_digestion_table_format().
fprint_result_of_digestion()
void fprint_result_of_digestion (FILE * file, peptide_t * peptides, int nb_peptides)
Procedure which prints in a file the result of the digestion.
Parameters
file The file where the result have to be put.
peptides The peptide_t* we want to view to print.
nb_peptides The peptide number.
Definition at line 288 of file digest.cpp.
References formula_tochar(), fprint_peptide_index(), free_n_formula(), get_formulae_of_peptides(), nb_missed_cleavages, peptides, and TRUE.
fprint_result_of_digestion_table_format()
void fprint_result_of_digestion_table_format (FILE * file, peptide_t * peptides, int nb_peptides)
Procedure which prints in a file a result of the digestion in a format useful for speadsheet programs.
Parameters
file The file where the result have to be put.
peptides The peptide_t* we want to print.
nb_peptides The peptide number.
Definition at line 315 of file digest.cpp.
References formula_tochar(), fprint_peptide_index(), free_n_formula(), get_formulae_of_peptides(), nb_missed_cleavages, peptides, and TRUE.
free_peptide()
void free_peptide (peptide_t * peptide)
Procedure which free the memory allocated for the post-translational modifications of a peptide.
Parameters
peptide The peptide we want to free the memory.
Definition at line 966 of file digest.cpp.
References peptide::endOff, error(), FREE_MEMORY_ERROR, peptide::modifications, peptide::nb_modif, and peptide::startOff.
Referenced by compute_post_traductional_modifications_global(), digest(), free_util_digestion(), and new_peptides_with_missed_cleavages().
free_util_digestion()
void free_util_digestion ()
Procedure which frees all the data useful for the digestion (enzym table for the moment).
Definition at line 781 of file digest.cpp.
References enztable, free_enzym_table(), free_formula(), free_peptide(), NbPeptides, peptide_charge_formula, Peptides, and sequence.
Referenced by ascq_me_configuration_cleaning().
fusion_peptide()
 peptide_t * fusion_peptide (peptide_t * first, peptide_t * second)
Function which makes the fusion of two CONTIGUOUS (!!!) peptides.
Parameters
first The first peptide.
second The second peptide.
Warning
The two peptides must be contiguous. They are fusionned in this order (first is really before second in the peptidic sequence).
Returns
The new peptide result of the fusion.
Definition at line 420 of file digest.cpp.
References copy_peptide(), peptide::endOff, peptide::equivalent_to_another, error(), FALSE, get_util_formula(), get_weight(), MEMORY_ALLOCATION_ERROR, peptide::modifications, peptide::nb_missed_cleavages, peptide::nb_modif, peptide_charge_weight(), peptide::startOff, USAGE_ERROR, and peptide::weight.
Referenced by new_peptides_with_missed_cleavages().
get_activation_full_digest()
int get_activation_full_digest ()
Function which allows to get the state of the activation of full digestion.
Definition at line 855 of file digest.cpp.
References FULL_DIGESTION.
Referenced by fprint_configuration(), fprint_configuration_xml(), and print_configuration().
get_copie_of_digestion_result()
 peptide_t * get_copie_of_digestion_result (int * nb_peptides)
Function which allows to gain a copie of the result of the digestion.
Parameters
nb_peptides The number of peptides, initialised by the function.
Returns
The peptide list obtained after the digestion.
Definition at line 239 of file digest.cpp.
References copy_peptide(), error(), MEMORY_ALLOCATION_ERROR, NbPeptides, and Peptides.
get_formulae_of_peptides()
 formula_t * get_formulae_of_peptides (int * nb_peptides)
Function which allows to obtain the result of the digestion in a formulae format.
Parameters
nb_peptides The peptide number (initialised by the function).
Returns
The peptides in a formulae format.
Definition at line 807 of file digest.cpp.
References add_formula(), apply_modification(), copy_formula(), peptide::endOff, error(), amino_acid_CF::form, get_amino_acid(), get_peptide_charge_formula(), get_util_formula(), MEMORY_ALLOCATION_ERROR, modifications, peptide::nb_modif, NbPeptides, peptides, Peptides, sequence, and peptide::startOff.
Referenced by fprint_result_of_digestion(), fprint_result_of_digestion_table_format(), main(), and print_result_of_digestion().
get_maximum_peptide_length()
int get_maximum_peptide_length ()
Function which returns the maximum allowed length in amino acids for a peptide.
Returns
The maximum allowed length.
Definition at line 1441 of file digest.cpp.
References maximum_peptide_length.
Referenced by fprint_configuration(), fprint_configuration_xml(), and print_configuration().
get_nb_missed_cleavages()
int get_nb_missed_cleavages ()
Function which allows to get the number of authorized missed cleavages.
Definition at line 849 of file digest.cpp.
References nb_missed_cleavages.
Referenced by fprint_configuration(), fprint_configuration_xml(), and print_configuration().
get_peptide_charge_formula()
 formula_t * get_peptide_charge_formula ()
Function which returns the formula of the atom charge.
Returns
The formula of the atom charge (in formula_t* format).
Definition at line 762 of file digest.cpp.
References peptide_charge_formula.
Referenced by fprint_configuration(), fprint_configuration_xml(), get_formulae_of_peptides(), get_peptide_formula_from_another_protein(), get_peptide_formula_from_index(), and print_configuration().
get_peptide_formula()
 formula_t * get_peptide_formula (peptide_t * peptide)
Function which returns a formula corresponding to a wanted peptide of the current digested protein.
Parameters
peptide The peptide.
Returns
The corresponding formula.
Definition at line 913 of file digest.cpp.
References get_peptide_formula_from_another_protein(), and sequence.
get_peptide_formula_from_another_protein()
 formula_t * get_peptide_formula_from_another_protein (peptide_t * peptide, char * protein_sequence)
Function which returns a formula corresponding to a wanted peptide that not belongs to the current digested protein.
Parameters
peptide The peptide.
protein_sequence The corresponding complete protein sequence.
Returns
The peptide formula.
Definition at line 919 of file digest.cpp.
References add_formula(), apply_modification(), copy_formula(), peptide::endOff, error(), amino_acid_CF::form, get_amino_acid(), get_peptide_charge_formula(), get_util_formula(), peptide::modifications, peptide::nb_modif, peptide::startOff, and USAGE_ERROR.
Referenced by get_peptide_formula().
get_peptide_formula_from_index()
 formula_t * get_peptide_formula_from_index (int index)
Function which returns a formula corresponding to a peptide according to its place in the current digestion.
Parameters
index The index of the peptide in the current digestion.
Returns
The peptide formula.
Definition at line 867 of file digest.cpp.
References add_formula(), apply_modification(), copy_formula(), peptide::endOff, error(), amino_acid_CF::form, get_amino_acid(), get_peptide_charge_formula(), get_util_formula(), modifications, peptide::nb_modif, NbPeptides, Peptides, sequence, peptide::startOff, and USAGE_ERROR.
Referenced by sort_and_init_with_peptide_scoring().
get_peptide_length_at_index()
int get_peptide_length_at_index (int index)
Function which returns the sequence length of a wanted peptide.
Parameters
index The index of the wanted peptide.
Returns
The peptide length.
Definition at line 1405 of file digest.cpp.
References peptide::endOff, NbPeptides, Peptides, and peptide::startOff.
get_peptide_sequence()
char * get_peptide_sequence (int index)
Function which returns the sequence of the wanted peptide, this sequence is only for making saves for printing because it can contains modifications name.
Parameters
index The index of the wanted peptide.
Returns
The sequence.
Definition at line 1275 of file digest.cpp.
References peptide::endOff, error(), get_activated_modification_symbol(), MEMORY_ALLOCATION_ERROR, modifications, peptide::nb_modif, NbPeptides, Peptides, sequence, peptide::startOff, and USAGE_ERROR.
Referenced by compute_equivalent_peptides(), and sort_and_init_with_peptide_scoring().
get_result_of_digestion()
 peptide_t * get_result_of_digestion (int * nb_peptides)
Function which returns the peptides resulting of the digestion.
Warning
get_result_of_digestion gives a original pointer so if you want to keep this result and make other digestion, use the next function called get_copie_of_digestion_result (don't forget to free the pointer after using it)
Parameters
nb_peptides The number of peptides, initialised by the function.
Returns
The peptide list obtained after the digestion.
Definition at line 232 of file digest.cpp.
References NbPeptides, and Peptides.
get_used_enzyme()
char * get_used_enzyme ()
Function which allows to get the name of the used enzyme.
Definition at line 861 of file digest.cpp.
References enzyme_list::enz, enztable, enzyme, and enzyme::name.
Referenced by fprint_configuration(), fprint_configuration_xml(), and print_configuration().
init_util_digestion()
void init_util_digestion ()
Procedure which initialises all the data useful for digestion (enzyme table for the moment).
Definition at line 768 of file digest.cpp.
References default_peptide_charge(), ENZFILENAME, enztable, and enzym_load().
Referenced by load_configuration().
is_equivalent_to_another()
int is_equivalent_to_another (int index)
Function which indicates if a peptide is equivalent to another one due to variable post-translational modifications.
Parameters
index The index of the wanted peptide.
Returns
TRUE or FALSE (see util.h).
Definition at line 1417 of file digest.cpp.
References peptide::equivalent_to_another, NbPeptides, and Peptides.
Referenced by optimized_isotopic_distribution().
new_peptides_with_missed_cleavages()
void new_peptides_with_missed_cleavages (int missed_cleavage, int * nb_new_peptides_total)
Procedure which allows to compute the new peptides gained due to missed cleavages.
Parameters
missed_cleavage The number of missed cleavage.
nb_new_peptides_total The total number of new peptides (modified by the procedure).
Definition at line 567 of file digest.cpp.
References copy_peptide(), error(), free_peptide(), fusion_peptide(), MEMORY_ALLOCATION_ERROR, peptide::modifications, peptide::nb_modif, NbPeptides, Peptides, and peptide::weight.
Referenced by real_digest().
peptide_charge_weight()
double peptide_charge_weight ()
Function which allows to get the weight of the atom charge.
Returns
The weight of the atom charge.
Definition at line 744 of file digest.cpp.
References error(), get_weight(), peptide_charge_formula, and USAGE_ERROR.
Referenced by digest(), and fusion_peptide().
print_peptide()
void print_peptide (peptide_t * peptide)
Procedure which allows to print directly a peptide on the stdout.
Parameters
peptide The peptide we want to print.
Definition at line 1331 of file digest.cpp.
References peptide::endOff, error(), get_activated_modification_symbol(), peptide::modifications, peptide::nb_modif, sequence, peptide::startOff, and USAGE_ERROR.
Referenced by print_peptide_index().
print_peptide_index()
void print_peptide_index (int index)
Procedure which prints directly on the screen a peptide of the current digestion (thanks to an index).
Parameters
index The index of the peptide.
Definition at line 1357 of file digest.cpp.
References error(), NbPeptides, Peptides, print_peptide(), and USAGE_ERROR.
Referenced by print_result_of_digestion().
print_result_of_digestion()
void print_result_of_digestion (peptide_t * peptides, int nb_peptides)
Procedure which prints on stdout the result of the digestion.
Definition at line 261 of file digest.cpp.
References formula_tochar(), free_n_formula(), get_formulae_of_peptides(), nb_missed_cleavages, peptides, print_peptide_index(), and TRUE.
real_digest()
void real_digest (char * seq)
Procedure which realises the real digestion according the number of missed cleavages.
Parameters
seq The sequence to digest.
Definition at line 646 of file digest.cpp.
References compute_equivalent_peptides(), compute_post_traductional_modifications_global(), digest(), error(), FULL_DIGESTION, get_number_of_activated_modifications(), MEMORY_ALLOCATION_ERROR, nb_missed_cleavages, NbPeptides, new_peptides_with_missed_cleavages(), sequence, and TRUE.
Referenced by main().
set_maximum_peptide_length()
void set_maximum_peptide_length (int new_value)
Procedure which sets the maximum allowed length in amino acids for a peptide.
Parameters
new_value The new value. If a peptide has a longer length, it will be not considered during the post-translational modification computation.
Definition at line 1429 of file digest.cpp.
References error(), maximum_peptide_length, and USAGE_ERROR.
Referenced by load_int_keyword().
set_nb_missed_cleavages()
void set_nb_missed_cleavages (int missed_cleavage)
Procedure which allows to set the number of authorized missed cleavage.
Parameters
missed_cleavage The number of missed cleavages.
Definition at line 801 of file digest.cpp.
References nb_missed_cleavages.
Referenced by load_int_keyword().
set_peptide_charge()
void set_peptide_charge (const char * formula)
Procedure which allows to set the value of the atom charge.
Parameters
formula The formula (in char* format).
Definition at line 734 of file digest.cpp.
References free_formula(), get_element_table(), get_element_table_size(), peptide_charge_formula, and read_formula().
Referenced by default_peptide_charge(), and load_string_keyword().
set_used_enzyme()
void set_used_enzyme (int chosen_enzyme)
Procedure which sets the chosen enzyme (default is 0 for trypsine see others in enztable.aprot).
Parameters
chosen_enzyme The chosen_enzyme.
Definition at line 775 of file digest.cpp.
Referenced by load_int_keyword().
sort_peptides()
void sort_peptides ()
Procedure which sorts the current experimental peptides.
It is simply a call of qsort with the function compare_peptides.
Definition at line 728 of file digest.cpp.
References compare_peptides(), NbPeptides, and Peptides.
Variable Documentation
enztable
 enztable_t * enztable =NULL
Enzyme table.
Definition at line 76 of file digest.cpp.
Referenced by digest(), free_util_digestion(), get_used_enzyme(), and init_util_digestion().
enzyme
int enzyme =0
Index of the current chosen enzyme in the enzyme table.
The default value corresponds to the trypsine enzyme, see enztable.aprot to understand.
Definition at line 83 of file digest.cpp.
Referenced by get_used_enzyme().
FULL_DIGESTION
int FULL_DIGESTION = FALSE
Activation state of the full digest process, TRUE or FALSE (see util.h).
Definition at line 66 of file digest.cpp.
Referenced by activate_full_digestion(), get_activation_full_digest(), and real_digest().
maximum_peptide_length
int maximum_peptide_length =30
Maximum length in amino acids allowed for a peptide.
Definition at line 98 of file digest.cpp.
Referenced by compute_post_traductional_modifications_one_peptide(), get_maximum_peptide_length(), and set_maximum_peptide_length().
nb_missed_cleavages
int nb_missed_cleavages =0
Maximum number of missed cleavage.
Definition at line 88 of file digest.cpp.
Referenced by fprint_result_of_digestion(), fprint_result_of_digestion_table_format(), get_nb_missed_cleavages(), print_result_of_digestion(), real_digest(), and set_nb_missed_cleavages().
NbPeptides
int NbPeptides =0
Current digestion peptide number.
Definition at line 61 of file digest.cpp.
Referenced by compute_equivalent_peptides(), compute_post_traductional_modifications_global(), digest(), fprint_peptide_index(), free_util_digestion(), get_copie_of_digestion_result(), get_formulae_of_peptides(), get_peptide_formula_from_index(), get_peptide_length_at_index(), get_peptide_sequence(), get_result_of_digestion(), is_equivalent_to_another(), new_peptides_with_missed_cleavages(), print_peptide_index(), real_digest(), and sort_peptides().
peptide_charge_formula
 formula_t * peptide_charge_formula =NULL
Formula to add for the peptide to be charged.
Definition at line 71 of file digest.cpp.
Referenced by free_util_digestion(), get_peptide_charge_formula(), peptide_charge_weight(), and set_peptide_charge().
Peptides
 peptide_t * Peptides = NULL
Result of the current digestion.
Definition at line 56 of file digest.cpp.
Referenced by compute_equivalent_peptides(), compute_post_traductional_modifications_global(), digest(), fprint_peptide_index(), free_util_digestion(), get_copie_of_digestion_result(), get_formulae_of_peptides(), get_peptide_formula_from_index(), get_peptide_length_at_index(), get_peptide_sequence(), get_result_of_digestion(), is_equivalent_to_another(), new_peptides_with_missed_cleavages(), print_peptide_index(), and sort_peptides().
sequence
char * sequence =NULL
Sequence of the protein that i currently digested.
Definition at line 93 of file digest.cpp.
Referenced by add_protein(), compute_post_traductional_modifications_one_peptide(), digest(), fprint_peptide(), free_util_digestion(), get_formula_from_sequence(), get_formulae_of_peptides(), get_peptide_formula(), get_peptide_formula_from_index(), get_peptide_sequence(), main(), print_peptide(), and real_digest().