fft4g.cpp File Reference
The complete fft package is also in the ASCQ_ME sources in fft_src.
#include <math.h>
Functions
void cdft (int n, int isgn, double *a, int * ip, double * w)
Complex Discrete Fourier Transform.
void rdft (int n, int isgn, double *a, int * ip, double * w)
Real Discrete Fourier Transform.
void ddct (int n, int isgn, double *a, int * ip, double * w)
Discrete Cosine Transform.
void ddst (int n, int isgn, double *a, int * ip, double * w)
Discrete Sine Transform.
void dfct (int n, double *a, double *t, int * ip, double * w)
Cosine Transform of RDFT (Real Symmetric DFT).
void dfst (int n, double *a, double *t, int * ip, double * w)
Sine Transform of RDFT (Real Anti-symmetric DFT)
void makewt (int nw, int * ip, double * w)
One of the initializing routines.
void makect (int nc, int * ip, double *c)
One the initializing routines.
void bitrv2 (int n, int * ip, double *a)
One of the child routines.
void bitrv2conj (int n, int * ip, double *a)
One of the child routines.
void cftfsub (int n, double *a, double * w)
One of the child routines.
void cftbsub (int n, double *a, double * w)
One of the child routines.
void cft1st (int n, double *a, double * w)
One of the child routines.
void cftmdl (int n, int l, double *a, double * w)
One of the child routines.
void rftfsub (int n, double *a, int nc, double *c)
One of the child routines.
void rftbsub (int n, double *a, int nc, double *c)
One the child rountines.
void dctsub (int n, double *a, int nc, double *c)
One of the child routines.
void dstsub (int n, double *a, int nc, double *c)
One of the child routines.
Detailed Description
The complete fft package is also in the ASCQ_ME sources in fft_src.
Author
See http://momonga.t.u-tokyo.ac.jp/~ooura/fft.html where the fft package has been downloaded.
Warning
Copyright USTL
 This software is governed by the CeCILL-C license under French law and abiding by the rules of distribution of free software.
Function Documentation
bitrv2()
void bitrv2 (int n, int * ip, double * a)
One of the child routines.
Definition at line 775 of file fft4g.cpp.
References ip.
Referenced by cdft(), ddct(), ddst(), dfct(), dfst(), makewt(), and rdft().
bitrv2conj()
void bitrv2conj (int n, int * ip, double * a)
One of the child routines.
Definition at line 877 of file fft4g.cpp.
References ip.
Referenced by cdft().
cdft()
void cdft (int n, int isgn, double * a, int * ip, double * w)
Complex Discrete Fourier Transform.
Definition at line 328 of file fft4g.cpp.
References bitrv2(), bitrv2conj(), cftbsub(), cftfsub(), ip, makewt(), and w.
Referenced by init_distrib(), and optimized_isotopic_distribution().
cft1st()
void cft1st (int n, double * a, double * w)
One of the child routines.
Definition at line 1095 of file fft4g.cpp.
References w.
Referenced by cftbsub(), and cftfsub().
cftbsub()
void cftbsub (int n, double * a, double * w)
One of the child routines.
Definition at line 1041 of file fft4g.cpp.
References cft1st(), cftmdl(), and w.
Referenced by cdft(), ddct(), ddst(), and rdft().
cftfsub()
void cftfsub (int n, double * a, double * w)
One of the child routines.
Definition at line 987 of file fft4g.cpp.
References cft1st(), cftmdl(), and w.
Referenced by cdft(), ddct(), ddst(), dfct(), dfst(), and rdft().
cftmdl()
void cftmdl (int n, int l, double * a, double * w)
One of the child routines.
Definition at line 1202 of file fft4g.cpp.
References w.
Referenced by cftbsub(), and cftfsub().
dctsub()
void dctsub (int n, double * a, int nc, double * c)
One of the child routines.
Definition at line 1387 of file fft4g.cpp.
Referenced by ddct(), and dfct().
ddct()
void ddct (int n, int isgn, double * a, int * ip, double * w)
Discrete Cosine Transform.
Definition at line 404 of file fft4g.cpp.
References bitrv2(), cftbsub(), cftfsub(), dctsub(), ip, makect(), makewt(), rftbsub(), rftfsub(), and w.
ddst()
void ddst (int n, int isgn, double * a, int * ip, double * w)
Discrete Sine Transform.
Definition at line 465 of file fft4g.cpp.
References bitrv2(), cftbsub(), cftfsub(), dstsub(), ip, makect(), makewt(), rftbsub(), rftfsub(), and w.
dfct()
void dfct (int n, double * a, double * t, int * ip, double * w)
Cosine Transform of RDFT (Real Symmetric DFT).
Definition at line 526 of file fft4g.cpp.
References bitrv2(), cftfsub(), dctsub(), ip, makect(), makewt(), rftfsub(), and w.
dfst()
void dfst (int n, double * a, double * t, int * ip, double * w)
Sine Transform of RDFT (Real Anti-symmetric DFT)
Definition at line 624 of file fft4g.cpp.
References bitrv2(), cftfsub(), dstsub(), ip, makect(), makewt(), rftfsub(), and w.
dstsub()
void dstsub (int n, double * a, int nc, double * c)
One of the child routines.
Definition at line 1410 of file fft4g.cpp.
Referenced by ddst(), and dfst().
makect()
void makect (int nc, int * ip, double * c)
One the initializing routines.
Definition at line 751 of file fft4g.cpp.
References ip.
Referenced by ddct(), ddst(), dfct(), dfst(), and rdft().
makewt()
void makewt (int nw, int * ip, double * w)
One of the initializing routines.
Definition at line 719 of file fft4g.cpp.
References bitrv2(), ip, and w.
Referenced by cdft(), ddct(), ddst(), dfct(), dfst(), and rdft().
rdft()
void rdft (int n, int isgn, double * a, int * ip, double * w)
Real Discrete Fourier Transform.
Definition at line 355 of file fft4g.cpp.
References bitrv2(), cftbsub(), cftfsub(), ip, makect(), makewt(), rftbsub(), rftfsub(), and w.
rftbsub()
void rftbsub (int n, double * a, int nc, double * c)
One the child rountines.
Definition at line 1358 of file fft4g.cpp.
Referenced by ddct(), ddst(), and rdft().
rftfsub()
void rftfsub (int n, double * a, int nc, double * c)
One of the child routines.
Definition at line 1331 of file fft4g.cpp.
Referenced by ddct(), ddst(), dfct(), dfst(), and rdft().