formula.cpp File Reference
Implementation of the methods defined in formula.h.
#include `formula.h`
Functions
 isotop_t * copy_isotop (isotop_t * isotop, int number)
Local function that allows to gain the copy of an isotop structure.
 element_t * copy_one_element (element_t * element)
Local function that allows to gain the copy of an element structure.
void free_element (element_t * element)
Local procedure that frees the memory allocated for an element structure.
void add_element (formula_t *f, composition_t *comp)
Procedure which adds an element in a formula.
int closest_int (double mass)
Local tool function which returns the most close int of a double <=> rint function used because rint does not seem work on windows.
int affect_atom (char * symbol, int quantity, int isotop, composition_t *comp, element_t *elem_table, int elem_table_size)
Local function that affects the quantity of atoms in a composition_t structure.
 formula_t * read_formula (const char *c, element_t *elem_table, int elem_table_size)
Allocate and read a formula from a string.
 element_t * get_element_table (const char *filename, int * nb_elements)
 element_t * get_element (char *sym, element_t *elem_table, int elem_table_size)
Returns an element for element table.
void add_formula (formula_t *dest, formula_t *src)
Add two formula.
int sub_formula (formula_t *dest, formula_t *src)
Substrate two formula.
char * formula_tochar (formula_t *f)
Returns a string representing a formula.
void free_composition (composition_t * composition, int number)
Procedure which frees the memory allocated for a composition.
void free_formula (formula_t *f)
Free the memory allocated for a formula.
void free_n_formula (formula_t * formula, int number)
Free the memory for n formula.
void free_element_table (element_t *e, int tsize)
Free the memory allocated for the element table.
double get_weight (formula_t *f)
Get the weight of a formula.
 composition_t * copy_composition (composition_t * composition, int number)
Get the copy of a composition.
 formula_t * copy_formula (formula_t * formula)
Get the copy of a formula.
void print_formula (formula_t * formula, int number)
Print the formula on the screen.
void fprint_formula (FILE *file, formula_t * formula, int number)
Print the formula in a file.
void print_element_table (element_t * element_table, int size)
Print the element table on the screen.
void fprint_element_table (FILE *file, element_t * element_table, int size)
Print the element table in a file.
Detailed Description
Implementation of the methods defined in formula.h.
Author
Nicolas GRUSZCZYNSKA and Nicolas DOLET (2005).
 Modified and updated by Jean-Charles BOISSON (2005-2008).
Warning
Copyright USTL
 This software is governed by the CeCILL-C license under French law and abiding by the rules of distribution of free software.
Function Documentation
add_element()
void add_element (formula_t * f, composition_t * comp)
Procedure which adds an element in a formula.
Parameters
f The formula in which the elements will be added.
comp the composition which the element to add.
Definition at line 437 of file formula.cpp.
References formula::comps, copy_one_element(), composition::element, formula::nb_comp, composition::quantity, and element::symbol.
Referenced by add_formula().
add_formula()
void add_formula (formula_t * dest, formula_t * src)
Add two formula.
Parameters
dest The first formula before/after the addition.
src The second formula.
Definition at line 481 of file formula.cpp.
References add_element(), formula::comps, error(), formula::nb_comp, and USAGE_ERROR.
Referenced by apply_global_modification(), apply_modification(), get_formula_from_sequence(), get_formulae_of_peptides(), get_peptide_formula_from_another_protein(), and get_peptide_formula_from_index().
affect_atom()
int affect_atom (char * symbol, int quantity, int isotop, composition_t * comp, element_t * elem_table, int elem_table_size)
Local function that affects the quantity of atoms in a composition_t structure.
Parameters
symbol The atom symbol.
quantity The atom quantity.
isotop The wanted isotop : in the most case it is indicated the first isotop.
comp The modified composition_t strucutre.
elem_table The element table.
elem_table_size The number of elements in the table.
Returns
TRUE or FALSE the affectation has been realised.
Definition at line 114 of file formula.cpp.
References closest_int(), copy_one_element(), composition::element, error(), FALSE, isotop::isotopic_composition, element::isotops, MEMORY_ALLOCATION_ERROR, element::nb_isotops, composition::quantity, isotop::relative_mass, symbol, TRUE, and USAGE_ERROR.
Referenced by read_formula().
closest_int()
int closest_int (double mass)
Local tool function which returns the most close int of a double <=> rint function used because rint does not seem work on windows.
Parameters
mass a double.
Returns
the closest int.
Definition at line 90 of file formula.cpp.
Referenced by affect_atom().
copy_composition()
 composition_t * copy_composition (composition_t * composition, int number)
Get the copy of a composition.
Parameters
composition The original composition.
number The number of elements.
Returns
The copy.
Definition at line 722 of file formula.cpp.
References copy_one_element(), composition::element, error(), MEMORY_ALLOCATION_ERROR, composition::quantity, and USAGE_ERROR.
Referenced by copy_formula(), and optimized_isotopic_distribution().
copy_formula()
 formula_t * copy_formula (formula_t * formula)
Get the copy of a formula.
Parameters
formula The original formula.
Returns
the copy.
Definition at line 746 of file formula.cpp.
References formula::comps, copy_composition(), error(), MEMORY_ALLOCATION_ERROR, formula::nb_comp, and USAGE_ERROR.
Referenced by add_protein(), get_amino_acid_table(), get_formula_from_sequence(), get_formulae_of_peptides(), get_peptide_formula_from_another_protein(), get_peptide_formula_from_index(), and sub_formula().
copy_isotop()
 isotop_t * copy_isotop (isotop_t * isotop, int number)
Local function that allows to gain the copy of an isotop structure.
Parameters
isotop The isotop structure to copy.
number The number of isotops.
Returns
The copy.
Definition at line 677 of file formula.cpp.
References error(), isotop::isotopic_composition, MEMORY_ALLOCATION_ERROR, isotop::relative_mass, and USAGE_ERROR.
Referenced by copy_one_element().
copy_one_element()
 element_t * copy_one_element (element_t * element)
Local function that allows to gain the copy of an element structure.
Parameters
element The element structure to copy.
Returns
The copy.
Definition at line 701 of file formula.cpp.
References copy_isotop(), error(), element::isotops, MEMORY_ALLOCATION_ERROR, element::nb_isotops, element::symbol, and USAGE_ERROR.
Referenced by add_element(), affect_atom(), copy_composition(), and sub_formula().
formula_tochar()
char * formula_tochar (formula_t * f)
Returns a string representing a formula.
Parameters
f The formula.
Returns
The string corresponding to f.
Definition at line 564 of file formula.cpp.
References formula::comps, composition::element, formula::nb_comp, composition::quantity, and element::symbol.
Referenced by fprint_amino_acid_table(), fprint_configuration(), fprint_configuration_xml(), fprint_formula(), fprint_result_of_digestion(), fprint_result_of_digestion_table_format(), print_amino_acid_table(), print_configuration(), print_formula(), and print_result_of_digestion().
fprint_element_table()
void fprint_element_table (FILE * file, element_t * element_table, int size)
Print the element table in a file.
Parameters
file the file.
element_table The element table.
size The size of the element table.
Definition at line 813 of file formula.cpp.
References element_table, element::nb_isotops, and symbol.
fprint_formula()
void fprint_formula (FILE * file, formula_t * formula, int number)
Print the formula in a file.
Parameters
file The file.
formula The formula we want to print.
number The number of formula.
Definition at line 781 of file formula.cpp.
References formula_tochar().
free_composition()
void free_composition (composition_t * composition, int number)
Procedure which frees the memory allocated for a composition.
Parameters
composition The composition to free
number The number of element
Definition at line 598 of file formula.cpp.
References error(), free_element(), and FREE_MEMORY_ERROR.
Referenced by free_all_modifications(), free_formula(), free_n_formula(), optimized_isotopic_distribution(), and sub_formula().
free_element()
void free_element (element_t * element)
Local procedure that frees the memory allocated for an element structure.
Parameters
element The element structure to frees.
Definition at line 580 of file formula.cpp.
References error(), FREE_MEMORY_ERROR, and element::isotops.
Referenced by free_composition(), and sub_formula().
free_element_table()
void free_element_table (element_t * e, int tsize)
Free the memory allocated for the element table.
Parameters
e The element table table.
tsize the size of e
Definition at line 642 of file formula.cpp.
References error(), and FREE_MEMORY_ERROR.
Referenced by free_tables().
free_formula()
void free_formula (formula_t * f)
Free the memory allocated for a formula.
Parameters
f The formula.
Definition at line 614 of file formula.cpp.
References formula::comps, error(), free_composition(), FREE_MEMORY_ERROR, and formula::nb_comp.
Referenced by fprintf_ascq_me_results(), fprintf_ascq_me_results_table_form(), fprintf_ascq_me_results_xml(), free_amino_acid_table(), free_peptide_link(), free_util_digestion(), init_distrib(), is_a_wanted_protein(), printf_ascq_me_results(), set_peptide_charge(), and sub_formula().
free_n_formula()
void free_n_formula (formula_t * formula, int number)
Free the memory for n formula.
Parameters
formula The formulae.
number The number of formulae.
Definition at line 626 of file formula.cpp.
References error(), free_composition(), and FREE_MEMORY_ERROR.
Referenced by add_protein(), ascq_me_cleaning(), fprint_result_of_digestion(), fprint_result_of_digestion_table_format(), main(), and print_result_of_digestion().
get_element()
 element_t * get_element (char * sym, element_t * elem_table, int elem_table_size)
Returns an element for element table.
Parameters
sym The atom symbol.
elem_table The element table.
elem_table_size The number of elements in the table.
Returns
the element_t structure corresponding to sym
Definition at line 464 of file formula.cpp.
References error(), symbol, and USAGE_ERROR.
get_element_table()
 element_t* get_element_table (const char * filename, int * nb_elements)
Definition at line 294 of file formula.cpp.
References error(), EXECUTION_ERROR, IO_ERROR, isotop::isotopic_composition, element::isotops, jump_a_line(), jump_commentaries(), MEMORY_ALLOCATION_ERROR, element::nb_isotops, read_line(), read_until(), isotop::relative_mass, and symbol.
Referenced by init_distrib(), load_modifications(), and set_peptide_charge().
get_weight()
double get_weight (formula_t * f)
Get the weight of a formula.
Parameters
f The formula from which we want the weight.
Returns
The wanted weight.
Definition at line 660 of file formula.cpp.
References formula::comps, composition::element, error(), element::isotops, formula::nb_comp, composition::quantity, isotop::relative_mass, and USAGE_ERROR.
Referenced by add_peptide_modification(), digest(), fprint_amino_acid_table(), fprintf_ascq_me_peptide_scoring(), fprintf_ascq_me_results(), fprintf_ascq_me_results_table_form(), fprintf_ascq_me_results_xml(), fusion_peptide(), is_a_wanted_protein(), optimized_isotopic_distribution(), peptide_charge_weight(), and printf_ascq_me_results().
print_element_table()
void print_element_table (element_t * element_table, int size)
Print the element table on the screen.
Parameters
element_table The element table.
size the size of the element table.
Definition at line 796 of file formula.cpp.
References element_table, element::nb_isotops, and symbol.
print_formula()
void print_formula (formula_t * formula, int number)
Print the formula on the screen.
Parameters
formula The formula we want to print.
number Their number.
Definition at line 766 of file formula.cpp.
References formula_tochar().
read_formula()
 formula_t * read_formula (const char * c, element_t * elem_table, int elem_table_size)
Allocate and read a formula from a string.
Parameters
c The string containing formula : CH3...
elem_table The element table.
elem_table_size The number of elements in the table.
Returns
the read formula_t structure.
Definition at line 176 of file formula.cpp.
References affect_atom(), formula::comps, error(), FALSE, MEMORY_ALLOCATION_ERROR, formula::nb_comp, and USAGE_ERROR.
Referenced by get_amino_acid_table(), init_distrib(), init_peptid_link(), load_modifications(), and set_peptide_charge().
sub_formula()
int sub_formula (formula_t * dest, formula_t * src)
Substrate two formula.
Parameters
dest The first formula before/after the substraction.
src The second formula.
Returns
1 if possible, 0 else.
Definition at line 495 of file formula.cpp.
References formula::comps, copy_formula(), copy_one_element(), composition::element, error(), FALSE, free_composition(), free_element(), free_formula(), MEMORY_ALLOCATION_ERROR, formula::nb_comp, composition::quantity, element::symbol, TRUE, and USAGE_ERROR.
Referenced by apply_global_modification(), and apply_modification().