isodistrib.cpp File Reference
Implementation of the methods defined in isodistrib.h.
#include `isodistrib.h`
Functions
 complex_t ** get_X_atom (char * symbol)
Tool function which returns the complex_t** X_atom associated to a symbol or NULL if the symbol has not an associated X_atom.
 complex_t * get_t_X_atom (char * symbol)
Tool function which returns the complex_t* t_X_atom associated to a symbol or NULL if the symbol has not a associated t_X_atom.
void cdft (int, int, double *, int *, double *)
Complex Discrete Fourier Transform.
void init_distrib ()
Procedure which initializes the parameters and allocates the useful structures.
double optimized_isotopic_distribution (formula_t * peptides, int nb_peptides)
Function which calculates the isotopic distribution of a peptide list.
int get_atom_quantity (const char * symbol)
Tool function which returns the atom quantity linked to a symbol or -1 if the symbol has not an associated atom quantity.
void integral_normalization (double integral_value, int size, complex_t *t_complex)
Procedure which makes a normalization of a data array.
void write_spectrum_cplx (FILE *f, complex_t *t_complex, char *entry)
Procedure which writes a module of data in a complex spectrum file.
void write_spectrum (FILE *f, complex_t *t_complex, char *entry)
Procedure which writes a spectrum in a file.
void read_spectrum (const char *spectrum_file)
Procedure which loads a spectrum from a file.
void free_isodistrib ()
Procedure which frees the memory allocated for all the structures useful for the isotopic distribution computation.
 complex_t * get_exp_spectrum ()
Function which allows to gain access to the experimental spectrum.
 complex_t * copy_spectrum (complex_t *spectrum)
Function which makes the copie of a spectrum.
void set_exp_spectrum (complex_t *spectrum)
Procedure which allows to set manually the experimental spectrum.
void write_spectrum_peak_only (FILE *file, complex_t *spectrum, char *name)
Procedure which writes only the spectrum peaks in a file.
void read_simulated_spectrum (const char *spectrum_file)
Procedure which allows to open the file which contains theoretical spectra.
int next_simulated_spectrum ()
Function which loads the next simulated spectrum.
 complex_t * get_theo_spectrum ()
Function which allows to gain access to the simulated spectrum.
void set_threshold (double new_value)
Procedure which allows to set the threshold useful for the procedure write_spectrum_peak_only and the scoring.
double get_threshold ()
Function to obtain the threshold.
int get_spectrum_size ()
Function which returns the size of the array that contains the spectrum.
double get_step ()
Function which returns the spectra array step (distance between two spectrum points).
char * get_spectrum_original_description ()
Function which returns the original description of the current spectrum.
char * get_spectrum_original_sequence ()
Function which returns the original sequence of the current spectrum.
void set_C_atom_quantity (int new_quantity)
Procedure which allows to modify the quantity of C atom for the initialisation process.
void set_spectrum_maximum_mass (int new_value)
Procedure which allows to modify the spectrum maximum mass.
void set_gaussian_value (double new_value)
Procedure which allows to modify the gaussian value.
void set_precision (int new_value)
Procedure which allows to modify the spectrum precision.
char * get_simulated_spectra_filename ()
Function which returns the name of file containing the simulated spectra.
int get_spectrum_maximum_mass ()
Function which allows to get the maximum mass authorized for the spectrum.
double get_gaussian_value ()
Function which allows to get the gaussian value.
int get_spectrum_precision ()
Function which allows to get the spetrum precision.
char * get_experimental_filename ()
Function which returns the file name of the experimental spectrum.
int is_simulated_wanted_protein ()
Function which indicates if the current loaded protein corresponding to the specie.
void set_scoring_sensitivity (double new_value)
Procedure which allows to modify the score sensitivity.
double get_scoring_sensitivity ()
Function which returns the score sensitivity.
void set_minimum_mass (double new_value)
Procedure which allows to modify the minimum mass for the peptides.
double get_minimum_mass ()
Function which returns the minimum mass authorized for the peptides.
void set_maximum_mass (double new_value)
Procedure which allows to modify the maximum mass for the peptides.
double get_maximum_mass ()
Function which returns the maximum mass authorized for the peptides.
void set_peptide_maximum_mass (int new_value)
Procedure which allows to modify the peptide maximum mass.
void set_peptide_precision (int new_value)
Procedure which allows to modify the peptide precision.
int get_peptide_maximum_mass ()
Function which allows to get the peptide maximum mass.
int get_peptide_precision ()
Function which allows to get the peptide precision.
double compute_correlation (int index, complex_t *spectrum)
Function which gives the correlation between the two spectra (experimental and simulated) according to an index on a peptide (global = FALSE) or on the complete spectrum (global = TRUE).
double penalization_factor ()
Function which gives a penalize factor corresponding to all the no need data from the simulated spectrum.
void set_minimum_peptide_number (unsigned int new_value)
Procedure which allows to modify the minimum peptide number needed to a protein to be considered.
unsigned int get_minimum_peptide_number ()
Function which allows to get the minimum peptide number for a protein to be considered.
void set_minimum_matched_peptide_number (unsigned int new_value)
Procedure which allows to modify the minimum matched peptide number needed to a protein to be considered.
unsigned int get_minimum_matched_peptide_number ()
Function which allows to get the minimum matched peptide number for a protein to be considered.
double get_peptide_score_threshold ()
Function which allows to get the peptide score threshold to make difference between `good` and `bad` peptides.
int get_distribution_activation ()
double * get_current_peptide_score_save ()
Function which allows to get the peptide scores of the last protein considered.
unsigned int get_current_peptide_score_size ()
Function which allows to get the peptide score array size of the last protein considered.
Variables
int is_distribution_initialised = FALSE
 complex_t * t_atom
Complex array for the atom spectrum.
 complex_t * result
Complex array for the theoretical spectrum.
 complex_t * gauss
Complex array for the gaussian convolution.
 complex_t * t_peptide
Complex array for one peptide spectrum.
 complex_t * t_shifted_peptide
Complex array for one peptide spectrum with a shifted mass.
 complex_t * t_exp_spec
Complex array for the experimental spectrum.
double gaussian =0.30
The gaussian value.
int N_SPEC =65536
The spectrum precision.
int N_PEPT =0
The peptide spectrum precision.
int spectrum_maximum_mass =4096
The spectrum maximum mass.
int peptide_maximum_mass =16
The peptide spectrum maximum mass.
int peptide_precision =8
The peptide precision.
unsigned int minimum_peptide_number =5
The minimum number of peptides that the digestion has to produced for a protein to be considered.
unsigned int minimum_matched_peptide_number =3
The minimum number of peptides belonging to the `good` peptides for a protein to be considered.
double min_experimental_mass =700
The minimum authorized peptide mass.
double max_experimental_mass =2500
The maximum authorized peptide mass.
double threshold =0.0000001
The spectrum threshold.
double sensitivity =0.5
The sensitivity.
double variation_threshold =-1.0
The varation threshold.
char * experimental_file =NULL
The experimental spectrum fime.
char * spectrum_original_description =NULL
The theoretical spectrum description (from FASTA database).
char * spectrum_original_sequence =NULL
The theoretical spectrum original sequence (from FASTA database).
char * simulated_spectra_file =NULL
The name of the file that contains the spectum database.
FILE * simulated_spectra =NULL
The file that contains the simulated spectrum database.
double step
The step between two points in a complete spectrum.
double atom_step
The step between two points in the atom spectrum.
double gauss_param
The gaussian parameter.
int nb_data_amu
Number of points between each mass unit of a complete spectrum.
int atom_nb_data_amu
Number of points between each mass unit in the atom spectrum.
double peptide_score_threshold =0.0
The score threshold for consider a peptide has a good peptide or a bad peptide.
int * ip =NULL
A first variable needed for the fast fourier transform process.
double * w =NULL
A second variable needed for the fast fourier transform process.
int C_atom_quantity =1000
Maximum quantity of C atoms, the corresponding distributions from 1 to this value will be computed during the distribution initialisation.
int H_atom_quantity =4000
Maximum quantity of H atoms, the corresponding distributions from 1 to this value will be computed during the distribution initialisation.
int O_atom_quantity =250
Maximum quantity of O atoms, the corresponding distributions from 1 to this value will be computed during the distribution initialisation.
int S_atom_quantity =125
Maximum quantity of S atoms, the corresponding distributions from 1 to this value will be computed during the distribution initialisation.
int N_atom_quantity =500
Maximum quantity of N atoms, the corresponding distributions from 1 to this value will be computed during the distribution initialisation.
int Se_atom_quantity =100
Maximum quantity of Se atoms (due to the U amino acid), the corresponding distributions from 1 to this value will be computed during the distribution initialisation.
 complex_t ** C_atom =NULL
All the saved distribution of the C atom.
 complex_t ** H_atom =NULL
All the saved distribution of the H atom.
 complex_t ** O_atom =NULL
All the saved distribution of the O atom.
 complex_t ** S_atom =NULL
All the saved distribution of the S atom.
 complex_t ** N_atom =NULL
All the saved distribution of the N atom.
 complex_t ** Se_atom =NULL
All the saved distribution of the Se atom.
 complex_t * t_C_atom =NULL
The distribution of C1.
 complex_t * t_H_atom =NULL
The distribution of H1.
 complex_t * t_O_atom =NULL
The distribution of O1.
 complex_t * t_S_atom =NULL
The distribution of S1.
 complex_t * t_N_atom =NULL
The distribution of N1.
 complex_t * t_Se_atom =NULL
The distribution of Se1.
double * current_peptide_score_save =NULL
The score of the peptide of the last protein considered.
unsigned int current_peptide_score_size =0
Size the of the current_peptide_score_save array.
Detailed Description
Implementation of the methods defined in isodistrib.h.
Author
Nicolas GRUSZCZYNSKA and Nicolas DOLET (2005).
 Modified and updated by Jean-Charles BOISSON and Christian ROLANDO (2005-2008).
Warning
Copyright USTL
 This software is governed by the CeCILL-C license under French law and abiding by the rules of distribution of free software.
Function Documentation
cdft()
void cdft (int n, int isgn, double * a, int * ip, double * w)
Complex Discrete Fourier Transform.
Definition at line 328 of file fft4g.cpp.
References bitrv2(), bitrv2conj(), cftbsub(), cftfsub(), ip, makewt(), and w.
Referenced by init_distrib(), and optimized_isotopic_distribution().
compute_correlation()
double compute_correlation (int index, complex_t * spectrum)
Function which gives the correlation between the two spectra (experimental and simulated) according to an index on a peptide (global = FALSE) or on the complete spectrum (global = TRUE).
Parameters
index The index.
spectrum The spectrum to compare with the experimental spectrum.
Returns
The correlation score between the two points.
Definition at line 2315 of file isodistrib.cpp.
References N_SPEC, complex::Re, t_exp_spec, threshold, and variation_threshold.
Referenced by fprintf_ascq_me_results_table_form(), and optimized_isotopic_distribution().
copy_spectrum()
 complex_t* copy_spectrum (complex_t * spectrum)
Function which makes the copie of a spectrum.
Parameters
spectrum The spectrum to copy.
Returns
The copie.
Definition at line 1741 of file isodistrib.cpp.
References error(), complex::Im, MEMORY_ALLOCATION_ERROR, N_SPEC, complex::Re, and USAGE_ERROR.
Referenced by add_protein().
free_isodistrib()
void free_isodistrib ()
Procedure which frees the memory allocated for all the structures useful for the isotopic distribution computation.
Definition at line 1651 of file isodistrib.cpp.
References C_atom, C_atom_quantity, current_peptide_score_save, current_peptide_score_size, experimental_file, gauss, H_atom, H_atom_quantity, ip, N_atom, N_atom_quantity, O_atom, O_atom_quantity, result, S_atom, S_atom_quantity, Se_atom, Se_atom_quantity, simulated_spectra_file, spectrum_original_description, spectrum_original_sequence, t_atom, t_C_atom, t_exp_spec, t_H_atom, t_N_atom, t_O_atom, t_peptide, t_S_atom, t_Se_atom, t_shifted_peptide, and w.
Referenced by ascq_me_configuration_cleaning().
get_atom_quantity()
int get_atom_quantity (const char * symbol)
Tool function which returns the atom quantity linked to a symbol or -1 if the symbol has not an associated atom quantity.
Parameters
symbol The symbol.
Returns
The associated atom quantity or -1.
Definition at line 1350 of file isodistrib.cpp.
References C_atom_quantity, H_atom_quantity, N_atom_quantity, O_atom_quantity, S_atom_quantity, Se_atom_quantity, and symbol.
Referenced by fprint_configuration(), fprint_configuration_xml(), optimized_isotopic_distribution(), and print_configuration().
get_current_peptide_score_save()
double* get_current_peptide_score_save ()
Function which allows to get the peptide scores of the last protein considered.
Warning
This function returns a direct pointer.
Definition at line 2425 of file isodistrib.cpp.
References current_peptide_score_save.
Referenced by main().
get_current_peptide_score_size()
unsigned int get_current_peptide_score_size ()
Function which allows to get the peptide score array size of the last protein considered.
Definition at line 2431 of file isodistrib.cpp.
References current_peptide_score_size.
Referenced by main().
get_distribution_activation()
int get_distribution_activation ()
Definition at line 2419 of file isodistrib.cpp.
References is_distribution_initialised.
Referenced by load_configuration(), load_float_keyword(), and load_int_keyword().
get_exp_spectrum()
 complex_t* get_exp_spectrum ()
Function which allows to gain access to the experimental spectrum.
Returns
The experimental spectrum.
Definition at line 1735 of file isodistrib.cpp.
References t_exp_spec.
Referenced by fprintf_ascq_me_results_table_form().
get_experimental_filename()
char* get_experimental_filename ()
Function which returns the file name of the experimental spectrum.
Returns
The file name.
Definition at line 2176 of file isodistrib.cpp.
References experimental_file.
Referenced by fprint_configuration(), fprint_configuration_xml(), and print_configuration().
get_gaussian_value()
double get_gaussian_value ()
Function which allows to get the gaussian value.
Returns
The gaussian value.
Definition at line 2164 of file isodistrib.cpp.
References gaussian.
Referenced by fprint_configuration(), fprint_configuration_xml(), and print_configuration().
get_maximum_mass()
double get_maximum_mass ()
Function which returns the maximum mass authorized for the peptides.
Returns
The maximum mass.
Definition at line 2262 of file isodistrib.cpp.
References max_experimental_mass.
Referenced by fprint_configuration(), fprint_configuration_xml(), fprintf_ascq_me_results_table_form(), and print_configuration().
get_minimum_mass()
double get_minimum_mass ()
Function which returns the minimum mass authorized for the peptides.
Returns
The minimum mass.
Definition at line 2236 of file isodistrib.cpp.
References min_experimental_mass.
Referenced by fprint_configuration(), fprint_configuration_xml(), fprintf_ascq_me_results_table_form(), and print_configuration().
get_minimum_matched_peptide_number()
unsigned int get_minimum_matched_peptide_number ()
Function which allows to get the minimum matched peptide number for a protein to be considered.
Returns
The minimum matched peptide number.
Definition at line 2407 of file isodistrib.cpp.
References minimum_matched_peptide_number.
Referenced by fprint_configuration(), fprint_configuration_xml(), and print_configuration().
get_minimum_peptide_number()
unsigned int get_minimum_peptide_number ()
Function which allows to get the minimum peptide number for a protein to be considered.
Returns
The minimum peptide number.
Definition at line 2386 of file isodistrib.cpp.
References minimum_peptide_number.
Referenced by fprint_configuration(), fprint_configuration_xml(), and print_configuration().
get_peptide_maximum_mass()
int get_peptide_maximum_mass ()
Function which allows to get the peptide maximum mass.
Returns
The peptide maximum mass.
Definition at line 2303 of file isodistrib.cpp.
References peptide_maximum_mass.
Referenced by fprint_configuration(), fprint_configuration_xml(), and print_configuration().
get_peptide_precision()
int get_peptide_precision ()
Function which allows to get the peptide precision.
Returns
The peptide precision.
Definition at line 2309 of file isodistrib.cpp.
References peptide_precision.
Referenced by fprint_configuration(), fprint_configuration_xml(), and print_configuration().
get_peptide_score_threshold()
double get_peptide_score_threshold ()
Function which allows to get the peptide score threshold to make difference between `good` and `bad` peptides.
Returns
The peptide score threshold.
Definition at line 2413 of file isodistrib.cpp.
References peptide_score_threshold.
Referenced by fprintf_ascq_me_results().
get_scoring_sensitivity()
double get_scoring_sensitivity ()
Function which returns the score sensitivity.
Returns
The sensitivity.
Definition at line 2214 of file isodistrib.cpp.
References sensitivity.
Referenced by fprint_configuration(), fprint_configuration_xml(), and print_configuration().
get_simulated_spectra_filename()
char* get_simulated_spectra_filename ()
Function which returns the name of file containing the simulated spectra.
Returns
The file name.
Definition at line 2152 of file isodistrib.cpp.
References simulated_spectra_file.
Referenced by fprint_configuration(), fprint_configuration_xml(), and print_configuration().
get_spectrum_maximum_mass()
int get_spectrum_maximum_mass ()
Function which allows to get the maximum mass authorized for the spectrum.
Returns
The maximum mass.
Definition at line 2158 of file isodistrib.cpp.
References spectrum_maximum_mass.
Referenced by fprint_configuration(), fprint_configuration_xml(), and print_configuration().
get_spectrum_original_description()
char* get_spectrum_original_description ()
Function which returns the original description of the current spectrum.
Returns
The original description.
Definition at line 2050 of file isodistrib.cpp.
References spectrum_original_description.
Referenced by main().
get_spectrum_original_sequence()
char* get_spectrum_original_sequence ()
Function which returns the original sequence of the current spectrum.
Returns
The original sequence.
Definition at line 2056 of file isodistrib.cpp.
References spectrum_original_sequence.
Referenced by main().
get_spectrum_precision()
int get_spectrum_precision ()
Function which allows to get the spetrum precision.
Returns
The precision.
Definition at line 2170 of file isodistrib.cpp.
References N_SPEC.
Referenced by fprint_configuration(), fprint_configuration_xml(), and print_configuration().
get_spectrum_size()
int get_spectrum_size ()
Function which returns the size of the array that contains the spectrum.
Returns
The size.
Definition at line 2038 of file isodistrib.cpp.
References N_SPEC.
get_step()
double get_step ()
Function which returns the spectra array step (distance between two spectrum points).
Returns
The step.
Definition at line 2044 of file isodistrib.cpp.
References step.
Referenced by fprintf_ascq_me_results_table_form().
get_t_X_atom()
 complex_t * get_t_X_atom (char * symbol)
Tool function which returns the complex_t* t_X_atom associated to a symbol or NULL if the symbol has not a associated t_X_atom.
Parameters
symbol The symbol.
Returns
The associated t_X_atom or NULL.
Definition at line 1416 of file isodistrib.cpp.
References symbol, t_C_atom, t_H_atom, t_N_atom, t_O_atom, t_S_atom, and t_Se_atom.
Referenced by optimized_isotopic_distribution().
get_theo_spectrum()
 complex_t* get_theo_spectrum ()
Function which allows to gain access to the simulated spectrum.
Returns
The theoretical spectrum.
Definition at line 2020 of file isodistrib.cpp.
References result.
Referenced by main().
get_threshold()
double get_threshold ()
Function to obtain the threshold.
Returns
The threshold.
Definition at line 2032 of file isodistrib.cpp.
References threshold.
Referenced by fprint_configuration(), fprint_configuration_xml(), and print_configuration().
get_X_atom()
 complex_t ** get_X_atom (char * symbol)
Tool function which returns the complex_t** X_atom associated to a symbol or NULL if the symbol has not an associated X_atom.
Parameters
symbol The symbol.
Returns
The associated X_atom or NULL.
Definition at line 1383 of file isodistrib.cpp.
References C_atom, H_atom, N_atom, O_atom, S_atom, Se_atom, and symbol.
Referenced by optimized_isotopic_distribution().
init_distrib()
void init_distrib ()
Procedure which initializes the parameters and allocates the useful structures.
Definition at line 336 of file isodistrib.cpp.
References atom_nb_data_amu, atom_step, C_atom, C_atom_quantity, cdft(), complex_multiplication(), formula::comps, composition::element, error(), free_formula(), gauss, gauss_param, gaussian, get_element_table(), get_element_table_size(), H_atom, H_atom_quantity, complex::Im, ip, is_distribution_initialised, is_verbose_mode_activated(), isotop::isotopic_composition, element::isotops, MEMORY_ALLOCATION_ERROR, N_atom, N_atom_quantity, N_PEPT, N_SPEC, nb_data_amu, element::nb_isotops, O_atom, O_atom_quantity, peptide_maximum_mass, peptide_precision, complex::Re, read_formula(), isotop::relative_mass, result, S_atom, S_atom_quantity, Se_atom, Se_atom_quantity, spectrum_maximum_mass, step, t_atom, t_C_atom, t_exp_spec, t_H_atom, t_N_atom, t_O_atom, t_peptide, t_S_atom, t_Se_atom, t_shifted_peptide, TRUE, and w.
Referenced by load_string_keyword().
integral_normalization()
void integral_normalization (double integral_value, int size, complex_t * t_complex)
Procedure which makes a normalization of a data array.
Parameters
integral_value The used integral value.
size The t_complex structure size.
t_complex The data to normalize.
Definition at line 1449 of file isodistrib.cpp.
References complex::Re.
Referenced by optimized_isotopic_distribution(), and read_spectrum().
is_simulated_wanted_protein()
int is_simulated_wanted_protein ()
Function which indicates if the current loaded protein corresponding to the specie.
Returns
TRUE or FALSE (see util.h).
Definition at line 2182 of file isodistrib.cpp.
References error(), get_specie(), spectrum_original_description, TRUE, and USAGE_ERROR.
Referenced by main().
next_simulated_spectrum()
int next_simulated_spectrum ()
Function which loads the next simulated spectrum.
Warning
This function must be called after read_simulated_spectrum, not before.
Returns
TRUE or FALSE, Does a protein have been loaded ?
Definition at line 1813 of file isodistrib.cpp.
References error(), FALSE, complex::Im, IO_ERROR, MEMORY_ALLOCATION_ERROR, N_SPEC, complex::Re, result, simulated_spectra, spectrum_original_description, spectrum_original_sequence, step, TRUE, and USAGE_ERROR.
Referenced by main().
optimized_isotopic_distribution()
double optimized_isotopic_distribution (formula_t * peptides, int nb_peptides)
Function which calculates the isotopic distribution of a peptide list.
Parameters
peptides The peptide list.
nb_peptides The peptide number.
Returns
The total score of the protein corresponding to the peptide list.
!!! The 2 last mass are thought to belong the main isotopic peak !!!!
!!! The 2 last mass are thought to belong the main isotopic peak !!!!
Definition at line 1029 of file isodistrib.cpp.
References atom_step, cdft(), complex_multiplication(), compute_correlation(), copy_composition(), current_peptide_score_save, current_peptide_score_size, composition::element, error(), EXECUTION_ERROR, free_composition(), gauss, get_atom_quantity(), get_t_X_atom(), get_weight(), get_X_atom(), complex::Im, integral_normalization(), ip, is_equivalent_to_another(), is_verbose_mode_activated(), isotop::isotopic_composition, element::isotops, max_experimental_mass, MEMORY_ALLOCATION_ERROR, min_experimental_mass, minimum_matched_peptide_number, minimum_peptide_number, N_PEPT, N_SPEC, nb_data_amu, element::nb_isotops, peptide_maximum_mass, peptide_precision, peptide_score_threshold, peptides, composition::quantity, complex::Re, isotop::relative_mass, result, step, element::symbol, t_atom, t_peptide, t_shifted_peptide, threshold, TRUE, and w.
Referenced by main().
penalization_factor()
double penalization_factor ()
Function which gives a penalize factor corresponding to all the no need data from the simulated spectrum.
Returns
The penalization score.
Definition at line 2351 of file isodistrib.cpp.
References max_experimental_mass, min_experimental_mass, complex::Re, result, step, t_exp_spec, threshold, and variation_threshold.
read_simulated_spectrum()
void read_simulated_spectrum (const char * spectrum_file)
Procedure which allows to open the file which contains theoretical spectra.
Warning
This procedure opens only the file and don't load any data.
Parameters
spectrum_file The name of the file which contains simulated spectra.
Definition at line 1795 of file isodistrib.cpp.
References error(), IO_ERROR, MEMORY_ALLOCATION_ERROR, simulated_spectra, and simulated_spectra_file.
Referenced by load_string_keyword().
read_spectrum()
void read_spectrum (const char * spectrum_file)
Procedure which loads a spectrum from a file.
Parameters
spectrum_file The spectrum file.
Definition at line 1514 of file isodistrib.cpp.
References error(), experimental_file, FALSE, complex::Im, integral_normalization(), IO_ERROR, is_verbose_mode_activated(), jump_commentaries(), max_experimental_mass, MEMORY_ALLOCATION_ERROR, min_experimental_mass, N_SPEC, complex::Re, step, t_exp_spec, TRUE, USAGE_ERROR, variation_threshold, and WARNING.
Referenced by load_string_keyword().
set_C_atom_quantity()
void set_C_atom_quantity (int new_quantity)
Procedure which allows to modify the quantity of C atom for the initialisation process.
Warning
The call to this procedure will change the H, O, N and S quantities with the corresponding factor *4, /4, /2 and /8.
 The call is refused if the distribution has already been initialised.
Parameters
new_quantity The new atom C quantity.
Definition at line 2062 of file isodistrib.cpp.
References C_atom, C_atom_quantity, error(), H_atom_quantity, N_atom_quantity, O_atom_quantity, S_atom_quantity, Se_atom_quantity, and USAGE_ERROR.
Referenced by load_int_keyword().
set_exp_spectrum()
void set_exp_spectrum (complex_t * spectrum)
Procedure which allows to set manually the experimental spectrum.
Parameters
spectrum The experimental spectrum.
Definition at line 1765 of file isodistrib.cpp.
References error(), complex::Im, N_SPEC, complex::Re, t_exp_spec, and USAGE_ERROR.
set_gaussian_value()
void set_gaussian_value (double new_value)
Procedure which allows to modify the gaussian value.
Warning
The call is refused if the procedure init_distrib has been already used.
Parameters
new_value The new gaussian value.
Definition at line 2120 of file isodistrib.cpp.
References error(), gaussian, N_PEPT, and USAGE_ERROR.
Referenced by load_float_keyword().
set_maximum_mass()
void set_maximum_mass (double new_value)
Procedure which allows to modify the maximum mass for the peptides.
Warning
The call is refused if the procedure init_distrib has been already used.
Parameters
new_value The new maximum mass.
Definition at line 2242 of file isodistrib.cpp.
References error(), max_experimental_mass, N_PEPT, spectrum_maximum_mass, and USAGE_ERROR.
Referenced by load_float_keyword().
set_minimum_mass()
void set_minimum_mass (double new_value)
Procedure which allows to modify the minimum mass for the peptides.
Warning
The call is refused if the procedure init_distrib has been already used.
Parameters
new_value The new minimum mass.
Definition at line 2220 of file isodistrib.cpp.
References error(), min_experimental_mass, N_PEPT, and USAGE_ERROR.
Referenced by load_float_keyword().
set_minimum_matched_peptide_number()
void set_minimum_matched_peptide_number (unsigned int new_value)
Procedure which allows to modify the minimum matched peptide number needed to a protein to be considered.
Warning
The call is refused if the procedure is_parsing_started (see seqio.h/.cpp) return TRUE.
Parameters
new_value The new minimum matched peptide number.
Definition at line 2392 of file isodistrib.cpp.
References error(), is_parsing_started(), minimum_matched_peptide_number, TRUE, and WARNING.
Referenced by load_unsigned_int_keyword().
set_minimum_peptide_number()
void set_minimum_peptide_number (unsigned int new_value)
Procedure which allows to modify the minimum peptide number needed to a protein to be considered.
Warning
The call is refused if the procedure is_parsing_started (see seqio.h/.cpp) return TRUE.
Parameters
new_value The new minimum peptide number.
Definition at line 2371 of file isodistrib.cpp.
References error(), is_parsing_started(), minimum_peptide_number, TRUE, and WARNING.
Referenced by load_unsigned_int_keyword().
set_peptide_maximum_mass()
void set_peptide_maximum_mass (int new_value)
Procedure which allows to modify the peptide maximum mass.
Warning
The call is refused if the procedure init_distrib has been already used.
Parameters
new_value The new peptide maximum mass.
Definition at line 2268 of file isodistrib.cpp.
References error(), N_PEPT, peptide_maximum_mass, and USAGE_ERROR.
Referenced by load_int_keyword().
set_peptide_precision()
void set_peptide_precision (int new_value)
Procedure which allows to modify the peptide precision.
Warning
The call is refused if the procedure init_distrib has been already used.
Parameters
new_value The new peptide precision.
Definition at line 2284 of file isodistrib.cpp.
References error(), N_PEPT, peptide_precision, USAGE_ERROR, and WARNING.
Referenced by load_int_keyword().
set_precision()
void set_precision (int new_value)
Procedure which allows to modify the spectrum precision.
Warning
The call is refused if the procedure init_distrib has been already used.
Parameters
new_value The new precision.
Definition at line 2136 of file isodistrib.cpp.
References error(), N_PEPT, N_SPEC, and USAGE_ERROR.
Referenced by load_int_keyword().
set_scoring_sensitivity()
void set_scoring_sensitivity (double new_value)
Procedure which allows to modify the score sensitivity.
Warning
The call is refused if the procedure init_distrib has been already used.
Parameters
new_value The new sensitivity.
Definition at line 2198 of file isodistrib.cpp.
References error(), N_PEPT, sensitivity, and USAGE_ERROR.
Referenced by load_float_keyword().
set_spectrum_maximum_mass()
void set_spectrum_maximum_mass (int new_value)
Procedure which allows to modify the spectrum maximum mass.
Warning
The call is refused if the procedure init_distrib has been already used.
Parameters
new_value The new maximum mass.
Definition at line 2104 of file isodistrib.cpp.
References error(), N_PEPT, spectrum_maximum_mass, and USAGE_ERROR.
Referenced by load_int_keyword().
set_threshold()
void set_threshold (double new_value)
Procedure which allows to set the threshold useful for the procedure write_spectrum_peak_only and the scoring.
Parameters
new_value The new value.
Definition at line 2026 of file isodistrib.cpp.
References threshold.
Referenced by load_float_keyword().
write_spectrum()
void write_spectrum (FILE * f, complex_t * t_complex, char * entry)
Procedure which writes a spectrum in a file.
Parameters
f The file where the spectrum will be write.
t_complex The spectrum to save.
entry The spectrum name.
Definition at line 1502 of file isodistrib.cpp.
References N_SPEC, and step.
write_spectrum_cplx()
void write_spectrum_cplx (FILE * f, complex_t * t_complex, char * entry)
Procedure which writes a module of data in a complex spectrum file.
Parameters
f The file.
t_complex The spectrum.
entry The spectrum name.
Definition at line 1490 of file isodistrib.cpp.
References N_SPEC, and step.
write_spectrum_peak_only()
void write_spectrum_peak_only (FILE * file, complex_t * spectrum, char * name)
Procedure which writes only the spectrum peaks in a file.
Parameters
file The file where the spectrum will be save.
spectrum The spectrum.
name The spectrum name.
Definition at line 1781 of file isodistrib.cpp.
References N_SPEC, step, and threshold.
Variable Documentation
atom_nb_data_amu
int atom_nb_data_amu
Number of points between each mass unit in the atom spectrum.
Definition at line 202 of file isodistrib.cpp.
Referenced by init_distrib().
atom_step
double atom_step
The step between two points in the atom spectrum.
Definition at line 187 of file isodistrib.cpp.
Referenced by init_distrib(), and optimized_isotopic_distribution().
C_atom
 complex_t ** C_atom =NULL
All the saved distribution of the C atom.
Definition at line 252 of file isodistrib.cpp.
Referenced by free_isodistrib(), get_X_atom(), init_distrib(), and set_C_atom_quantity().
C_atom_quantity
int C_atom_quantity =1000
Maximum quantity of C atoms, the corresponding distributions from 1 to this value will be computed during the distribution initialisation.
Definition at line 222 of file isodistrib.cpp.
Referenced by free_isodistrib(), get_atom_quantity(), init_distrib(), and set_C_atom_quantity().
current_peptide_score_save
double * current_peptide_score_save =NULL
The score of the peptide of the last protein considered.
Definition at line 312 of file isodistrib.cpp.
Referenced by free_isodistrib(), get_current_peptide_score_save(), and optimized_isotopic_distribution().
current_peptide_score_size
unsigned int current_peptide_score_size =0
Size the of the current_peptide_score_save array.
Definition at line 317 of file isodistrib.cpp.
Referenced by free_isodistrib(), get_current_peptide_score_size(), and optimized_isotopic_distribution().
experimental_file
char * experimental_file =NULL
The experimental spectrum fime.
Definition at line 157 of file isodistrib.cpp.
Referenced by free_isodistrib(), get_experimental_filename(), and read_spectrum().
gauss
 complex_t * gauss
Complex array for the gaussian convolution.
Definition at line 72 of file isodistrib.cpp.
Referenced by free_isodistrib(), init_distrib(), and optimized_isotopic_distribution().
gauss_param
double gauss_param
The gaussian parameter.
Definition at line 192 of file isodistrib.cpp.
Referenced by init_distrib().
gaussian
double gaussian =0.30
The gaussian value.
Definition at line 92 of file isodistrib.cpp.
Referenced by get_gaussian_value(), init_distrib(), and set_gaussian_value().
H_atom
 complex_t ** H_atom =NULL
All the saved distribution of the H atom.
Definition at line 257 of file isodistrib.cpp.
Referenced by free_isodistrib(), get_X_atom(), and init_distrib().
H_atom_quantity
int H_atom_quantity =4000
Maximum quantity of H atoms, the corresponding distributions from 1 to this value will be computed during the distribution initialisation.
Definition at line 227 of file isodistrib.cpp.
Referenced by free_isodistrib(), get_atom_quantity(), init_distrib(), and set_C_atom_quantity().
ip
int * ip =NULL
A first variable needed for the fast fourier transform process.
Definition at line 212 of file isodistrib.cpp.
Referenced by bitrv2(), bitrv2conj(), cdft(), ddct(), ddst(), dfct(), dfst(), free_isodistrib(), init_distrib(), makect(), makewt(), optimized_isotopic_distribution(), and rdft().
is_distribution_initialised
int is_distribution_initialised = FALSE
Definition at line 57 of file isodistrib.cpp.
Referenced by get_distribution_activation(), and init_distrib().
max_experimental_mass
double max_experimental_mass =2500
The maximum authorized peptide mass.
Definition at line 137 of file isodistrib.cpp.
Referenced by get_maximum_mass(), optimized_isotopic_distribution(), penalization_factor(), read_spectrum(), and set_maximum_mass().
min_experimental_mass
double min_experimental_mass =700
The minimum authorized peptide mass.
Definition at line 132 of file isodistrib.cpp.
Referenced by get_minimum_mass(), optimized_isotopic_distribution(), penalization_factor(), read_spectrum(), and set_minimum_mass().
minimum_matched_peptide_number
unsigned int minimum_matched_peptide_number =3
The minimum number of peptides belonging to the `good` peptides for a protein to be considered.
Definition at line 127 of file isodistrib.cpp.
Referenced by get_minimum_matched_peptide_number(), optimized_isotopic_distribution(), and set_minimum_matched_peptide_number().
minimum_peptide_number
unsigned int minimum_peptide_number =5
The minimum number of peptides that the digestion has to produced for a protein to be considered.
Definition at line 122 of file isodistrib.cpp.
Referenced by get_minimum_peptide_number(), optimized_isotopic_distribution(), and set_minimum_peptide_number().
N_atom
 complex_t ** N_atom =NULL
All the saved distribution of the N atom.
Definition at line 272 of file isodistrib.cpp.
Referenced by free_isodistrib(), get_X_atom(), and init_distrib().
N_atom_quantity
int N_atom_quantity =500
Maximum quantity of N atoms, the corresponding distributions from 1 to this value will be computed during the distribution initialisation.
Definition at line 242 of file isodistrib.cpp.
Referenced by free_isodistrib(), get_atom_quantity(), init_distrib(), and set_C_atom_quantity().
N_PEPT
int N_PEPT =0
The peptide spectrum precision.
Definition at line 102 of file isodistrib.cpp.
Referenced by init_distrib(), optimized_isotopic_distribution(), set_gaussian_value(), set_maximum_mass(), set_minimum_mass(), set_peptide_maximum_mass(), set_peptide_precision(), set_precision(), set_scoring_sensitivity(), and set_spectrum_maximum_mass().
N_SPEC
int N_SPEC =65536
The spectrum precision.
Definition at line 97 of file isodistrib.cpp.
Referenced by compute_correlation(), copy_spectrum(), get_spectrum_precision(), get_spectrum_size(), init_distrib(), next_simulated_spectrum(), optimized_isotopic_distribution(), read_spectrum(), set_exp_spectrum(), set_precision(), write_spectrum(), write_spectrum_cplx(), and write_spectrum_peak_only().
nb_data_amu
int nb_data_amu
Number of points between each mass unit of a complete spectrum.
Definition at line 197 of file isodistrib.cpp.
Referenced by init_distrib(), and optimized_isotopic_distribution().
O_atom
 complex_t ** O_atom =NULL
All the saved distribution of the O atom.
Definition at line 262 of file isodistrib.cpp.
Referenced by free_isodistrib(), get_X_atom(), and init_distrib().
O_atom_quantity
int O_atom_quantity =250
Maximum quantity of O atoms, the corresponding distributions from 1 to this value will be computed during the distribution initialisation.
Definition at line 232 of file isodistrib.cpp.
Referenced by free_isodistrib(), get_atom_quantity(), init_distrib(), and set_C_atom_quantity().
peptide_maximum_mass
int peptide_maximum_mass =16
The peptide spectrum maximum mass.
Definition at line 112 of file isodistrib.cpp.
Referenced by get_peptide_maximum_mass(), init_distrib(), optimized_isotopic_distribution(), and set_peptide_maximum_mass().
peptide_precision
int peptide_precision =8
The peptide precision.
Definition at line 117 of file isodistrib.cpp.
Referenced by get_peptide_precision(), init_distrib(), optimized_isotopic_distribution(), and set_peptide_precision().
peptide_score_threshold
double peptide_score_threshold =0.0
The score threshold for consider a peptide has a good peptide or a bad peptide.
Definition at line 207 of file isodistrib.cpp.
Referenced by get_peptide_score_threshold(), and optimized_isotopic_distribution().
result
 complex_t * result
Complex array for the theoretical spectrum.
Definition at line 67 of file isodistrib.cpp.
Referenced by add_chains(), free_isodistrib(), get_reversed_sequence(), get_theo_spectrum(), init_distrib(), next_simulated_spectrum(), optimized_isotopic_distribution(), and penalization_factor().
S_atom
 complex_t ** S_atom =NULL
All the saved distribution of the S atom.
Definition at line 267 of file isodistrib.cpp.
Referenced by free_isodistrib(), get_X_atom(), and init_distrib().
S_atom_quantity
int S_atom_quantity =125
Maximum quantity of S atoms, the corresponding distributions from 1 to this value will be computed during the distribution initialisation.
Definition at line 237 of file isodistrib.cpp.
Referenced by free_isodistrib(), get_atom_quantity(), init_distrib(), and set_C_atom_quantity().
Se_atom
 complex_t ** Se_atom =NULL
All the saved distribution of the Se atom.
Definition at line 277 of file isodistrib.cpp.
Referenced by free_isodistrib(), get_X_atom(), and init_distrib().
Se_atom_quantity
int Se_atom_quantity =100
Maximum quantity of Se atoms (due to the U amino acid), the corresponding distributions from 1 to this value will be computed during the distribution initialisation.
Definition at line 247 of file isodistrib.cpp.
Referenced by free_isodistrib(), get_atom_quantity(), init_distrib(), and set_C_atom_quantity().
sensitivity
double sensitivity =0.5
The sensitivity.
Definition at line 147 of file isodistrib.cpp.
Referenced by get_scoring_sensitivity(), and set_scoring_sensitivity().
simulated_spectra
FILE * simulated_spectra =NULL
The file that contains the simulated spectrum database.
Definition at line 177 of file isodistrib.cpp.
Referenced by next_simulated_spectrum(), and read_simulated_spectrum().
simulated_spectra_file
char * simulated_spectra_file =NULL
The name of the file that contains the spectum database.
Definition at line 172 of file isodistrib.cpp.
Referenced by free_isodistrib(), get_simulated_spectra_filename(), and read_simulated_spectrum().
spectrum_maximum_mass
int spectrum_maximum_mass =4096
The spectrum maximum mass.
Definition at line 107 of file isodistrib.cpp.
Referenced by get_spectrum_maximum_mass(), init_distrib(), set_maximum_mass(), and set_spectrum_maximum_mass().
spectrum_original_description
char * spectrum_original_description =NULL
The theoretical spectrum description (from FASTA database).
Definition at line 162 of file isodistrib.cpp.
Referenced by free_isodistrib(), get_spectrum_original_description(), is_simulated_wanted_protein(), and next_simulated_spectrum().
spectrum_original_sequence
char * spectrum_original_sequence =NULL
The theoretical spectrum original sequence (from FASTA database).
Definition at line 167 of file isodistrib.cpp.
Referenced by free_isodistrib(), get_spectrum_original_sequence(), and next_simulated_spectrum().
step
int step
The step between two points in a complete spectrum.
Definition at line 182 of file isodistrib.cpp.
Referenced by get_step(), init_distrib(), next_simulated_spectrum(), optimized_isotopic_distribution(), penalization_factor(), read_spectrum(), write_spectrum(), write_spectrum_cplx(), and write_spectrum_peak_only().
t_atom
 complex_t * t_atom
Complex array for the atom spectrum.
Definition at line 62 of file isodistrib.cpp.
Referenced by free_isodistrib(), init_distrib(), and optimized_isotopic_distribution().
t_C_atom
 complex_t * t_C_atom =NULL
The distribution of C1.
Definition at line 282 of file isodistrib.cpp.
Referenced by free_isodistrib(), get_t_X_atom(), and init_distrib().
t_exp_spec
 complex_t * t_exp_spec
Complex array for the experimental spectrum.
Definition at line 87 of file isodistrib.cpp.
Referenced by compute_correlation(), free_isodistrib(), get_exp_spectrum(), init_distrib(), penalization_factor(), read_spectrum(), and set_exp_spectrum().
t_H_atom
 complex_t * t_H_atom =NULL
The distribution of H1.
Definition at line 287 of file isodistrib.cpp.
Referenced by free_isodistrib(), get_t_X_atom(), and init_distrib().
t_N_atom
 complex_t * t_N_atom =NULL
The distribution of N1.
Definition at line 302 of file isodistrib.cpp.
Referenced by free_isodistrib(), get_t_X_atom(), and init_distrib().
t_O_atom
 complex_t * t_O_atom =NULL
The distribution of O1.
Definition at line 292 of file isodistrib.cpp.
Referenced by free_isodistrib(), get_t_X_atom(), and init_distrib().
t_peptide
 complex_t * t_peptide
Complex array for one peptide spectrum.
Definition at line 77 of file isodistrib.cpp.
Referenced by free_isodistrib(), init_distrib(), and optimized_isotopic_distribution().
t_S_atom
 complex_t * t_S_atom =NULL
The distribution of S1.
Definition at line 297 of file isodistrib.cpp.
Referenced by free_isodistrib(), get_t_X_atom(), and init_distrib().
t_Se_atom
 complex_t * t_Se_atom =NULL
The distribution of Se1.
Definition at line 307 of file isodistrib.cpp.
Referenced by free_isodistrib(), get_t_X_atom(), and init_distrib().
t_shifted_peptide
 complex_t * t_shifted_peptide
Complex array for one peptide spectrum with a shifted mass.
Definition at line 82 of file isodistrib.cpp.
Referenced by free_isodistrib(), init_distrib(), and optimized_isotopic_distribution().
threshold
double threshold =0.0000001
The spectrum threshold.
Definition at line 142 of file isodistrib.cpp.
Referenced by compute_correlation(), get_threshold(), optimized_isotopic_distribution(), penalization_factor(), set_threshold(), and write_spectrum_peak_only().
variation_threshold
double variation_threshold =-1.0
The varation threshold.
Definition at line 152 of file isodistrib.cpp.
Referenced by compute_correlation(), penalization_factor(), and read_spectrum().
w
double * w =NULL
A second variable needed for the fast fourier transform process.
Definition at line 217 of file isodistrib.cpp.
Referenced by cdft(), cft1st(), cftbsub(), cftfsub(), cftmdl(), ddct(), ddst(), dfct(), dfst(), free_isodistrib(), init_distrib(), makewt(), optimized_isotopic_distribution(), and rdft().