isodistrib.h File Reference
Definition of the methods to make simulated spectrum computation.
#include `complex.h`
#include `digest.h`
#include `seqio.h`
Functions
void init_distrib ()
Procedure which initializes the parameters and allocates the useful structures.
void element_convolution (composition_t *comp)
Procedure which makes the convolution for one atom.
double optimized_isotopic_distribution (formula_t * peptides, int nb_peptides)
Function which calculates the isotopic distribution of a peptide list.
void free_isodistrib ()
Procedure which frees the memory allocated for all the structures useful for the isotopic distribution computation.
void integral_normalization (double integral_value, int size, complex_t *t_complex)
Procedure which makes a normalization of a data array.
void write_spectrum (FILE *f, complex_t *t_complex, char *entry)
Procedure which writes a spectrum in a file.
void read_spectrum (const char *spectrum_file)
Procedure which loads a spectrum from a file.
 complex_t * get_exp_spectrum ()
Function which allows to gain access to the experimental spectrum.
 complex_t * get_theo_spectrum ()
Function which allows to gain access to the simulated spectrum.
 complex_t * copy_spectrum (complex_t *spectrum)
Function which makes the copie of a spectrum.
void set_exp_spectrum (complex_t *spectrum)
Procedure which allows to set manually the experimental spectrum.
void write_spectrum_peak_only (FILE *file, complex_t *spectrum, char *name)
Procedure which writes only the spectrum peaks in a file.
void read_simulated_spectrum (const char *spectrum_file)
Procedure which allows to open the file which contains theoretical spectra.
int next_simulated_spectrum ()
Function which loads the next simulated spectrum.
void set_threshold (double new_value)
Procedure which allows to set the threshold useful for the procedure write_spectrum_peak_only and the scoring.
double get_threshold ()
Function to obtain the threshold.
int get_spectrum_size ()
Function which returns the size of the array that contains the spectrum.
double get_step ()
Function which returns the spectra array step (distance between two spectrum points).
char * get_spectrum_original_description ()
Function which returns the original description of the current spectrum.
char * get_spectrum_original_sequence ()
Function which returns the original sequence of the current spectrum.
void set_C_atom_quantity (int new_quantity)
Procedure which allows to modify the quantity of C atom for the initialisation process.
int get_atom_quantity (const char * symbol)
Tool function which returns the atom quantity linked to a symbol or -1 if the symbol has not an associated atom quantity.
void set_spectrum_maximum_mass (int new_value)
Procedure which allows to modify the spectrum maximum mass.
int get_spectrum_maximum_mass ()
Function which allows to get the maximum mass authorized for the spectrum.
void set_gaussian_value (double new_value)
Procedure which allows to modify the gaussian value.
double get_gaussian_value ()
Function which allows to get the gaussian value.
void set_precision (int new_value)
Procedure which allows to modify the spectrum precision.
int get_spectrum_precision ()
Function which allows to get the spetrum precision.
char * get_simulated_spectra_filename ()
Function which returns the name of file containing the simulated spectra.
char * get_experimental_filename ()
Function which returns the file name of the experimental spectrum.
int is_simulated_wanted_protein ()
Function which indicates if the current loaded protein corresponding to the specie.
void set_scoring_sensitivity (double new_value)
Procedure which allows to modify the score sensitivity.
double get_scoring_sensitivity ()
Function which returns the score sensitivity.
void set_minimum_mass (double new_value)
Procedure which allows to modify the minimum mass for the peptides.
double get_minimum_mass ()
Function which returns the minimum mass authorized for the peptides.
void set_maximum_mass (double new_value)
Procedure which allows to modify the maximum mass for the peptides.
double get_maximum_mass ()
Function which returns the maximum mass authorized for the peptides.
void set_peptide_maximum_mass (int new_value)
Procedure which allows to modify the peptide maximum mass.
void set_peptide_precision (int new_value)
Procedure which allows to modify the peptide precision.
int get_peptide_maximum_mass ()
Function which allows to get the peptide maximum mass.
int get_peptide_precision ()
Function which allows to get the peptide precision.
void set_minimum_peptide_number (unsigned int new_value)
Procedure which allows to modify the minimum peptide number needed to a protein to be considered.
unsigned int get_minimum_peptide_number ()
Function which allows to get the minimum peptide number for a protein to be considered.
void set_minimum_matched_peptide_number (unsigned int new_value)
Procedure which allows to modify the minimum matched peptide number needed to a protein to be considered.
unsigned int get_minimum_matched_peptide_number ()
Function which allows to get the minimum matched peptide number for a protein to be considered.
double compute_correlation (int index, complex_t *spectrum)
Function which gives the correlation between the two spectra (experimental and simulated) according to an index on a peptide (global = FALSE) or on the complete spectrum (global = TRUE).
double penalization_factor ()
Function which gives a penalize factor corresponding to all the no need data from the simulated spectrum.
double get_peptide_score_threshold ()
Function which allows to get the peptide score threshold to make difference between `good` and `bad` peptides.
int get_distribution_activation ()
double * get_current_peptide_score_save ()
Function which allows to get the peptide scores of the last protein considered.
unsigned int get_current_peptide_score_size ()
Function which allows to get the peptide score array size of the last protein considered.
Detailed Description
Definition of the methods to make simulated spectrum computation.
Author
Nicolas GRUSZCZYNSKA and Nicolas DOLET (2005).
 Modified and updated by Jean-Charles BOISSON and Christian ROLANDO (2005-2008).
Warning
Copyright USTL
 This software is governed by the CeCILL-C license under French law and abiding by the rules of distribution of free software.
Function Documentation
compute_correlation()
double compute_correlation (int index, complex_t * spectrum)
Function which gives the correlation between the two spectra (experimental and simulated) according to an index on a peptide (global = FALSE) or on the complete spectrum (global = TRUE).
Parameters
index The index.
spectrum The spectrum to compare with the experimental spectrum.
Returns
The correlation score between the two points.
Definition at line 2315 of file isodistrib.cpp.
References N_SPEC, complex::Re, t_exp_spec, threshold, and variation_threshold.
Referenced by fprintf_ascq_me_results_table_form(), and optimized_isotopic_distribution().
copy_spectrum()
 complex_t * copy_spectrum (complex_t * spectrum)
Function which makes the copie of a spectrum.
Parameters
spectrum The spectrum to copy.
Returns
The copie.
Definition at line 1741 of file isodistrib.cpp.
References error(), complex::Im, MEMORY_ALLOCATION_ERROR, N_SPEC, complex::Re, and USAGE_ERROR.
Referenced by add_protein().
element_convolution()
void element_convolution (composition_t * comp)
Procedure which makes the convolution for one atom.
Parameters
comp The composition containing the atom and its quantity.
free_isodistrib()
void free_isodistrib ()
Procedure which frees the memory allocated for all the structures useful for the isotopic distribution computation.
Definition at line 1651 of file isodistrib.cpp.
References C_atom, C_atom_quantity, current_peptide_score_save, current_peptide_score_size, experimental_file, gauss, H_atom, H_atom_quantity, ip, N_atom, N_atom_quantity, O_atom, O_atom_quantity, result, S_atom, S_atom_quantity, Se_atom, Se_atom_quantity, simulated_spectra_file, spectrum_original_description, spectrum_original_sequence, t_atom, t_C_atom, t_exp_spec, t_H_atom, t_N_atom, t_O_atom, t_peptide, t_S_atom, t_Se_atom, t_shifted_peptide, and w.
Referenced by ascq_me_configuration_cleaning().
get_atom_quantity()
int get_atom_quantity (const char * symbol)
Tool function which returns the atom quantity linked to a symbol or -1 if the symbol has not an associated atom quantity.
Parameters
symbol The symbol.
Returns
The associated atom quantity or -1.
Definition at line 1350 of file isodistrib.cpp.
References C_atom_quantity, H_atom_quantity, N_atom_quantity, O_atom_quantity, S_atom_quantity, Se_atom_quantity, and symbol.
Referenced by fprint_configuration(), fprint_configuration_xml(), optimized_isotopic_distribution(), and print_configuration().
get_current_peptide_score_save()
double * get_current_peptide_score_save ()
Function which allows to get the peptide scores of the last protein considered.
Warning
This function returns a direct pointer.
Definition at line 2425 of file isodistrib.cpp.
References current_peptide_score_save.
Referenced by main().
get_current_peptide_score_size()
unsigned int get_current_peptide_score_size ()
Function which allows to get the peptide score array size of the last protein considered.
Definition at line 2431 of file isodistrib.cpp.
References current_peptide_score_size.
Referenced by main().
get_distribution_activation()
int get_distribution_activation ()
Definition at line 2419 of file isodistrib.cpp.
References is_distribution_initialised.
Referenced by load_configuration(), load_float_keyword(), and load_int_keyword().
get_exp_spectrum()
 complex_t * get_exp_spectrum ()
Function which allows to gain access to the experimental spectrum.
Returns
The experimental spectrum.
Definition at line 1735 of file isodistrib.cpp.
References t_exp_spec.
Referenced by fprintf_ascq_me_results_table_form().
get_experimental_filename()
char * get_experimental_filename ()
Function which returns the file name of the experimental spectrum.
Returns
The file name.
Definition at line 2176 of file isodistrib.cpp.
References experimental_file.
Referenced by fprint_configuration(), fprint_configuration_xml(), and print_configuration().
get_gaussian_value()
double get_gaussian_value ()
Function which allows to get the gaussian value.
Returns
The gaussian value.
Definition at line 2164 of file isodistrib.cpp.
References gaussian.
Referenced by fprint_configuration(), fprint_configuration_xml(), and print_configuration().
get_maximum_mass()
double get_maximum_mass ()
Function which returns the maximum mass authorized for the peptides.
Returns
The maximum mass.
Definition at line 2262 of file isodistrib.cpp.
References max_experimental_mass.
Referenced by fprint_configuration(), fprint_configuration_xml(), fprintf_ascq_me_results_table_form(), and print_configuration().
get_minimum_mass()
double get_minimum_mass ()
Function which returns the minimum mass authorized for the peptides.
Returns
The minimum mass.
Definition at line 2236 of file isodistrib.cpp.
References min_experimental_mass.
Referenced by fprint_configuration(), fprint_configuration_xml(), fprintf_ascq_me_results_table_form(), and print_configuration().
get_minimum_matched_peptide_number()
unsigned int get_minimum_matched_peptide_number ()
Function which allows to get the minimum matched peptide number for a protein to be considered.
Returns
The minimum matched peptide number.
Definition at line 2407 of file isodistrib.cpp.
References minimum_matched_peptide_number.
Referenced by fprint_configuration(), fprint_configuration_xml(), and print_configuration().
get_minimum_peptide_number()
unsigned int get_minimum_peptide_number ()
Function which allows to get the minimum peptide number for a protein to be considered.
Returns
The minimum peptide number.
Definition at line 2386 of file isodistrib.cpp.
References minimum_peptide_number.
Referenced by fprint_configuration(), fprint_configuration_xml(), and print_configuration().
get_peptide_maximum_mass()
int get_peptide_maximum_mass ()
Function which allows to get the peptide maximum mass.
Returns
The peptide maximum mass.
Definition at line 2303 of file isodistrib.cpp.
References peptide_maximum_mass.
Referenced by fprint_configuration(), fprint_configuration_xml(), and print_configuration().
get_peptide_precision()
int get_peptide_precision ()
Function which allows to get the peptide precision.
Returns
The peptide precision.
Definition at line 2309 of file isodistrib.cpp.
References peptide_precision.
Referenced by fprint_configuration(), fprint_configuration_xml(), and print_configuration().
get_peptide_score_threshold()
double get_peptide_score_threshold ()
Function which allows to get the peptide score threshold to make difference between `good` and `bad` peptides.
Returns
The peptide score threshold.
Definition at line 2413 of file isodistrib.cpp.
References peptide_score_threshold.
Referenced by fprintf_ascq_me_results().
get_scoring_sensitivity()
double get_scoring_sensitivity ()
Function which returns the score sensitivity.
Returns
The sensitivity.
Definition at line 2214 of file isodistrib.cpp.
References sensitivity.
Referenced by fprint_configuration(), fprint_configuration_xml(), and print_configuration().
get_simulated_spectra_filename()
char * get_simulated_spectra_filename ()
Function which returns the name of file containing the simulated spectra.
Returns
The file name.
Definition at line 2152 of file isodistrib.cpp.
References simulated_spectra_file.
Referenced by fprint_configuration(), fprint_configuration_xml(), and print_configuration().
get_spectrum_maximum_mass()
int get_spectrum_maximum_mass ()
Function which allows to get the maximum mass authorized for the spectrum.
Returns
The maximum mass.
Definition at line 2158 of file isodistrib.cpp.
References spectrum_maximum_mass.
Referenced by fprint_configuration(), fprint_configuration_xml(), and print_configuration().
get_spectrum_original_description()
char * get_spectrum_original_description ()
Function which returns the original description of the current spectrum.
Returns
The original description.
Definition at line 2050 of file isodistrib.cpp.
References spectrum_original_description.
Referenced by main().
get_spectrum_original_sequence()
char * get_spectrum_original_sequence ()
Function which returns the original sequence of the current spectrum.
Returns
The original sequence.
Definition at line 2056 of file isodistrib.cpp.
References spectrum_original_sequence.
Referenced by main().
get_spectrum_precision()
int get_spectrum_precision ()
Function which allows to get the spetrum precision.
Returns
The precision.
Definition at line 2170 of file isodistrib.cpp.
References N_SPEC.
Referenced by fprint_configuration(), fprint_configuration_xml(), and print_configuration().
get_spectrum_size()
int get_spectrum_size ()
Function which returns the size of the array that contains the spectrum.
Returns
The size.
Definition at line 2038 of file isodistrib.cpp.
References N_SPEC.
get_step()
double get_step ()
Function which returns the spectra array step (distance between two spectrum points).
Returns
The step.
Definition at line 2044 of file isodistrib.cpp.
References step.
Referenced by fprintf_ascq_me_results_table_form().
get_theo_spectrum()
 complex_t * get_theo_spectrum ()
Function which allows to gain access to the simulated spectrum.
Returns
The theoretical spectrum.
Definition at line 2020 of file isodistrib.cpp.
References result.
Referenced by main().
get_threshold()
double get_threshold ()
Function to obtain the threshold.
Returns
The threshold.
Definition at line 2032 of file isodistrib.cpp.
References threshold.
Referenced by fprint_configuration(), fprint_configuration_xml(), and print_configuration().
init_distrib()
void init_distrib ()
Procedure which initializes the parameters and allocates the useful structures.
Definition at line 336 of file isodistrib.cpp.
References atom_nb_data_amu, atom_step, C_atom, C_atom_quantity, cdft(), complex_multiplication(), formula::comps, composition::element, error(), free_formula(), gauss, gauss_param, gaussian, get_element_table(), get_element_table_size(), H_atom, H_atom_quantity, complex::Im, ip, is_distribution_initialised, is_verbose_mode_activated(), isotop::isotopic_composition, element::isotops, MEMORY_ALLOCATION_ERROR, N_atom, N_atom_quantity, N_PEPT, N_SPEC, nb_data_amu, element::nb_isotops, O_atom, O_atom_quantity, peptide_maximum_mass, peptide_precision, complex::Re, read_formula(), isotop::relative_mass, result, S_atom, S_atom_quantity, Se_atom, Se_atom_quantity, spectrum_maximum_mass, step, t_atom, t_C_atom, t_exp_spec, t_H_atom, t_N_atom, t_O_atom, t_peptide, t_S_atom, t_Se_atom, t_shifted_peptide, TRUE, and w.
Referenced by load_string_keyword().
integral_normalization()
void integral_normalization (double integral_value, int size, complex_t * t_complex)
Procedure which makes a normalization of a data array.
Parameters
integral_value The used integral value.
size The t_complex structure size.
t_complex The data to normalize.
Definition at line 1449 of file isodistrib.cpp.
References complex::Re.
Referenced by optimized_isotopic_distribution(), and read_spectrum().
is_simulated_wanted_protein()
int is_simulated_wanted_protein ()
Function which indicates if the current loaded protein corresponding to the specie.
Returns
TRUE or FALSE (see util.h).
Definition at line 2182 of file isodistrib.cpp.
References error(), get_specie(), spectrum_original_description, TRUE, and USAGE_ERROR.
Referenced by main().
next_simulated_spectrum()
int next_simulated_spectrum ()
Function which loads the next simulated spectrum.
Warning
This function must be called after read_simulated_spectrum, not before.
Returns
TRUE or FALSE, Does a protein have been loaded ?
Definition at line 1813 of file isodistrib.cpp.
References error(), FALSE, complex::Im, IO_ERROR, MEMORY_ALLOCATION_ERROR, N_SPEC, complex::Re, result, simulated_spectra, spectrum_original_description, spectrum_original_sequence, step, TRUE, and USAGE_ERROR.
Referenced by main().
optimized_isotopic_distribution()
double optimized_isotopic_distribution (formula_t * peptides, int nb_peptides)
Function which calculates the isotopic distribution of a peptide list.
Parameters
peptides The peptide list.
nb_peptides The peptide number.
Returns
The total score of the protein corresponding to the peptide list.
!!! The 2 last mass are thought to belong the main isotopic peak !!!!
!!! The 2 last mass are thought to belong the main isotopic peak !!!!
Definition at line 1029 of file isodistrib.cpp.
References atom_step, cdft(), complex_multiplication(), compute_correlation(), copy_composition(), current_peptide_score_save, current_peptide_score_size, composition::element, error(), EXECUTION_ERROR, free_composition(), gauss, get_atom_quantity(), get_t_X_atom(), get_weight(), get_X_atom(), complex::Im, integral_normalization(), ip, is_equivalent_to_another(), is_verbose_mode_activated(), isotop::isotopic_composition, element::isotops, max_experimental_mass, MEMORY_ALLOCATION_ERROR, min_experimental_mass, minimum_matched_peptide_number, minimum_peptide_number, N_PEPT, N_SPEC, nb_data_amu, element::nb_isotops, peptide_maximum_mass, peptide_precision, peptide_score_threshold, peptides, composition::quantity, complex::Re, isotop::relative_mass, result, step, element::symbol, t_atom, t_peptide, t_shifted_peptide, threshold, TRUE, and w.
Referenced by main().
penalization_factor()
double penalization_factor ()
Function which gives a penalize factor corresponding to all the no need data from the simulated spectrum.
Returns
The penalization score.
Definition at line 2351 of file isodistrib.cpp.
References max_experimental_mass, min_experimental_mass, complex::Re, result, step, t_exp_spec, threshold, and variation_threshold.
read_simulated_spectrum()
void read_simulated_spectrum (const char * spectrum_file)
Procedure which allows to open the file which contains theoretical spectra.
Warning
This procedure opens only the file and don't load any data.
Parameters
spectrum_file The name of the file which contains simulated spectra.
Definition at line 1795 of file isodistrib.cpp.
References error(), IO_ERROR, MEMORY_ALLOCATION_ERROR, simulated_spectra, and simulated_spectra_file.
Referenced by load_string_keyword().
read_spectrum()
void read_spectrum (const char * spectrum_file)
Procedure which loads a spectrum from a file.
Parameters
spectrum_file The spectrum file.
Definition at line 1514 of file isodistrib.cpp.
References error(), experimental_file, FALSE, complex::Im, integral_normalization(), IO_ERROR, is_verbose_mode_activated(), jump_commentaries(), max_experimental_mass, MEMORY_ALLOCATION_ERROR, min_experimental_mass, N_SPEC, complex::Re, step, t_exp_spec, TRUE, USAGE_ERROR, variation_threshold, and WARNING.
Referenced by load_string_keyword().
set_C_atom_quantity()
void set_C_atom_quantity (int new_quantity)
Procedure which allows to modify the quantity of C atom for the initialisation process.
Warning
The call to this procedure will change the H, O, N and S quantities with the corresponding factor *4, /4, /2 and /8.
 The call is refused if the distribution has already been initialised.
Parameters
new_quantity The new atom C quantity.
Definition at line 2062 of file isodistrib.cpp.
References C_atom, C_atom_quantity, error(), H_atom_quantity, N_atom_quantity, O_atom_quantity, S_atom_quantity, Se_atom_quantity, and USAGE_ERROR.
Referenced by load_int_keyword().
set_exp_spectrum()
void set_exp_spectrum (complex_t * spectrum)
Procedure which allows to set manually the experimental spectrum.
Parameters
spectrum The experimental spectrum.
Definition at line 1765 of file isodistrib.cpp.
References error(), complex::Im, N_SPEC, complex::Re, t_exp_spec, and USAGE_ERROR.
set_gaussian_value()
void set_gaussian_value (double new_value)
Procedure which allows to modify the gaussian value.
Warning
The call is refused if the procedure init_distrib has been already used.
Parameters
new_value The new gaussian value.
Definition at line 2120 of file isodistrib.cpp.
References error(), gaussian, N_PEPT, and USAGE_ERROR.
Referenced by load_float_keyword().
set_maximum_mass()
void set_maximum_mass (double new_value)
Procedure which allows to modify the maximum mass for the peptides.
Warning
The call is refused if the procedure init_distrib has been already used.
Parameters
new_value The new maximum mass.
Definition at line 2242 of file isodistrib.cpp.
References error(), max_experimental_mass, N_PEPT, spectrum_maximum_mass, and USAGE_ERROR.
Referenced by load_float_keyword().
set_minimum_mass()
void set_minimum_mass (double new_value)
Procedure which allows to modify the minimum mass for the peptides.
Warning
The call is refused if the procedure init_distrib has been already used.
Parameters
new_value The new minimum mass.
Definition at line 2220 of file isodistrib.cpp.
References error(), min_experimental_mass, N_PEPT, and USAGE_ERROR.
Referenced by load_float_keyword().
set_minimum_matched_peptide_number()
void set_minimum_matched_peptide_number (unsigned int new_value)
Procedure which allows to modify the minimum matched peptide number needed to a protein to be considered.
Warning
The call is refused if the procedure is_parsing_started (see seqio.h/.cpp) return TRUE.
Parameters
new_value The new minimum matched peptide number.
Definition at line 2392 of file isodistrib.cpp.
References error(), is_parsing_started(), minimum_matched_peptide_number, TRUE, and WARNING.
Referenced by load_unsigned_int_keyword().
set_minimum_peptide_number()
void set_minimum_peptide_number (unsigned int new_value)
Procedure which allows to modify the minimum peptide number needed to a protein to be considered.
Warning
The call is refused if the procedure is_parsing_started (see seqio.h/.cpp) return TRUE.
Parameters
new_value The new minimum peptide number.
Definition at line 2371 of file isodistrib.cpp.
References error(), is_parsing_started(), minimum_peptide_number, TRUE, and WARNING.
Referenced by load_unsigned_int_keyword().
set_peptide_maximum_mass()
void set_peptide_maximum_mass (int new_value)
Procedure which allows to modify the peptide maximum mass.
Warning
The call is refused if the procedure init_distrib has been already used.
Parameters
new_value The new peptide maximum mass.
Definition at line 2268 of file isodistrib.cpp.
References error(), N_PEPT, peptide_maximum_mass, and USAGE_ERROR.
Referenced by load_int_keyword().
set_peptide_precision()
void set_peptide_precision (int new_value)
Procedure which allows to modify the peptide precision.
Warning
The call is refused if the procedure init_distrib has been already used.
Parameters
new_value The new peptide precision.
Definition at line 2284 of file isodistrib.cpp.
References error(), N_PEPT, peptide_precision, USAGE_ERROR, and WARNING.
Referenced by load_int_keyword().
set_precision()
void set_precision (int new_value)
Procedure which allows to modify the spectrum precision.
Warning
The call is refused if the procedure init_distrib has been already used.
Parameters
new_value The new precision.
Definition at line 2136 of file isodistrib.cpp.
References error(), N_PEPT, N_SPEC, and USAGE_ERROR.
Referenced by load_int_keyword().
set_scoring_sensitivity()
void set_scoring_sensitivity (double new_value)
Procedure which allows to modify the score sensitivity.
Warning
The call is refused if the procedure init_distrib has been already used.
Parameters
new_value The new sensitivity.
Definition at line 2198 of file isodistrib.cpp.
References error(), N_PEPT, sensitivity, and USAGE_ERROR.
Referenced by load_float_keyword().
set_spectrum_maximum_mass()
void set_spectrum_maximum_mass (int new_value)
Procedure which allows to modify the spectrum maximum mass.
Warning
The call is refused if the procedure init_distrib has been already used.
Parameters
new_value The new maximum mass.
Definition at line 2104 of file isodistrib.cpp.
References error(), N_PEPT, spectrum_maximum_mass, and USAGE_ERROR.
Referenced by load_int_keyword().
set_threshold()
void set_threshold (double new_value)
Procedure which allows to set the threshold useful for the procedure write_spectrum_peak_only and the scoring.
Parameters
new_value The new value.
Definition at line 2026 of file isodistrib.cpp.
References threshold.
Referenced by load_float_keyword().
write_spectrum()
void write_spectrum (FILE * f, complex_t * t_complex, char * entry)
Procedure which writes a spectrum in a file.
Parameters
f The file where the spectrum will be write.
t_complex The spectrum to save.
entry The spectrum name.
Definition at line 1502 of file isodistrib.cpp.
References N_SPEC, and step.
write_spectrum_peak_only()
void write_spectrum_peak_only (FILE * file, complex_t * spectrum, char * name)
Procedure which writes only the spectrum peaks in a file.
Parameters
file The file where the spectrum will be save.
spectrum The spectrum.
name The spectrum name.
Definition at line 1781 of file isodistrib.cpp.
References N_SPEC, step, and threshold.