modifications_for_digestion.cpp File Reference
Implementation of the methods defined in modifications_for_digestion.h.
#include `modifications_for_digestion.h`
Functions
void print_modification_configuration ()
Procedure which prints the current configuration of activated modifications on the stdout.
void fprint_modification_configuration (FILE *file)
Procedure which prints the current configuration of activated modifications in a file.
void fprint_xml_modification_configuration (FILE *file)
Procedure which prints the current configuration of activated modifications in a file in a XML format.
void load_modification_configuration (char *configuration)
Procedure which loads the configuration for the modifications.
void add_modification (int type, int id)
Procedure which allows to activate a new modification.
void free_activated_modification ()
Procedure which allows to free all the initialised modifications.
int get_number_of_activated_modifications ()
Function which returns the number of activated modifications.
int can_be_used_on_for_digestion (int modif, char amino_acid, int place, int size, int first)
Function which indicates if the given amino acid can have the indicated modification.
 formula_t * get_formula_to_add (int modif)
Function which returns the formula to add according to the indicated modification.
 formula_t * get_formula_to_sub (int modif)
Function which returns the formula to sub according the indicated modification.
int get_modification_type (int modif)
Function which returns the type of modification according the given index.
void apply_modification (formula_t * formula, int modif)
Procedure which applies a modification on a formula.
char * get_activated_modification_symbol (int modif)
Function which returns the small name (symbol) of a modification.
char * get_activated_modification_name (int modif)
Function which returns the full name of a modification.
void digestion_modification_initialization (const char *configuration)
Procedure that allows to initialize all the post translational modifications for the digestion.
int get_global_modification_index (int modif)
Function which returns the global index of the modification.
Variables
int nb_modifications =0
The total number of activated modifications.
 post_translational_modification_t * modifications =NULL
The activated post-translational modifications.
Detailed Description
Implementation of the methods defined in modifications_for_digestion.h.
Author
Jean-Charles BOISSON (2006-2008).
Warning
Copyright USTL
 This software is governed by the CeCILL-C license under French law and abiding by the rules of distribution of free software.
Function Documentation
add_modification()
void add_modification (int type, int id)
Procedure which allows to activate a new modification.
Parameters
type It can be FIXED or VARIABLE.
id The modification index (see modification_table.h).
Definition at line 187 of file modifications_for_digestion.cpp.
References error(), FALSE, FIXED, get_total_number_of_modifications(), MEMORY_ALLOCATION_ERROR, post_traductional_modification::modification, modifications, nb_modifications, TRUE, post_traductional_modification::type, USAGE_ERROR, and VARIABLE.
Referenced by digestion_modification_initialization(), and load_modification_configuration().
apply_modification()
void apply_modification (formula_t * formula, int modif)
Procedure which applies a modification on a formula.
Parameters
formula The formula where the modification have to be applied.
modif The modification index.
Definition at line 330 of file modifications_for_digestion.cpp.
References add_formula(), error(), EXECUTION_ERROR, FALSE, get_formula_to_add(), get_formula_to_sub(), nb_modifications, sub_formula(), and USAGE_ERROR.
Referenced by get_formulae_of_peptides(), get_peptide_formula_from_another_protein(), and get_peptide_formula_from_index().
can_be_used_on_for_digestion()
int can_be_used_on_for_digestion (int modif, char amino_acid, int place, int size, int first)
Function which indicates if the given amino acid can have the indicated modification.
Parameters
modif The chosen modification index.
amino_acid An amino acid.
place Its place.
size The size of the protein/peptide.
first The last parameter indicates if the amino acid is the first of the complete protein or the first peptide.
Warning
The first place <=> N-term, the last one <=> C-term.
Returns
TRUE or FALSE (see util.h).
Definition at line 266 of file modifications_for_digestion.cpp.
References can_be_used_on(), error(), modifications, nb_modifications, and USAGE_ERROR.
Referenced by compute_post_traductional_modifications_one_peptide().
digestion_modification_initialization()
void digestion_modification_initialization (const char * configuration)
Procedure that allows to initialize all the post translational modifications for the digestion.
Parameters
configuration The modification configuration.
Definition at line 381 of file modifications_for_digestion.cpp.
References add_modification(), error(), FALSE, FIXED, MEMORY_ALLOCATION_ERROR, USAGE_ERROR, and VARIABLE.
fprint_modification_configuration()
void fprint_modification_configuration (FILE * file)
Procedure which prints the current configuration of activated modifications in a file.
Parameters
file The file where we want to print the configuration.
Definition at line 75 of file modifications_for_digestion.cpp.
References FIXED, get_modification_name(), modifications, and nb_modifications.
Referenced by fprint_configuration().
fprint_xml_modification_configuration()
void fprint_xml_modification_configuration (FILE * file)
Procedure which prints the current configuration of activated modifications in a file in a XML format.
Parameters
file The file where we want to print the configuration.
Definition at line 87 of file modifications_for_digestion.cpp.
References FIXED, get_modification_name(), modifications, and nb_modifications.
Referenced by fprint_configuration_xml().
free_activated_modification()
void free_activated_modification ()
Procedure which allows to free all the initialised modifications.
Definition at line 251 of file modifications_for_digestion.cpp.
References modifications, and nb_modifications.
Referenced by ascq_me_configuration_cleaning().
get_activated_modification_name()
char* get_activated_modification_name (int modif)
Function which returns the full name of a modification.
Parameters
modif The modification index.
Definition at line 370 of file modifications_for_digestion.cpp.
References error(), get_modification_name(), modifications, nb_modifications, and USAGE_ERROR.
get_activated_modification_symbol()
char* get_activated_modification_symbol (int modif)
Function which returns the small name (symbol) of a modification.
Parameters
modif The modification index.
Definition at line 359 of file modifications_for_digestion.cpp.
References error(), get_modification_symbol(), modifications, nb_modifications, and USAGE_ERROR.
Referenced by fprint_peptide(), get_peptide_sequence(), and print_peptide().
get_formula_to_add()
 formula_t* get_formula_to_add (int modif)
Function which returns the formula to add according to the indicated modification.
Parameters
modif The modification index.
Returns
The formula.
Warning
The result can be NULL if no formula is needed to add to apply the modification.
Definition at line 277 of file modifications_for_digestion.cpp.
References error(), get_modification_formula_to_add(), modifications, formula::nb_comp, nb_modifications, and USAGE_ERROR.
Referenced by add_peptide_modification(), and apply_modification().
get_formula_to_sub()
 formula_t* get_formula_to_sub (int modif)
Function which returns the formula to sub according the indicated modification.
Parameters
modif The modification index.
Returns
The formula.
Warning
The result can be NULL if no formula is needed to sub to apply the modification.
Definition at line 298 of file modifications_for_digestion.cpp.
References error(), get_modification_formula_to_sub(), modifications, formula::nb_comp, nb_modifications, and USAGE_ERROR.
Referenced by add_peptide_modification(), and apply_modification().
get_global_modification_index()
int get_global_modification_index (int modif)
Function which returns the global index of the modification.
Parameters
modif The index for the digestion modification.
Returns
The global index in order to use the functions of the modification table.
Definition at line 469 of file modifications_for_digestion.cpp.
References error(), post_traductional_modification::modification, modifications, nb_modifications, and USAGE_ERROR.
get_modification_type()
int get_modification_type (int modif)
Function which returns the type of modification according the given index.
Parameters
modif The modification index.
Returns
The corresponding type.
Definition at line 319 of file modifications_for_digestion.cpp.
References error(), modifications, nb_modifications, post_traductional_modification::type, and USAGE_ERROR.
Referenced by compute_post_traductional_modifications_one_peptide().
get_number_of_activated_modifications()
int get_number_of_activated_modifications ()
Function which returns the number of activated modifications.
Returns
The number of activated modifications.
Definition at line 260 of file modifications_for_digestion.cpp.
References nb_modifications.
Referenced by add_peptide_modification(), compute_post_traductional_modifications_one_peptide(), fprint_configuration(), fprint_configuration_xml(), print_configuration(), and real_digest().
load_modification_configuration()
void load_modification_configuration (char * configuration)
Procedure which loads the configuration for the modifications.
Parameters
configuration The current configuration to load.
Definition at line 99 of file modifications_for_digestion.cpp.
References add_modification(), error(), FALSE, FIXED, MEMORY_ALLOCATION_ERROR, USAGE_ERROR, and VARIABLE.
Referenced by load_string_keyword().
print_modification_configuration()
void print_modification_configuration ()
Procedure which prints the current configuration of activated modifications on the stdout.
Definition at line 63 of file modifications_for_digestion.cpp.
References FIXED, get_modification_name(), modifications, and nb_modifications.
Referenced by print_configuration().
Variable Documentation
modifications
 post_translational_modification_t * modifications =NULL
The activated post-translational modifications.
Definition at line 59 of file modifications_for_digestion.cpp.
Referenced by add_modification(), can_be_used_on_for_digestion(), fprint_modification_configuration(), fprint_xml_modification_configuration(), free_activated_modification(), get_activated_modification_name(), get_activated_modification_symbol(), get_formula_to_add(), get_formula_to_sub(), get_formulae_of_peptides(), get_global_modification_index(), get_modification_type(), get_peptide_formula_from_index(), get_peptide_sequence(), and print_modification_configuration().
nb_modifications
int nb_modifications =0
The total number of activated modifications.
Definition at line 54 of file modifications_for_digestion.cpp.
Referenced by add_modification(), apply_modification(), can_be_used_on_for_digestion(), compute_post_traductional_modifications_one_peptide(), fprint_modification_configuration(), fprint_xml_modification_configuration(), free_activated_modification(), get_activated_modification_name(), get_activated_modification_symbol(), get_formula_to_add(), get_formula_to_sub(), get_global_modification_index(), get_modification_type(), get_number_of_activated_modifications(), and print_modification_configuration().