modification_table.cpp File Reference
Implementation of the methods defined in modification_table.h.
#include `modification_table.h`
Functions
void free_all_modifications ()
Procedure which allows to free the modification formulae.
 formula_t * get_modification_formula_to_add (int modif)
Function which returns the formula to add when we want to apply a wanted modification.
 formula_t * get_modification_formula_to_sub (int modif)
Function which returns the formula to sub when we want to apply a wanted modification.
char * get_modification_symbol (int modif)
Function which allows to get the corresponding symbol according a wanted modification.
char * get_modification_amino_acids (int modif)
Function which allows to return all the amino acids on which this modification can be used.
int get_total_number_of_modifications ()
Function which allows to get the total number of available modifications.
char * get_modification_name (int modif)
Function which allows to get the complete name of a modification.
int get_modification_side (int modif)
Function which returns the side corresponding to the modification.
int can_be_used_on (int modif, char amino_acid, int place, int size, int first)
Function which indicates if the amino acid given can have the indicated modification.
void load_modifications (const char *file)
Procedure which loads the available modifications from a file.
void apply_global_modification (formula_t * formula, int modif)
Procedure which applies a modification on a formula.
Variables
int nb_total_modif =0
The total number of modifications.
char ** modifications_name =NULL
The names of all modifications.
char ** symbol =NULL
The symbols of all modifications.
int * side =NULL
The application side of each modifications.
char ** modifications_on_amino_acids =NULL
The amino acids where the modifications can be put.
 formula_t * formula_to_add =NULL
For each modification, formula to add to apply it.
 formula_t * formula_to_sub =NULL
For each modification, formula to sub to apply it.
Detailed Description
Implementation of the methods defined in modification_table.h.
Author
Jean-Charles BOISSON (2006-2008).
Warning
Copyright USTL
 This software is governed by the CeCILL-C license under French law and abiding by the rules of distribution of free software.
Function Documentation
apply_global_modification()
void apply_global_modification (formula_t * formula, int modif)
Procedure which applies a modification on a formula.
Parameters
formula The formula to modify.
modif The index of the modif to apply.
Definition at line 587 of file modification_table.cpp.
References add_formula(), error(), EXECUTION_ERROR, FALSE, formula_to_add, formula_to_sub, nb_total_modif, sub_formula(), and USAGE_ERROR.
can_be_used_on()
int can_be_used_on (int modif, char amino_acid, int place, int size, int first)
Function which indicates if the amino acid given can have the indicated modification.
Parameters
modif The chosen modification.
amino_acid The amino acid
place Its place
size The size of the protein/peptide.
first This parameters indicates if the amino acid is an amino acid of a complete protein or the amino acid of the first peptide.
Warning
The first place <=> N-term, the last <=> C-term.
Returns
TRUE or FALSE (see util.h).
Definition at line 193 of file modification_table.cpp.
References BOTH_TERM, C_TERM, error(), FALSE, INDEPENDANT_TERM, modifications_on_amino_acids, N_TERM, nb_total_modif, PROTEIN, side, TRUE, and USAGE_ERROR.
Referenced by can_be_used_on_for_digestion().
free_all_modifications()
void free_all_modifications ()
Procedure which allows to free the modification formulae.
Definition at line 87 of file modification_table.cpp.
References formula_to_add, formula_to_sub, free_composition(), modifications_name, modifications_on_amino_acids, nb_total_modif, side, and symbol.
Referenced by ascq_me_configuration_cleaning().
get_modification_amino_acids()
char* get_modification_amino_acids (int modif)
Function which allows to return all the amino acids on which this modification can be used.
Parameters
modif The wanted modification.
Returns
The amino acids.
Definition at line 154 of file modification_table.cpp.
References error(), modifications_on_amino_acids, nb_total_modif, and USAGE_ERROR.
get_modification_formula_to_add()
 formula_t* get_modification_formula_to_add (int modif)
Function which returns the formula to add when we want to apply a wanted modification.
Parameters
modif The wanted modification.
Returns
The formula to add to apply the modification.
Warning
This function return directly a pointer on the formula, so do not modify it, if you want this formula and make modification on it, call copy_formula(get_modification_formula_to_add(modif)) in order to have a copy.
Definition at line 120 of file modification_table.cpp.
References error(), formula_to_add, nb_total_modif, and USAGE_ERROR.
Referenced by get_formula_to_add().
get_modification_formula_to_sub()
 formula_t* get_modification_formula_to_sub (int modif)
Function which returns the formula to sub when we want to apply a wanted modification.
Parameters
modif The wanted modification.
Returns
The formula to sub to apply the modification.
Warning
This function return directly a pointer on the formula, so do not modify it, if you want this formula and make modification on it, call copy_formula(get_modification_formula_to_sub(modif)) in order to have a copy.
Definition at line 132 of file modification_table.cpp.
References error(), formula_to_sub, nb_total_modif, and USAGE_ERROR.
Referenced by get_formula_to_sub().
get_modification_name()
char* get_modification_name (int modif)
Function which allows to get the complete name of a modification.
Parameters
modif The wanted modification.
Returns
The modification complete name.
Definition at line 171 of file modification_table.cpp.
References error(), modifications_name, nb_total_modif, and USAGE_ERROR.
Referenced by fprint_modification_configuration(), fprint_xml_modification_configuration(), get_activated_modification_name(), and print_modification_configuration().
get_modification_side()
int get_modification_side (int modif)
Function which returns the side corresponding to the modification.
Parameters
modif The wanted modif.
Returns
The corresponding side.
Definition at line 182 of file modification_table.cpp.
References error(), nb_total_modif, side, and USAGE_ERROR.
get_modification_symbol()
char* get_modification_symbol (int modif)
Function which allows to get the corresponding symbol according a wanted modification.
Parameters
modif The wanted modification.
Returns
The corresponding char*
Definition at line 143 of file modification_table.cpp.
References error(), nb_total_modif, symbol, and USAGE_ERROR.
Referenced by get_activated_modification_symbol().
get_total_number_of_modifications()
int get_total_number_of_modifications ()
Function which allows to get the total number of available modifications.
Returns
the modification number.
Definition at line 165 of file modification_table.cpp.
References nb_total_modif.
Referenced by add_modification().
load_modifications()
void load_modifications (const char * file)
Procedure which loads the available modifications from a file.
Parameters
file The file for the loading.
Definition at line 273 of file modification_table.cpp.
References BOTH_TERM, C_TERM, formula::comps, error(), formula_to_add, formula_to_sub, get_element_table(), get_element_table_size(), INDEPENDANT_TERM, IO_ERROR, jump_a_line(), jump_commentaries(), MEMORY_ALLOCATION_ERROR, modifications_name, modifications_on_amino_acids, N_TERM, formula::nb_comp, nb_total_modif, PROTEIN, read_formula(), read_until(), side, symbol, and USAGE_ERROR.
Referenced by load_configuration().
Variable Documentation
formula_to_add
 formula_t * formula_to_add =NULL
For each modification, formula to add to apply it.
Definition at line 79 of file modification_table.cpp.
Referenced by apply_global_modification(), free_all_modifications(), get_modification_formula_to_add(), and load_modifications().
formula_to_sub
 formula_t * formula_to_sub =NULL
For each modification, formula to sub to apply it.
Definition at line 84 of file modification_table.cpp.
Referenced by apply_global_modification(), free_all_modifications(), get_modification_formula_to_sub(), and load_modifications().
modifications_name
char ** modifications_name =NULL
The names of all modifications.
Definition at line 59 of file modification_table.cpp.
Referenced by free_all_modifications(), get_modification_name(), and load_modifications().
modifications_on_amino_acids
char ** modifications_on_amino_acids =NULL
The amino acids where the modifications can be put.
Definition at line 74 of file modification_table.cpp.
Referenced by can_be_used_on(), free_all_modifications(), get_modification_amino_acids(), and load_modifications().
nb_total_modif
int nb_total_modif =0
The total number of modifications.
Definition at line 54 of file modification_table.cpp.
Referenced by apply_global_modification(), can_be_used_on(), free_all_modifications(), get_modification_amino_acids(), get_modification_formula_to_add(), get_modification_formula_to_sub(), get_modification_name(), get_modification_side(), get_modification_symbol(), get_total_number_of_modifications(), and load_modifications().
side
int * side =NULL
The application side of each modifications.
Definition at line 69 of file modification_table.cpp.
Referenced by can_be_used_on(), free_all_modifications(), get_modification_side(), and load_modifications().
symbol
char ** symbol =NULL
The symbols of all modifications.
Definition at line 64 of file modification_table.cpp.
Referenced by affect_atom(), fprint_element_table(), free_all_modifications(), get_atom_quantity(), get_element(), get_element_table(), get_modification_symbol(), get_t_X_atom(), get_X_atom(), load_modifications(), and print_element_table().