seqio.cpp File Reference
Implementation of the methods defined in seqio.h.
#include `seqio.h`
Macros
#define MALLOC_STEP_SEQ 10000
Standard size of allocation.
Functions
char * getSeq ()
Function which returns the sequence of the current protein in the FASTA file.
char * get_reversed_sequence ()
Function which returns the reverse of the current protein sequence.
char * getDesc ()
Function which returns the description of the current protein in the FASTA file.
unsigned int is_parsing_started ()
Function that indicates if the parsing of the database is started or not i.e. nextEntry has been called at least one time.
int nextEntry (long *offset)
Function which allows to move until the next entry.
void fastafclose ()
Function to close the FASTA file currently opened.
void fastafopen (const char *filename, long *size)
Function which opens a FASTA file.
void fastafwrite (FILE *f, char *desc, char *seq)
Procedure which writes in a file the description and the sequence of a protein.
void fastafwrite_way (FILE *f, char *desc, char *seq, int way)
Procedure which writes in a file the description and the sequence of a protein in a reading phase particulary.
int getEntry (long *offset)
Function to position the cursor on the nearest entry from the offset position.
void set_specie (const char *wanted_specie)
Procedure which allows to specifie the wanted specie to study.
int is_a_wanted_protein ()
Function which indicates if the current protein is wanted or not.
char * get_fasta_filename ()
Function which allows to get the name of the opened file.
char * get_specie ()
Function which allows to get the current specie wanted from the fasta file.
void set_exp_protein_mass (double mass)
Procedure to set a for the experimental protein mass.
double get_exp_protein_mass ()
Function which allows to get the mass given for the protein mass.
int is_exp_protein_mass_activated ()
Function which allows to know if a experimental protein mass has been already set.
Variables
char * SeqBuffer =NULL
Variable that corresponds to the buffer holding the current protein sequence.
char * DescBuffer =NULL
Variable that corresponds to the buffer holding the current protein description.
FILE * DbFile =NULL
Variable that corresponds to the opened FASTA file.
long Offset = (long) 0
Variable that corresponds to the offset in the FASTA file.
char * specie =NULL
Variable that corresponds to the wanted specie.
char * fasta_file_name =NULL
Variable that corresponds to the name of the opened FASTA file.
double protein_mass =0.0
Variable that corresponds to the experimental protein mass.
int protein_mass_given = FALSE
Variable that indicates if the a experimental protein mass has been given.
double mass_tolerance =10.0
Variable that indicates the according tolerance around the experimental protein mass.
unsigned parsing_is_started = FALSE
Variable that indicates if the parsing of the database has started or not.
Detailed Description
Implementation of the methods defined in seqio.h.
Author
Pierre LAURENCE and David BOENS for ASCQ-PROT (2003).
 Modified and updated by Jean-Charles BOISSON (2005-2008).
Warning
Copyright USTL
 This software is governed by the CeCILL-C license under French law and abiding by the rules of distribution of free software.
Macro Definition Documentation
MALLOC_STEP_SEQ
#define MALLOC_STEP_SEQ 10000
Standard size of allocation.
Definition at line 56 of file seqio.cpp.
Function Documentation
fastafclose()
void fastafclose ()
Function to close the FASTA file currently opened.
Definition at line 265 of file seqio.cpp.
References DbFile, DescBuffer, fasta_file_name, SeqBuffer, and specie.
Referenced by ascq_me_configuration_cleaning().
fastafopen()
void fastafopen (const char * filename, long * size)
Function which opens a FASTA file.
Parameters
filename The name of the file to open.
size The variable what will contain the FASTA file size.
Definition at line 295 of file seqio.cpp.
References DbFile, error(), fasta_file_name, IO_ERROR, MEMORY_ALLOCATION_ERROR, and Offset.
Referenced by load_string_keyword().
fastafwrite()
void fastafwrite (FILE * f, char * desc, char * seq)
Procedure which writes in a file the description and the sequence of a protein.
Parameters
f The file where the result will be write.
desc The protein description.
seq The protein sequence.
Definition at line 321 of file seqio.cpp.
References error(), and MEMORY_ALLOCATION_ERROR.
fastafwrite_way()
void fastafwrite_way (FILE * f, char * desc, char * seq, int way)
Procedure which writes in a file the description and the sequence of a protein in a reading phase particulary.
Parameters
f The file where the result will be written.
desc The protein description.
seq The protein sequence.
way The way to make the translation.
Definition at line 358 of file seqio.cpp.
References error(), and MEMORY_ALLOCATION_ERROR.
get_exp_protein_mass()
double get_exp_protein_mass ()
Function which allows to get the mass given for the protein mass.
Returns
The mass.
Definition at line 499 of file seqio.cpp.
References error(), FALSE, protein_mass, protein_mass_given, and USAGE_ERROR.
Referenced by fprint_configuration(), and print_configuration().
get_fasta_filename()
char* get_fasta_filename ()
Function which allows to get the name of the opened file.
Returns
The name of opened fasta file.
Definition at line 480 of file seqio.cpp.
References fasta_file_name.
Referenced by fprint_configuration(), fprint_configuration_xml(), and print_configuration().
get_reversed_sequence()
char* get_reversed_sequence ()
Function which returns the reverse of the current protein sequence.
Returns
The protein sequence reversed.
Definition at line 115 of file seqio.cpp.
References error(), MEMORY_ALLOCATION_ERROR, result, and SeqBuffer.
Referenced by main().
get_specie()
char* get_specie ()
Function which allows to get the current specie wanted from the fasta file.
Returns
The current specie.
Definition at line 486 of file seqio.cpp.
References specie.
Referenced by fprint_configuration(), fprint_configuration_xml(), is_simulated_wanted_protein(), and print_configuration().
getDesc()
char* getDesc ()
Function which returns the description of the current protein in the FASTA file.
Returns
The description.
Definition at line 144 of file seqio.cpp.
References DescBuffer.
Referenced by main().
getEntry()
int getEntry (long * offset)
Function to position the cursor on the nearest entry from the offset position.
Parameters
offset The position.
Returns
Int that indicates if the function has worked or not.
Definition at line 398 of file seqio.cpp.
References DbFile, nextEntry(), and Offset.
getSeq()
char* getSeq ()
Function which returns the sequence of the current protein in the FASTA file.
Returns
The protein sequence.
Definition at line 109 of file seqio.cpp.
References SeqBuffer.
Referenced by main().
is_a_wanted_protein()
int is_a_wanted_protein ()
Function which indicates if the current protein is wanted or not.
Returns
TRUE or FALSE (according to util.h).
Definition at line 434 of file seqio.cpp.
References DescBuffer, error(), FALSE, free_formula(), get_formula_from_sequence(), get_weight(), mass_tolerance, protein_mass, protein_mass_given, SeqBuffer, specie, TRUE, and USAGE_ERROR.
Referenced by main().
is_exp_protein_mass_activated()
int is_exp_protein_mass_activated ()
Function which allows to know if a experimental protein mass has been already set.
Returns
TRUE or FALSE (according to util.h).
Definition at line 511 of file seqio.cpp.
References protein_mass_given.
Referenced by fprint_configuration(), and print_configuration().
is_parsing_started()
unsigned int is_parsing_started ()
Function that indicates if the parsing of the database is started or not i.e. nextEntry has been called at least one time.
Returns
TRUE or FALSE according to util.h.
Definition at line 150 of file seqio.cpp.
References parsing_is_started.
Referenced by set_minimum_matched_peptide_number(), and set_minimum_peptide_number().
nextEntry()
int nextEntry (long * offset)
Function which allows to move until the next entry.
Parameters
offset The current position.
Returns
int that indicates if the function has worked correctly or not.
Definition at line 156 of file seqio.cpp.
References DbFile, DescBuffer, error(), EXECUTION_ERROR, FALSE, MALLOC_STEP_SEQ, Offset, parsing_is_started, SeqBuffer, and TRUE.
Referenced by getEntry(), and main().
set_exp_protein_mass()
void set_exp_protein_mass (double mass)
Procedure to set a for the experimental protein mass.
Parameters
mass The weight.
Warning
The mass tolerance is by defaut 10%.
Definition at line 492 of file seqio.cpp.
References protein_mass, protein_mass_given, and TRUE.
Referenced by load_float_keyword().
set_specie()
void set_specie (const char * wanted_specie)
Procedure which allows to specifie the wanted specie to study.
Parameters
wanted_specie The wanted specie.
Warning
This call will be refused if a fasta file is already opened.
Definition at line 406 of file seqio.cpp.
References DbFile, error(), MEMORY_ALLOCATION_ERROR, specie, USAGE_ERROR, and WARNING.
Referenced by load_string_keyword().
Variable Documentation
DbFile
FILE * DbFile =NULL
Variable that corresponds to the opened FASTA file.
Definition at line 71 of file seqio.cpp.
Referenced by fastafclose(), fastafopen(), getEntry(), nextEntry(), and set_specie().
DescBuffer
char * DescBuffer =NULL
Variable that corresponds to the buffer holding the current protein description.
Definition at line 66 of file seqio.cpp.
Referenced by fastafclose(), getDesc(), is_a_wanted_protein(), and nextEntry().
fasta_file_name
char * fasta_file_name =NULL
Variable that corresponds to the name of the opened FASTA file.
Definition at line 86 of file seqio.cpp.
Referenced by fastafclose(), fastafopen(), and get_fasta_filename().
mass_tolerance
double mass_tolerance =10.0
Variable that indicates the according tolerance around the experimental protein mass.
Definition at line 101 of file seqio.cpp.
Referenced by is_a_wanted_protein().
Offset
long Offset = (long) 0
Variable that corresponds to the offset in the FASTA file.
Definition at line 76 of file seqio.cpp.
Referenced by fastafopen(), getEntry(), and nextEntry().
parsing_is_started
unsigned int parsing_is_started = FALSE
Variable that indicates if the parsing of the database has started or not.
Definition at line 106 of file seqio.cpp.
Referenced by is_parsing_started(), and nextEntry().
protein_mass
double protein_mass =0.0
Variable that corresponds to the experimental protein mass.
Definition at line 91 of file seqio.cpp.
Referenced by get_exp_protein_mass(), is_a_wanted_protein(), and set_exp_protein_mass().
protein_mass_given
int protein_mass_given = FALSE
Variable that indicates if the a experimental protein mass has been given.
Definition at line 96 of file seqio.cpp.
Referenced by get_exp_protein_mass(), is_a_wanted_protein(), is_exp_protein_mass_activated(), and set_exp_protein_mass().
SeqBuffer
char * SeqBuffer =NULL
Variable that corresponds to the buffer holding the current protein sequence.
Definition at line 61 of file seqio.cpp.
Referenced by fastafclose(), get_reversed_sequence(), getSeq(), is_a_wanted_protein(), and nextEntry().
specie
char * specie =NULL
Variable that corresponds to the wanted specie.
Definition at line 81 of file seqio.cpp.
Referenced by fastafclose(), get_specie(), is_a_wanted_protein(), and set_specie().