tables.cpp File Reference
Implementation of the methods defined in tables.h.
#include `tables.h`
Functions
void tables_initialisation ()
Procedure which initialises all the useful data : element table, amino acid table, ...
void free_tables ()
Procedure which frees the memory allocated for all the useful data : element table, amino acid table ,...
 element_t * get_element_table ()
Function which allows to get the element table.
int get_element_table_size ()
Function which returns the size of the element table.
 aa_CF_t get_amino_acid (char aa)
Function which returns the amino acid structure associated to a given char.
 aa_CF_t * get_amino_acid_table ()
Function which allows to get the amino acid table.
 formula_t * get_formula_from_sequence (char * sequence)
Function which allows to get the formula of the proteic sequence given.
char get_amino_acid_at_index (int index)
Function wich returns the amino acid structure associated to an index, it uses the array that contains the amino acids in an increasing order (according to the mass).
Variables
 element_t * element_table =NULL
Variable that corresponds to the table which will contain all the chemical elements.
int nb_elements =0
Variable that corresponds to the total number of chemical elements.
 aa_CF_t * amino_acid_table =NULL
Variable that corresponds to the table which will contain all the amino acid formulae.
char sorted_amino_acid_table [] = {'G','A','S','P','V','T','C','I','L','N','D','Q','K','E','M',' H','U','F','R','Y','W', 'O'}
Detailed Description
Implementation of the methods defined in tables.h.
Author
Jean-Charles BOISSON (2005-2008).
Warning
Copyright USTL
 This software is governed by the CeCILL-C license under French law and abiding by the rules of distribution of free software.
Function Documentation
free_tables()
void free_tables ()
Procedure which frees the memory allocated for all the useful data : element table, amino acid table ,...
Definition at line 77 of file tables.cpp.
References amino_acid_table, element_table, free_amino_acid_table(), free_element_table(), free_peptide_link(), and nb_elements.
Referenced by ascq_me_configuration_cleaning().
get_amino_acid()
 aa_CF_t get_amino_acid (char aa)
Function which returns the amino acid structure associated to a given char.
Parameters
aa The char which corresponding to an amino acid.
Returns
The amino acid structure associated (aa_CF_t).
Definition at line 97 of file tables.cpp.
References amino_acid_table, error(), EXECUTION_ERROR, amino_acid_CF::form, and USAGE_ERROR.
Referenced by digest(), get_formula_from_sequence(), get_formulae_of_peptides(), get_peptide_formula_from_another_protein(), and get_peptide_formula_from_index().
get_amino_acid_at_index()
char get_amino_acid_at_index (int index)
Function wich returns the amino acid structure associated to an index, it uses the array that contains the amino acids in an increasing order (according to the mass).
Parameters
index The index.
Returns
a char representing an amino acid.
Definition at line 148 of file tables.cpp.
References sorted_amino_acid_table.
get_amino_acid_table()
 aa_CF_t* get_amino_acid_table ()
Function which allows to get the amino acid table.
Returns
The amino acid table.
Definition at line 117 of file tables.cpp.
References amino_acid_table.
Referenced by tables_initialisation().
get_element_table()
 element_t* get_element_table ()
Function which allows to get the element table.
Returns
The element table.
Definition at line 85 of file tables.cpp.
References element_table.
Referenced by tables_initialisation().
get_element_table_size()
int get_element_table_size ()
Function which returns the size of the element table.
Returns
The element table size.
Definition at line 91 of file tables.cpp.
References nb_elements.
Referenced by init_distrib(), load_modifications(), set_peptide_charge(), and tables_initialisation().
get_formula_from_sequence()
 formula_t* get_formula_from_sequence (char * sequence)
Function which allows to get the formula of the proteic sequence given.
Returns
The formula.
Definition at line 123 of file tables.cpp.
References add_formula(), copy_formula(), error(), amino_acid_CF::form, get_amino_acid(), get_util_formula(), sequence, and USAGE_ERROR.
Referenced by fprintf_ascq_me_results(), fprintf_ascq_me_results_table_form(), fprintf_ascq_me_results_xml(), is_a_wanted_protein(), and printf_ascq_me_results().
tables_initialisation()
void tables_initialisation ()
Procedure which initialises all the useful data : element table, amino acid table, ...
Definition at line 69 of file tables.cpp.
References AMINO_ACID_TABLE, amino_acid_table, ELEMENT_TABLE, element_table, get_amino_acid_table(), get_element_table(), get_element_table_size(), init_peptid_link(), and nb_elements.
Referenced by load_configuration().
Variable Documentation
amino_acid_table
 aa_CF_t * amino_acid_table =NULL
Variable that corresponds to the table which will contain all the amino acid formulae.
Definition at line 64 of file tables.cpp.
Referenced by free_tables(), get_amino_acid(), get_amino_acid_table(), and tables_initialisation().
element_table
 element_t * element_table =NULL
Variable that corresponds to the table which will contain all the chemical elements.
Definition at line 54 of file tables.cpp.
Referenced by fprint_element_table(), free_tables(), get_element_table(), print_element_table(), and tables_initialisation().
nb_elements
int nb_elements =0
Variable that corresponds to the total number of chemical elements.
Definition at line 59 of file tables.cpp.
Referenced by free_tables(), get_element_table_size(), and tables_initialisation().
sorted_amino_acid_table
char sorted_amino_acid_table[] = {'G','A','S','P','V','T','C','I','L','N','D','Q','K','E','M',' H','U','F','R','Y','W', 'O'}
Definition at line 66 of file tables.cpp.
Referenced by get_amino_acid_at_index().