util.cpp File Reference
Implementation of the methods defined in util.h.
#include `util.h`
Functions
int jump_commentaries (FILE *file, char commentary)
Function which allows to jump commentaries in a file.
int jump_a_line (FILE *file)
Function which allows to jump a line from a file.
int jump_blanks (FILE *file)
Function which allows to not take the blanks of a file.
char * read_line (FILE *file)
Function which allows to read a line and put it in a char*.
char * read_until (FILE *file, char separator)
Function which allows to read a char* until a special separator, EOF or the end of the line.
void delete_final_blanks (char *buffer)
Procedure which deletes all the final blanks of a char*.
void activate_verbose_mode ()
Procedure which activates the verbose mode.
int is_verbose_mode_activated ()
Function which indicates if the verbose mode is activated.
char * add_chains (const char *first, const char *second)
Function which allows to append the second char* to the end of the first char*.
int equals (double value1, double value2, double delta)
Tool function which indicates if 2 double are equal or not according to a delta.
double * copy_double_array (double *src, int src_size)
Tool Function which makes the copy of a double array.
int compare_doubles (const void *first, const void *second)
Tool Function which compares two double ==> useful for making qsort.
Variables
int verbose_activation = FALSE
Variable that indicates if the verbose mode is activated or not.
Detailed Description
Implementation of the methods defined in util.h.
Author
Jean-Charles BOISSON (2005-2008).
Warning
Copyright USTL
 This software is governed by the CeCILL-C license under French law and abiding by the rules of distribution of free software.
Function Documentation
activate_verbose_mode()
void activate_verbose_mode ()
Procedure which activates the verbose mode.
Definition at line 223 of file util.cpp.
References TRUE, and verbose_activation.
Referenced by main().
add_chains()
char* add_chains (const char * first, const char * second)
Function which allows to append the second char* to the end of the first char*.
Returns
The result char*
This method is equivalent to the C++ method '+' for the strings.
Definition at line 235 of file util.cpp.
References error(), MEMORY_ALLOCATION_ERROR, result, and USAGE_ERROR.
Referenced by main().
compare_doubles()
int compare_doubles (const void * first, const void * second)
Tool Function which compares two double ==> useful for making qsort.
Parameters
first The first double.
second The second double.
Returns
-1, 0 or 1 according to the first <, = or > second.
Definition at line 314 of file util.cpp.
copy_double_array()
double* copy_double_array (double * src, int src_size)
Tool Function which makes the copy of a double array.
Parameters
src The original double array.
src_size The size of the array.
Returns
The copie.
Definition at line 279 of file util.cpp.
References error(), MEMORY_ALLOCATION_ERROR, and USAGE_ERROR.
delete_final_blanks()
void delete_final_blanks (char * buffer)
Procedure which deletes all the final blanks of a char*.
Parameters
buffer The char* to process.
Definition at line 196 of file util.cpp.
References error(), MEMORY_ALLOCATION_ERROR, and USAGE_ERROR.
equals()
int equals (double value1, double value2, double delta)
Tool function which indicates if 2 double are equal or not according to a delta.
Parameters
value1 The first value.
value2 The second value.
delta The delta.
Returns
TRUE or FALSE
Definition at line 273 of file util.cpp.
References FALSE, and TRUE.
Referenced by compute_equivalent_peptides().
is_verbose_mode_activated()
int is_verbose_mode_activated ()
Function which indicates if the verbose mode is activated.
Returns
TRUE or FALSE.
Definition at line 229 of file util.cpp.
References verbose_activation.
Referenced by init_distrib(), main(), optimized_isotopic_distribution(), and read_spectrum().
jump_a_line()
int jump_a_line (FILE * file)
Function which allows to jump a line from a file.
Parameters
file The file to read.
Returns
The result of the command fscanf <=> number of characters read on the last called or EOF.
Definition at line 83 of file util.cpp.
Referenced by get_element_table(), jump_commentaries(), and load_modifications().
jump_blanks()
int jump_blanks (FILE * file)
Function which allows to not take the blanks of a file.
Parameters
file The file where we want to avoid the blanks.
Returns
The result of the command fscanf <=> number of characters read on the last called or EOF.
Definition at line 96 of file util.cpp.
References error(), and USAGE_ERROR.
Referenced by read_until().
jump_commentaries()
int jump_commentaries (FILE * file, char commentary)
Function which allows to jump commentaries in a file.
Parameters
file The file to read.
commentary The character designing a line as a commentary.
Returns
The result of the command fscanf <=> number of characters read on the last called or EOF.
NB: a commentary is a line beginning by a special character or an empty line beginning by ' '.
Definition at line 57 of file util.cpp.
References jump_a_line().
Referenced by get_element_table(), load_configuration(), load_modifications(), and read_spectrum().
read_line()
char* read_line (FILE * file)
Function which allows to read a line and put it in a char*.
Parameters
file The file opened on the line to read.
Returns
The char* read.
Definition at line 119 of file util.cpp.
References read_until().
Referenced by get_element_table(), load_boolean_keyword(), load_float_keyword(), load_int_keyword(), load_string_keyword(), and load_unsigned_int_keyword().
read_until()
char* read_until (FILE * file, char separator)
Function which allows to read a char* until a special separator, EOF or the end of the line.
Parameters
file The file where the char* has to be read.
separator The separator.
Returns
the char* read.
Definition at line 124 of file util.cpp.
References error(), jump_blanks(), MEMORY_ALLOCATION_ERROR, and USAGE_ERROR.
Referenced by get_element_table(), load_modifications(), and read_line().
Variable Documentation
verbose_activation
int verbose_activation = FALSE
Variable that indicates if the verbose mode is activated or not.
Definition at line 54 of file util.cpp.
Referenced by activate_verbose_mode(), and is_verbose_mode_activated().