.TH "src Directory Reference" 3 "Fri Nov 3 2023" "Version 1.0.6" "ASCQ_ME" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBinclude\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBaa\&.cpp\fP"
.br
.RI "Implementation of the methods defined in \fBaa\&.h\fP\&. "
.ti -1c
.RI "file \fBascq_me\&.cpp\fP"
.br
.RI "ASCQ_ME main program\&. "
.ti -1c
.RI "file \fBascq_me_configuration\&.cpp\fP"
.br
.RI "Implementation of the methods defined in \fBascq_me_configuration\&.h\fP\&. "
.ti -1c
.RI "file \fBascq_me_display\&.cpp\fP"
.br
.RI "Implementation of the methods defined in \fBascq_me_display\&.h\fP\&. "
.ti -1c
.RI "file \fBcleavage\&.cpp\fP"
.br
.RI "Implementation of the methods defined in \fBcleavage\&.h\fP\&. "
.ti -1c
.RI "file \fBcomplex\&.cpp\fP"
.br
.RI "Implementation of the methods defined in \fBcomplex\&.h\fP\&. "
.ti -1c
.RI "file \fBdigest\&.cpp\fP"
.br
.RI "Implementation of the methods defined in \fBdigest\&.h\fP\&. "
.ti -1c
.RI "file \fBerror\&.cpp\fP"
.br
.RI "Implementation of the methods defined in \fBerror\&.h\fP\&. "
.ti -1c
.RI "file \fBfft4g\&.cpp\fP"
.br
.RI "The complete fft package is also in the ASCQ_ME sources in fft_src\&. "
.ti -1c
.RI "file \fBformula\&.cpp\fP"
.br
.RI "Implementation of the methods defined in \fBformula\&.h\fP\&. "
.ti -1c
.RI "file \fBisodistrib\&.cpp\fP"
.br
.RI "Implementation of the methods defined in \fBisodistrib\&.h\fP\&. "
.ti -1c
.RI "file \fBmodification_table\&.cpp\fP"
.br
.RI "Implementation of the methods defined in \fBmodification_table\&.h\fP\&. "
.ti -1c
.RI "file \fBmodifications_for_digestion\&.cpp\fP"
.br
.RI "Implementation of the methods defined in \fBmodifications_for_digestion\&.h\fP\&. "
.ti -1c
.RI "file \fBseqio\&.cpp\fP"
.br
.RI "Implementation of the methods defined in \fBseqio\&.h\fP\&. "
.ti -1c
.RI "file \fBtables\&.cpp\fP"
.br
.RI "Implementation of the methods defined in \fBtables\&.h\fP\&. "
.ti -1c
.RI "file \fButil\&.cpp\fP"
.br
.RI "Implementation of the methods defined in \fButil\&.h\fP\&. "
.in -1c
