.TH "include Directory Reference" 3 "Fri Nov 3 2023" "Version 1.0.6" "ASCQ_ME" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBaa\&.h\fP"
.br
.RI "Definition of an amino acid\&. "
.ti -1c
.RI "file \fBascq_me_configuration\&.h\fP"
.br
.RI "Definition of the useful things to configure ASCQ_ME\&. "
.ti -1c
.RI "file \fBascq_me_display\&.h\fP"
.br
.RI "Definition of the methods to use and display ASCQ_ME results\&. "
.ti -1c
.RI "file \fBcleavage\&.h\fP"
.br
.RI "Description of methods allowing to know where enzymes can cut proteins\&. "
.ti -1c
.RI "file \fBcomplex\&.h\fP"
.br
.RI "Definition of the complex structure and basic methods to use complex numbers\&. "
.ti -1c
.RI "file \fBdigest\&.h\fP"
.br
.RI "Description of methods allowing to make the digestion of proteins\&. "
.ti -1c
.RI "file \fBerror\&.h\fP"
.br
.RI "Definition of the error management\&. "
.ti -1c
.RI "file \fBformula\&.h\fP"
.br
.RI "Definition of a chemical formula\&. "
.ti -1c
.RI "file \fBindex\&.h\fP"
.br
.RI "Main page of the ASCQ_ME documentation\&. "
.ti -1c
.RI "file \fBisodistrib\&.h\fP"
.br
.RI "Definition of the methods to make simulated spectrum computation\&. "
.ti -1c
.RI "file \fBmodification_table\&.h\fP"
.br
.RI "Definition of a lot of things to use post-translational modifications\&. "
.ti -1c
.RI "file \fBmodifications_for_digestion\&.h\fP"
.br
.RI "Definition of the specifications for the post-translation modifications in the digestion case\&. "
.ti -1c
.RI "file \fBseqio\&.h\fP"
.br
.RI "Description of methods allowing the using of FASTA files and other useful things linked to them\&. "
.ti -1c
.RI "file \fBtables\&.h\fP"
.br
.RI "Description of methods that allows to manipulate amino acids easier\&. "
.ti -1c
.RI "file \fButil\&.h\fP"
.br
.RI "Definition of several useful things\&. "
.in -1c
