.TH "cleavePointList" 3 "Fri Nov 3 2023" "Version 1.0.6" "ASCQ_ME" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cleavePointList \- Structure representing a list of cleavage point <=> cleavage rules\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cleavage\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBsize\fP"
.br
.RI "The rules number\&. "
.ti -1c
.RI "\fBcp_t\fP * \fBcp\fP"
.br
.RI "The different rules\&. "
.in -1c
.SH "Detailed Description"
.PP 
Structure representing a list of cleavage point <=> cleavage rules\&. 
.PP
Definition at line 90 of file cleavage\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBcp_t\fP* cleavePointList::cp"

.PP
The different rules\&. 
.PP
Definition at line 95 of file cleavage\&.h\&.
.PP
Referenced by cpl_fprint(), cpl_isCleavage(), cpl_isCleavage2(), free_cplt(), and stringToCpl()\&.
.SS "int cleavePointList::size"

.PP
The rules number\&. 
.PP
Definition at line 93 of file cleavage\&.h\&.
.PP
Referenced by cpl_fprint(), cpl_isCleavage(), cpl_isCleavage2(), free_cplt(), and stringToCpl()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ASCQ_ME from the source code\&.
