.TH "composition" 3 "Fri Nov 3 2023" "Version 1.0.6" "ASCQ_ME" \" -*- nroff -*-
.ad l
.nh
.SH NAME
composition \- Structure representing an element with its quantity, for example: C2\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <formula\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBelement_t\fP * \fBelement\fP"
.br
.RI "The element\&. "
.ti -1c
.RI "int \fBquantity\fP"
.br
.RI "The element quantity\&. "
.in -1c
.SH "Detailed Description"
.PP 
Structure representing an element with its quantity, for example: C2\&. 
.PP
Definition at line 89 of file formula\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBelement_t\fP* composition::element"

.PP
The element\&. 
.PP
Definition at line 92 of file formula\&.h\&.
.PP
Referenced by add_element(), affect_atom(), copy_composition(), formula_tochar(), get_weight(), init_distrib(), optimized_isotopic_distribution(), and sub_formula()\&.
.SS "int composition::quantity"

.PP
The element quantity\&. 
.PP
Definition at line 94 of file formula\&.h\&.
.PP
Referenced by add_element(), affect_atom(), copy_composition(), formula_tochar(), get_weight(), optimized_isotopic_distribution(), and sub_formula()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ASCQ_ME from the source code\&.
