.TH "complex" 3 "Fri Nov 3 2023" "Version 1.0.6" "ASCQ_ME" \" -*- nroff -*-
.ad l
.nh
.SH NAME
complex \- Basic complex structure with a real part and an imaginary part\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <complex\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBRe\fP"
.br
.RI "The real part\&. "
.ti -1c
.RI "double \fBIm\fP"
.br
.RI "The imaginary part\&. "
.in -1c
.SH "Detailed Description"
.PP 
Basic complex structure with a real part and an imaginary part\&. 
.PP
Definition at line 57 of file complex\&.h\&.
.SH "Field Documentation"
.PP 
.SS "double complex::Im"

.PP
The imaginary part\&. 
.PP
Definition at line 62 of file complex\&.h\&.
.PP
Referenced by complex_addition(), complex_conjugate(), complex_multiplication(), complex_power(), complex_subtraction(), copy_spectrum(), init_distrib(), next_simulated_spectrum(), optimized_isotopic_distribution(), read_spectrum(), and set_exp_spectrum()\&.
.SS "double complex::Re"

.PP
The real part\&. 
.PP
Definition at line 60 of file complex\&.h\&.
.PP
Referenced by complex_addition(), complex_conjugate(), complex_multiplication(), complex_power(), complex_subtraction(), compute_correlation(), copy_spectrum(), init_distrib(), integral_normalization(), next_simulated_spectrum(), optimized_isotopic_distribution(), penalization_factor(), read_spectrum(), and set_exp_spectrum()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ASCQ_ME from the source code\&.
