.TH "enzyme_list" 3 "Fri Nov 3 2023" "Version 1.0.6" "ASCQ_ME" \" -*- nroff -*-
.ad l
.nh
.SH NAME
enzyme_list \- Structure that represents an enzyme list\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cleavage\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBsize\fP"
.br
.RI "The list size\&. "
.ti -1c
.RI "\fBenz_t\fP * \fBenz\fP"
.br
.RI "The enzyme list\&. "
.in -1c
.SH "Detailed Description"
.PP 
Structure that represents an enzyme list\&. 
.PP
Definition at line 117 of file cleavage\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBenz_t\fP* enzyme_list::enz"

.PP
The enzyme list\&. 
.PP
Definition at line 122 of file cleavage\&.h\&.
.PP
Referenced by digest(), enzym_load(), free_enzym_table(), get_enzyme_number(), get_used_enzyme(), and print_enzyme_table()\&.
.SS "int enzyme_list::size"

.PP
The list size\&. 
.PP
Definition at line 120 of file cleavage\&.h\&.
.PP
Referenced by enzym_load(), free_enzym_table(), get_enzyme_number(), and print_enzyme_table()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ASCQ_ME from the source code\&.
