.TH "isotop" 3 "Fri Nov 3 2023" "Version 1.0.6" "ASCQ_ME" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isotop \- An isotopic structure represents the isotop of an element\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <formula\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBrelative_mass\fP"
.br
.RI "The relative mass\&. "
.ti -1c
.RI "double \fBisotopic_composition\fP"
.br
.RI "The isotopic composition\&. "
.in -1c
.SH "Detailed Description"
.PP 
An isotopic structure represents the isotop of an element\&. 
.PP
Definition at line 60 of file formula\&.h\&.
.SH "Field Documentation"
.PP 
.SS "double isotop::isotopic_composition"

.PP
The isotopic composition\&. 
.PP
Definition at line 65 of file formula\&.h\&.
.PP
Referenced by affect_atom(), copy_isotop(), get_element_table(), init_distrib(), and optimized_isotopic_distribution()\&.
.SS "double isotop::relative_mass"

.PP
The relative mass\&. 
.PP
Definition at line 63 of file formula\&.h\&.
.PP
Referenced by affect_atom(), copy_isotop(), get_element_table(), get_weight(), init_distrib(), and optimized_isotopic_distribution()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ASCQ_ME from the source code\&.
