.TH "post_translational_modification" 3 "Fri Nov 3 2023" "Version 1.0.6" "ASCQ_ME" \" -*- nroff -*-
.ad l
.nh
.SH NAME
post_translational_modification \- Definition of a post-translationam modification\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <modifications_for_digestion\&.h>\fP
.SH "Detailed Description"
.PP 
Definition of a post-translationam modification\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ASCQ_ME from the source code\&.
