.TH "post_traductional_modification" 3 "Fri Nov 3 2023" "Version 1.0.6" "ASCQ_ME" \" -*- nroff -*-
.ad l
.nh
.SH NAME
post_traductional_modification
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <modifications_for_digestion\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBtype\fP"
.br
.RI "The modification type (FIXED or VARIABLE)\&. "
.ti -1c
.RI "int \fBmodification\fP"
.br
.RI "The associated modification index (see \fBmodification_table\&.h\fP)\&.*/\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 67 of file modifications_for_digestion\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int post_traductional_modification::modification"

.PP
The associated modification index (see \fBmodification_table\&.h\fP)\&.*/\&. 
.PP
Definition at line 72 of file modifications_for_digestion\&.h\&.
.PP
Referenced by add_modification(), and get_global_modification_index()\&.
.SS "int post_traductional_modification::type"

.PP
The modification type (FIXED or VARIABLE)\&. 
.PP
Definition at line 70 of file modifications_for_digestion\&.h\&.
.PP
Referenced by add_modification(), and get_modification_type()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ASCQ_ME from the source code\&.
